### ISSUE TITLE
Specific constraints for areas

### ISSUE THREAD

**Issue by saramaxwell** [prioritizr/prioritizr#129]
Hello,
I've been using prioritizr successfully to determine a PA that is a single unit (continuous) using add_contiguity_constraints(), but I am wondering if there are ways to do the following:
- Create a network of PAs limited to, say 10 PAs of a specific size.  

I've tried using add_boundary_penalties but either it doesn't quite conform, or it I find that the program stops running.

Many thanks!

**Comment by jeffreyhanson** [comment]
Hi,

Yeah, this is a pretty tricky problem. Ideally, prioritizr would add a custom function that lets you specify the minimum size of each reserve to achieve this (https://github.com/prioritizr/prioritizr/issues/29), but the maths for this are over my head (contributions are more than welcome). However, since you are interested in a fixed number of reserves that each have a minimum size, we can re-use existing prioritizr functions to achieve this. The trick is that we create a "zone" for each different reserve (defined as a contiguous set of selected planning units), create a "fake" feature with 1s in all planning units and set a target for this feature to control the minimum reserve size, and use contiguity constraints for each "zone" to force the planning units selected in each "zone" to create a "reserve".

I'll copy in a quick example using prioritizr's simulated data below. I'm sorry that I don't have much time today to document it properly, so please let me know if you have any questions. Also, please note that this is a very complex problem, so you will need to Gurobi to obtain a solution in a feasible period of time and it might take a very long time (e.g. hours, days) to solve problems with many planning units, reserves, or features.

```
# load packages
library(prioritizr)
library(tibble)
library(dplyr)
library(raster)

# load data
data(sim_pu_raster, sim_features)

# set variables
number_of_reserves <- 4
minimum_reserve_size <- 2
feature_targets <- 0.1 # minimum proportion of each feature held in solution

# create a fake feature with 1s in all planning units to constrain reserve sizes
fake_feature <- sim_pu_raster
fake_feature[!is.na(fake_feature)] <- 1

# create cost data,
# since we are using zones to represent reserves, we need to create
# a raster stack with the same cost layer duplicated for each reserve
cost_data <- sim_pu_raster[[rep(1, number_of_reserves)]]

# create feature data
feature_data <- addLayer(sim_features, fake_feature)
feature_zone_data <-
  append(list(feature_data)[rep(1, number_of_reserves)],
         list(zone_names = paste0("reserve_", seq_len(number_of_reserves)),
              feature_names = c(paste0("f", seq_len(nlayers(sim_features))),
                                "fake")))
feature_zone_data <- do.call(zones, feature_zone_data)

# create contiguity matrix to make individual reserves,
# this matrix specifies that all of the planning units selected in each zone 
# must be fully contiguous
cont_matrix <- diag(number_of_reserves)

# create feature target data
## add targets for features,
## since each zone is for a different reserve, we set targets that can
## be met using contributions from all zones together
target_data <- tibble(
  feature = feature_names(feature_zone_data)[seq_len(nlayers(sim_features))],
  zone = list(zone_names(feature_zone_data))[rep(1, nlayers(sim_features))],
  type = "absolute",
  sense = ">=",
  target = feature_targets * cellStats(sim_features, "sum"))

## add targets to ensure minimum reserve sizes,
target_data <- bind_rows(
  target_data,
  tibble(feature = rep("fake", number_of_reserves),
         zone = as.list(zone_names(feature_zone_data)),
         type = "absolute",
         sense = ">=",
         target = minimum_reserve_size))

## print target data
print(target_data)

# build problem
p <-
  problem(cost_data, feature_zone_data) %>%
  add_min_set_objective() %>%
  add_manual_targets(target_data) %>%
  add_contiguity_constraints(zones = cont_matrix) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.01)

# print problem
print(p)

# solve problem
raw_sol <- solve(p)

# here each layer in our RasterStack is a different reserve so we need
# to combine data in the different layers to obtain a single RasterLayer
raw_sol2 <- category_layer(raw_sol)
sol <- raw_sol2
sol[!is.na(raw_sol2)] <- 0
sol[!is.na(raw_sol2) & (raw_sol2 > 0.5)] <- 1

# plot solution
plot(sol)
```

**Comment by jeffreyhanson** [comment]
@saramaxwell, I haven't heard back from you about this issue so I'll close it for now. If you have any more questions about this topic, please feel free to reopen the issue.

**Comment by saramaxwell** [comment]
Thank you Jeff!  Apologies - this has been slow moving, and moving even slower given the pandemic.  I will get in touch if I have additional questions!

Best,
SM
