### ISSUE TITLE
Distribution of costs in planning unit data

### ISSUE THREAD

**Issue by CDuchardt** [prioritizr/prioritizr#142]
Hello,

I'm relatively new to spatial prioritization software but am trying to learn the ins and outs of prioritizr to do some fairly large scale prioritization for restoration.

I ran into an issue with my own datasets which are much larger than the built-in datasets but have recreated the issue using code from problem #97 

The basic issue is that I get an error whenever I try to use the add_max_features_objective() with my own datasets :  
Error: Warning in presolve_check.OptimizationProblem(compile(x)) :
  feature targets with very high target weights (> 1e+6)
Error in .local(a, b, ...) : 
  problem failed presolve checks, for more information see ?presolve_check

I did some digging, and the issue appears to lie with my cost data, which is distributed like so:

![image](https://user-images.githubusercontent.com/64870183/81117320-1f7a0700-8ee4-11ea-8e36-29d43e60c5ec.png)

```
#####-prioritizr problem with spread of costs-----------
require(prioritizr)
#bringing in built-in datasets
data(sim_pu_raster, sim_features)

## Resample PUs and features based on finer grain
res3<-2000
mod_pu3 <- raster(nrow=res3, ncol=res3, xmn=0, xmx=1, ymn=0, ymx=1)
mod_pu3 <- resample(sim_pu_raster, mod_pu3, method='ngb')
mod_feat3 <- raster(nrow=res3, ncol=res3, xmn=0, xmx=1, ymn=0, ymx=1)
mod_feat3 <- resample(sim_features, mod_feat3, method='ngb')


#examine the histogram of the original cost data
hist(mod_pu3$layer)

#generate more skewed cost data
mod_pu3_1<-mod_pu3 
values(mod_pu3_1)[values(mod_pu3_1) >= 200] = 100

mod_pu3_2<-mod_pu3 
values(mod_pu3_2)[values(mod_pu3_2) >= 200] = 10

#newly skewed costs
hist(mod_pu3_1$layer)
hist(mod_pu3_2$layer)

#first problem with original cost data runs fine
p0<- problem(mod_pu3 , mod_feat3) %>%
  add_absolute_targets(10000)%>%
  add_max_features_objective(budget=40000000) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.1, presolve = 2, time_limit = 500)
s0<-solve(p0)
plot(s0)
as.data.frame(feature_representation(p0, s0))


#problem with "somewhat" skewed cost data runs fine
p1 <- problem(mod_pu3_1, mod_feat3) %>%
  add_absolute_targets(10000)%>%
  add_max_features_objective(budget=40000000) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.1, presolve = 2, time_limit = 500)

s1<-solve(p1)
plot(s1)


#problem with "very" skewed cost data throws the error
p2 <- problem(mod_pu3_2, mod_feat3) %>%
  add_absolute_targets(10000)%>%
  add_max_features_objective(budget=40000000) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.1, presolve = 2, time_limit = 500)

s2<-solve(p2)
plot(s2)


```

I can easily modify my costs to be less skewed and still meet my research needs, but I'm wondering what is causing the error. Again, I'm very new to these analyses so thanks in advance for your patience!

**Comment by jeffreyhanson** [comment]
Hi,

Sorry for the slow response. Exact algorithm solvers operate with a certain level of precision (e.g. 1e-6 for Gurobi by default). This means that when you have numbers that are really small (e.g. <1e-6) then the solver will effectively round them down to zero which can cause problems (e.g. targets may not be able to met if all values <1e-6 are rounded down to zero, or planning units are treated as "free" if values are rounded down to zero). Additionally, really large numbers (e.g. > 1e+6) can also cause problems if/when the ILP solver needs to calculate things like ratios/fractions/percentages. So, as a general rule, we recommend ensuring that values are between 1e-6 and 1e+6 (following Gurobi's documentation). If you want to learn more about the details, I'd really recommend reading Gurobi's documentation and recommend practices for dealing with numerical issues (see here: https://www.gurobi.com/documentation/9.0/refman/num_grb_guidelines_for_num.html). 

I hope that helps? Does that answer your question?

**Comment by CDuchardt** [comment]
Hi Jeff, thanks so much for your response and your patience! I understand now that this is more of a Gurobi issue than a prioritizr one per se, but I'd like a bit more clarification if possible.

 I understand the very low and very high constraints, but are these constraints on all parameters  (features values, costs, targets, budgets)? If so, how would you (and the other authors of the package) recommend dealing with large spatial extents/fine grains with >1,000,000 pixels? It seems like this isn't prohibitive in all cases (as in the toy example provided, as well as in the literature), but is perhaps a function both of the large number of pixels and an either very large or very small value in another parameter (such as cost)? In the coarsest of terms, if I'm understanding correctly, things should run smoothly if all parameters are  1E-6 <x<1E+6. It may still be fine outside of those bounds but is more sensitive to the magnitude of the other parameters?

Thanks again, and apologies for my tenuous ecologist's grasp of the quantitative aspects. In the long term we are hoping to use prioritizr in the creation of a tool for managers, so the better my own qualitative grasp the better we can convey it to them.

**Comment by jeffreyhanson** [comment]
No worries - happy to help!

The 1e-6/1e+6 guidelines correspond to the data values (e.g. planning unit costs, budgets, amount of each feature within each planning unit, weight values). They don't apply the size/dimensioanlity  of the data (e.g. number of planning units, number of features, number of constraints). Gurobi can still solve problems with data values outside these range, it might just take longer than needed or -- in a worst case scenario -- it might output strange/invalid solutions (e.g. if it assumes all planning units with costs < 1e-6 are equal to zero). 

So, when working with large spatial extents/fine grains (e.g. 1M+ planning units), you might need to rescale the data units so that they fall within this 1e-6/1e+6 range. For example, if you're dealing with land acquisition costs (e.g. one planning unit might cost $10'000'000), you might need to rescale the units so they are in millions (e.g. divide costs by 1'000'000 so the panning unit has a value of `10` and not `10'000'000`). Additionally, if your feature data denote the amount of habitat available for each species within each planning unit, then you might have values like `50'000'000`  m^2. You could fix this by rescaling it to km^2 or you could rescale the values so that they are a proportion (i.e. values between 0 and 1) of the total amount of area within the planning unit (e.g. if a feature has a value of `50'000'000` [m^2] habitat within a planning unit that is 100'000'000 m^2 in size, then the planning unit is assigned a value of `0.5`). When doing this, you may also need to adjust the targets too (e.g. if you manually calculate the targets and set them using `add_absolute_targets`).

**Comment by jeffreyhanson** [comment]
@CDuchardt, I think I've answered your questions and I haven't heard back from you in a while, so I'll close this issue for now. Please feel free to re-open it if I missed any of your questions in my replies, or if you have any more questions.
