### ISSUE TITLE
Cannot load newest version with code provided

### ISSUE THREAD

**Issue by crleopold** [prioritizr/prioritizr#145]
Hi, I cannot load version 5.0.1 using CRAN; I get 4.1.5. 
If I use GitHub with package remotes as listed on prioritzr page, I receive the following error: 
Error: Failed to install 'prioritizr' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)

I found this trying to use 'ferrier_score' which is not in version 4.1.5.
--I very much appreciate these new package updates.

**Comment by jeffreyhanson** [comment]
I just double checked the R code on the README and it works for me (i.e. I can install the version 5+ from CRAN and install the dev version on GitHub). May I ask what version of R are you using? If it's a bit old, then you might need to update it. Have you installed the latest version of the remotes R package? If you post the output of `sessionInfo()` then that might help me track down exactly what's going on.

**Comment by crleopold** [comment]
Good morning,
Thank you. I had to do a deeper dive and found some issues on my end -
government computer security stuff was causing some problems.
I resolved it. My apologies for the rookie mistake!

**Comment by jeffreyhanson** [comment]
Ah ok - glad to hear you were able to sort it out! I'll close this issue now but please feel free to reopen it if you have any further questions.

**Comment by crleopold** [comment]
Hi,
I have a follow-up question because I am still unable to use gurobi. I have
R 4.0.2, remotes 2.1.1, and Gurobi 9.0.2 with updated prioritizr.
Gurobi says it only supports R 3.6, but here I was recommended to update
R...which version of R do you use?
Maybe I have some internal problem with my computer, but I have uninstalled
and deleted all R associated files, same for Gurobi. Now, my next step will
be to try an older version of R supported by Gurobi and try again, but I
have to wait until I have more time next week.
Restarts, etc., and I still get this error below. I copied sessioninfo()
below as well.
lsymphony is much slower, and I expect it is what is used for the
irreplaceability calcs. That took a long time (and is there a way to
parallelize it with do.par, or already built-in?)
Thanks for your assistance,
Christina

> install.packages("C:/gurobi902/win64/R/gurobi_9.0-2.zip", repos = NULL,
type = "win.binary")
Installing package into ‘C:/Users/cleopold/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
package ‘gurobi’ successfully unpacked and MD5 sums checked
> library(gurobi)
Loading required package: slam
Error: package or namespace load failed for ‘gurobi’:
 package ‘gurobi’ was installed before R 4.0.0: please re-install it

sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United
States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] slam_0.1-47

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     rstudioapi_0.11  knitr_1.29       raster_3.1-5
magrittr_1.5     tidyselect_1.1.0 lattice_0.20-41  R6_2.4.1
 [9] rlang_0.4.6      dplyr_1.0.0      tools_4.0.2      parallel_4.0.2
grid_4.0.2       xfun_0.15        tinytex_0.24     ellipsis_0.3.1
[17] yaml_2.2.1       tibble_3.0.1     lifecycle_0.2.0  crayon_1.3.4
purrr_0.3.4      vctrs_0.3.1      codetools_0.2-16 glue_1.4.1
[25] sp_1.4-2         compiler_4.0.2   pillar_1.4.4     generics_0.0.2
pkgconfig_2.0.3

**Comment by jeffreyhanson** [comment]
Hi,

Sorry, yes, you are absolutely correct. The pre-built gurobi R package distributed with the latest version of Gurobi is not compatible with R version 4.0.0. To use the gurobi R package with R version 4.0.0, you will need to install the gurobi R package from its source code. A colleague of mine emailed Gurobi about this and they sent them the source code for the gurobi R package so they can use Gurobi with R version 4.0.0. Could you please send me an email (my email address is listed on my GitHub profile), and I can forward you the source code for the gurobi R package? After installing the package from source, you can run Gurobi from R version 4.0.0. 

To answer your question about my setup, I have several different versions of R installed on my computer. I use R version 4.0.0 for developing and testing R packages (I should update this to 4.0.2 but haven't gotten to it yet). Most of my projects (e.g. scientific papers I'm working on) use either R 3.6.* or 3.5.* - but this is because I have very strict control over how my computer runs R code (e.g. I use Linux which makes this sort of stuff easier).

**Comment by jeffreyhanson** [comment]
Since we were able to resolve this issue over email, I'm closing this issue now.
