### ISSUE TITLE
Release candidate?

### ISSUE THREAD

**Issue by ricschuster** [prioritizr/prioritizr#154]
Hi @jeffreyhanson 

Should I push `prioritizr` up to CRAN, given ec21d15?

**Comment by jeffreyhanson** [comment]
Yeah, could you please double check both prioritizr and prioritizrdata pass R-devel on WinBuilder? If they do, could you please submit prioritizr to CRAN? After the new version of prioritizr is on CRAN, could you please submit prioritizrdata to CRAN?

**Comment by ricschuster** [comment]
On it.
Thanks @jeffreyhanson !

**Comment by jeffreyhanson** [comment]
Prioritizr seems to be having issues on AppVeyor/Windows (i.e. https://ci.appveyor.com/project/jeffreyhanson/prioritizr/builds/34359718) - did the WinBuilder check pass?

**Comment by ricschuster** [comment]
Weird. All three winbuilder checks (old, current, dev) worked and only have one note each (_Packages suggested but not available for checking: 'gurobi'_). winbuilder didn't even complain about package size anymore.

Do you think we should submit anyways?

**Comment by jeffreyhanson** [comment]
Hmm, AppVeyor seems to complain that the utf8 package ins't installed which is (sometimes apparently?) used to print tibble objects. Maybe WinBuilder isn't throwing any errors because it already has utf8 installed? Let me try adding the utf8 package to Suggests in the DESCRIPTION to see if that fixes it.

Also, after you replied, a person created a new issue (#155) about a potential bug. I think it's already been fixed in the GitHub version, but it would be good to verify that its been fixed before we release the new version on CRAN?

**Comment by ricschuster** [comment]
Sounds good on both points. Will wait to hear from you re: utf8 package and have a look at #155 to make sure the current development version resolves the issue.

**Comment by jeffreyhanson** [comment]
Ok great! I'll let you know when these issues have been resolved.

**Comment by jeffreyhanson** [comment]
Ok, the utf8 package is needed to print tibble objects, but it's not currently available as a Windows binary for R-devel (https://cran.r-project.org/web/packages/utf8/index.html). It is currently available as a source file, Windows binary file for R-release, and Mac OSX binary file for R-release. So, the tests pass on WinBuilder because it already has utf8 installed, Travis Linux because it can build the packages from source, and Travis Mac because it is configured to only check for R-release. So, I think this means we can (1) wait for the Windows binary file for R-devel to appear on CRAN to test with AppVeyor on R-devel, or (2) change AppVeyor to check for R-release (so it can install the utf8 package)? What option would you prefer? I'm re-configuring AppVeyor now to verify that (2) actually works and then we can proceed with the option that you would prefer?

**Comment by jeffreyhanson** [comment]
The [AppVeyor build just passed when configured with R-release](https://ci.appveyor.com/project/jeffreyhanson/prioritizr) so I think this demonstrates that the issue is with failing to install utf8 package (indeed if this is also evidenced in the log files).

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson !

If its okay with you, I'd say we go for the CRAN release as Travis and Winbuilder checks were all successful.
What do you think?

**Comment by jeffreyhanson** [comment]
Yeah - I think that makes the most sense. We're still waiting for the Tavis OSX check to finish (https://travis-ci.org/github/prioritizr/prioritizr/builds/713092576), but once/if that finishes succesfully I think we can submit it?

**Comment by ricschuster** [comment]
Sounds good!

**Comment by jeffreyhanson** [comment]
Ok - all the builds have now passed (https://travis-ci.org/github/prioritizr/prioritizr/builds/713092576), so I think we can submit to CRAN now?

**Comment by ricschuster** [comment]
Submitted to CRAN.
Fingers crossed!

**Comment by jeffreyhanson** [comment]
Awesome - thanks!

**Comment by ricschuster** [comment]
on CRAN now
