### ISSUE TITLE
data.table dependency

### ISSUE THREAD

**Issue by DanRosauer** [prioritizr/prioritizr#18]
Running a line such as
`p <- marxan_problem("input_sp.dat")`

Returns the error:
`Error in load_file("PUNAME", x, input_dir) :
  the "data.table" package needs to be installed to load Marxan data files.`

Could you make data.table a dependency, so it gets installed automatically?

(please ignore if it is already, but install happened to fail in this case)

**Comment by jeffreyhanson** [comment]
Thanks for raising this issue!

Yeah, so originally we listed data.table under Suggests and not Imports is because data.table is only used in the `marxan_problem` function, and data.table can take a while to install, so I thought users might appreciate not having to install data.table if they don't need it.

What do you think? Do you think people would rather have data.table installed automatically even if it meant that they may not use it?

**Comment by DanRosauer** [comment]
R packages often install lots of dependencies which are only needed for some function you would never use...    So I can see the point of being more selective - fair point.  It is nice though to install a package, and it all just works....    Up to you.

**Comment by ricschuster** [comment]
Thanks for raising this Dan. 
@jeffreyhanson, as data.table isn't that large a package, why don't we just move it to the Imports?

**Comment by jeffreyhanson** [comment]
I've added the _data.table_ package to Imports in version 1.0.2.0 (https://github.com/prioritizr/prioritizr/commit/e01c77e359aaa9586640134d261dde9d45bbf757)
