### ISSUE TITLE
Time to solve prioritizr problems

### ISSUE THREAD

**Issue by negira** [prioritizr/prioritizr#192]
Hi! I am running prioritizr with Gurobi optimizer. I am using a fishnet of 1km (I have 154,308 units) and 33 features (the distribution of 33 species). I am trying to solve the problem but the analysis has been running for more than 15 days. Is this normal? In the manual it mentions that the percentage of progress of the analysis will appear, however this percentage does not appear to me. What should I do? 
 
![image](https://user-images.githubusercontent.com/81947522/113539913-7bda2080-95a4-11eb-9b26-2f4b88e7fbbb.png)

**Comment by jeffreyhanson** [comment]
Hi, thanks for reaching out! I wouldn't have expected a problem with ~150k planning units and ~30 features to take that long if the problem formulation is relatively simple. What exactly does the problem formulation look like? Can you post the relevant part of your script where you create a `problem` and customize it by adding components to it? Also, have you tried setting the number of threads to maximize performance (e.g. `parallel::detectCores(TRUE) - 1`)?

**Comment by jeffreyhanson** [comment]
Also, can you please confirm that Gurobi isn't using most of of your computers RAM?

**Comment by negira** [comment]
Hi, thanks for answer. I copied the relevant part of the script: 
unidades=raster("unidades.asc")
features=stack(Agalychnis_moreleti,Aquiloeurycea_cephalica,Craugastor_hobartsmithi,Craugastor_mexicanus,Craugastor_occidentalis,Craugastor_omiltemanus,Craugastor_pygmaeus,Craugastor_saltator,Dendropsophus_sartori,Dermophis_oaxacae,Eleutherodactylus_dilatus,Eleutherodactylus_syristes,Exerodonta_juanitae,Exerodonta_melanomma,Exerodonta_pinorum,Exerodonta_sumichrasti,Hyla_arboricola,Hypopachus_ustus,Incilius_gemmifer,Incilius_perplexus,Isthmura_bellii,Isthmura_maxima,Lithobates_berlandieri,Lithobates_forreri,Lithobates_omiltemanus,Lithobates_sierramadrensis,Ptychohyla_erythromma,Ptychohyla_leonhardschultzei,Rhinophrynus_dorsalis,Sarcohyla_pentheter,Sarcohyla_thorectes,Thorius_grandis,Thorius_omiltemi)
locked_in=raster("in.asc")
locked_out=raster("out.asc")
p9=problem(unidades,features)%>%add_min_set_objective()%>%add_relative_targets(0.1)%>%add_locked_in_constraints(locked_in)%>%add_locked_out_constraints(locked_out)%>%add_feature_contiguity_constraints()%>%add_boundary_penalties(penalty = 0.01)%>%add_binary_decisions()%>%add_gurobi_solver(gap = 0)
s9=solve(p9)

I think there is still RAM
![image](https://user-images.githubusercontent.com/81947522/113599572-6f85b000-9604-11eb-89a7-3419162d5350.png)

I haven't set the number of threads to maximize performance, I will do it, do you think it will be enough with this?

**Comment by negira** [comment]
I also send you the planning unit data in case something is wrong with it. 
[unidades.zip](https://github.com/prioritizr/prioritizr/files/6259458/unidades.zip)

**Comment by jeffreyhanson** [comment]
Thanks so much for providing all these details - it's really helpful!

Yeah, I think the reason this is taking so long is because the problem formulation is very complex. I agree - it doesn't look like the RAM is the issue here. Also, I think the planning unit data looks fine. Specifically, the feature contiguity constraints (i.e. added by the `add_feature_contiguity_constraints()` function) are very complex (mathematically speaking) and, as a consequence, generally take a really long time to solve. For example, in my own work (if I remember correctly), it took about 1 week (with 20 cores and 60GB RAM) to generate a solution to a problem with the `add_feature_contiguity_constraints()` and ~1,000 planning units and 8 species. I also used some tricks to speed it up too (see below). 

May I ask how important are the feature contiguity constraints to your work?

* If they aren't critical, I would recommend dropping them because it will make things a lot easier. For example, could you use the boundary penalties (alone) to promote connectivity? Although this function won't produce a prioritisation that represents species in spatially contiguous blocks of land, it might produce a prioritization that is clumped enough to (broadly speaking) maintain connectivity? If you have information on how different planning units impede/facilitate species' movements/gene flow across the study area, you could also try using connectivity penalties? For example, given your knowledge of the species, would you expect places with higher human pressure impede species' movements (e.g. see https://doi.org/10.1038/s41598-017-15304-w)?

* If they are critical to your work, then things will get very difficult and it will (most likely) take a while before you have a solution (e.g. it took me 6 months of playing around with different data pre-processing options and failed attempts before I could get a Gurobi run to finish in 1 week). Specifically, I would recommend doing the following things:
    1. Get access to a system with many more cores (e.g. 20+ if possible), because this will help reduce processing time a lot. If you can't get access to such a system, then I don't think it is really possible to generate a solution with these constraints (unless you drastically reduce the total number of planning units, e.g. to 100). I'm sorry if this isn't possible, I just don't want to waste your time.
    2. Drop the boundary penalties to reduce run time. 
    3. Pre-process the data to make it easier to solve. For instance, you will (almost certainly) need to reduce the total number of planning units  (e.g. you could do this by focusing on one region of the study area, or making the planning units a coarser resolution with `raster::aggregate`). You could also (1) exclude planning units that are not occupied by any species (i.e. set their cost values as `NA`), (2) exclude small isolated patches from the species distribution data (e.g. a planning unit with a presence that is surrounded by planning units with absences) by setting those presences as absences.
    4. You can help Gurobi by giving it a good starting solution (this helps a lot). To achieve this, you can run the prioritization process for each species separately to obtain a solution for each species, and then combine all of those solutions together.
    5. Since these constraints are very complex, you will likely need to relax the optimality gap to obtain a solution within a feasible period of time (e.g. try 0.2, 0.25 or 0.3).
    6. Unfortunately, this will likely require a lot of trial-and-error to find out what works (e.g. using different sized planning units, different pre-processing options). To help get an idea how well pre-processing options/attempts work, you could set a time limit for preliminary attempts and see how far Gurobi gets for a given attempt (e.g. you could set a time limit of 1 day). As a rule of thumb, if Gurobi can't get to within 50% of optimality after 1 day, then you might as well stop it and try pre-processing the data again to make it simpler to solve.

Does that help? I'm sorry that I can't provide a simple fix to get this working. Please let me know if you have any follow up questions, or if anything I've written isn't clear?

**Comment by AlecNelson** [comment]
Not the original commenter, but I have a similar challenge with running a prioritization problem with the Gurobi solver and wanted to ask about the "NodefileStart" parameter as one possible solution:

Specifically I am running a problem with 1,130,526 planning units (100m raster cells), solving for min_set_objective at a 0.1 gap and binary_decisions with a range of relative_targets (currently exploring different values of targets). When I add_neighbor_constraints, even low values, the solver will report that it has run out of memory (10001.  OUT OF MEMORY.) on a machine with 16GB of RAM and 6 cores. Having just seen your suggestions to the question above, I will certainly try to implement those steps to working out a solution that completes within a reasonable time and fits the conservation problem setting I am working towards. 

However, I also wanted to ask about the Gurobi parameter that is suggested in their documentation, namely the "NodefileStart" parameter. I can't find much documentation about this parameter, especially in R or prioritzr, but it appears to be one solution to problems that exceed the system memory by writing problems temporarily to the harddrive.

When I scour the prioritzr documentation, I've found the get_solver_parameter and set_solver_parameter options for modifying problem objects, but I can't seem to figure out what the id value would be for "NodefileStart" (running "p1$set_solver_parameter("NodefileStart",0.5)" returns "Error in res(x, ...) : parameter with matching name not found").

Any assistance you could provide on this particular approach to getting past this problem of running out of memory beyond the helpful suggestions you've mentioned above would be very much appreciated! Thanks!

My problem setting function:

p1 <- problem(sav_pu, sav_features) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1, 0.1, 0.1, 0.6, 0.6, 0.6) %>%
  add_binary_decisions() %>%
  add_boundary_penalties(0.0005, 0.5) %>%
  add_gurobi_solver(gap = 0.1, time_limit = 7200, threads = 2, first_feasible = FALSE)%T>%
  run_calculations()

p1$set_solver_parameter("NodefileStart",0.5) ##returns "Error in res(x, ...) : parameter with matching name not found"

**Comment by negira** [comment]
Thank you very much for your suggestions Jeff, it was really helpful.
I will follow these steps and I will drop the contiguity constraints. I
will let you know how I am doing.

**Comment by jeffreyhanson** [comment]
@AlecNelson, thanks for raising this issue. Since this is a bit different from the isssue originally raised by @negira, I've created a new issue to discuss this further (see https://github.com/prioritizr/prioritizr/issues/193).

**Comment by jeffreyhanson** [comment]
@negira, no worries, I'm glad that was helpful. Please let me know if you have any further questions.

**Comment by negira** [comment]
Hi Jeff, I tried some of the suggestions you made, dropping contiguity
constraints considerably reduces time as you said, although it still takes
a lot of time with boundary penalties. If I also drop boundary penalties it
finishes in a few minutes. I also have another question about the
conservation features; is it better to use continuous or binary
conservation features? I have tried both options (the values of continuous
features are probability of presence of the species and move from 0 to 1)
using different relative targets for each species according to threat and
endemicity. The result with binary features is more fragmented. In general
I prefer to use continuous features because a lot of information is lost
with the conversion from continuous to binary but I have a doubt about the
limit values that the algorithm considers when using continuous features. I
mean I suppose that the algorithm will try to take for each species the
units with higher values (of probability of presence in this case) but is
there a threshold? For example 0.8, 0.5... Can this threshold be
controlled? Is it possible that for some species the algorithm had
selected, for the solution, planification units with very low values like
0.1 or 0.2 instead of the higher ones in order to meet the other
requirements? Because in this case it may be better to use binary features.
Or the solution will always contain the units with the highest values for
each species? for example if the relative target for one species is 0.1,
then the algorithm will take the 10% of the planification units with the
highest values for this species? I hope I have explained myself well
enough. Thank you very very much for your time!

**Comment by jeffreyhanson** [comment]
Excellent! I'm glad it's able to generate solutions within a reasonable period of time now. 

Yeah, adding boundary penalties does increase the time by a lot. However, the amount of time required to solve with boundary penalties does depend on the penalty value used. So, if you haven't already, it might be worth trying some really small boundary penalty values to see what happens (e.g. 1e-5, or 1e-8).

Yeah, tricky question: should you use (i) continuous probability of presence data or (ii) apply a threshold to the probabilities to use predicted presence/absence data? The benefit of using the continuous probabilities is that you don't need to impose a strict threshold definition of what probability is present vs. absent. However, the issue with using continuous probabilities is that the prioritization might select a set of places with very low probability of presences to meet the target (unless you are using reserve selection tools explicitly designed for probabilities, e.g. see [MarProb](https://conbio.onlinelibrary.wiley.com/doi/abs/10.1111/cobi.13681)). Based on what your previous post, it sounds like it might be helpful for me to provide some examples showing how the twhat the targets  provide examples of how the targets are used to generate prioritizations, so I've included this information in the example -- sorry

For instance, let's say you're working with the min set objective and a single feature (to simplicity, this is a bad idea in practice), if you set a target of 10%, then you're saying that the solution must contain at least 10% of the sum of all the probabilities values for that feature. So, if the sum of all the probability values was 12 and and you set a target of 10%, then your solution needs to select a set of planning units -- that in combination -- contain probabilities for this feature that sum to 1.2 (because `12 * 10% = 1.2`). So, for example, a solution that contains two planning units -- each with a probability of 0.6 -- would meet the target (because `0.6 + 0.6 >= 1.2`). Another solution that contains three planning units -- with probabilities of 0.1, 0.9, and 0.3 -- would also meet the target (because `0.1 + 0.9 + 0.3 >= 1.2`). However, a solution that contains three planning units --- with probabilities all equal to 0.1 -- would not meet the target (because `0.1 + 0.1 + 0.1 >= 1.2` is not correct) and so prioritizr would never actually return such a solution (excepting bugs). So, when we use a target of 10% in this example, we can be confident that the sum of the probabilities is greater than or equal to 1.2. The issue with this is that a solution containing 100 planning units -- each with a probability value of 0.02 -- would meet the target (because `100 * 0.02 >= 1.2`). Although this solution meets the target, the actual probability of the species occurring in many planning units is relatively small. So, there is a good chance that the prioritization could meet the target, but could fail to actually meet the target if implemented (e.g. because the species does not occur in very many of the planning units). This issue is further exacerbated by the fact that many species distribution models (but see zero-inflated models) don't predict a probability of exactly zero, but some value that is effectively zero (e.g. 1e-3) which still provides a non-zero contribution towards meeting a target.

Because of this issue, I (personally) prefer applying thresholds to continuous probabilities -- based on statistical measures, e.g. see [`dismo::threshold`](https://rdrr.io/cran/dismo/man/threshold.html))  -- to help ensure that prioritizations adequately represent species in places they are likely to occur. You could also try clamping the continuous probabilities (i.e. given a threshold, assign all values below the threshold to zero, and keep the values above the threshold as continuous) to help avoid loosing information on which planning units are "highly likely to contain species" vs. "extremely likely to contain species" (we sort of did something similar to this for the climatic refugia data in [this paper](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2664.13718), see Figures S45 and S46).

In terms of making sure that the prioritizations are not spatially fragmented, I would recommend using the boundary penalties to control for this. Although using continuous probability data will spatially cluster prioritizations to some extent, they won't let you specify how spatially clustered the prioritization should be -- and a prioritization based on continuous probability data (alone) might be overly clustered (or not clustered enough) depending on the purpose of the prioritization and the spatial auto-correlation of the probability data.

Does that help? Please let me know if anything I've written isn't clear?

**Comment by negira** [comment]
Hi Jeff, your example is very clear. I clamped the continuous probabilities
using a threshold (10 percentile training presence) as you suggested. I've
been able to run the problem with a boundary penalty value of 1e-5 and also
with a value of 0.1. I attached the solution with a boundary penalty of
0.1. But now I have another problem: when I try to evaluate the performance
of the solution or calculate irreplaceability I get an error: "function
could not be found". This happens with all eval... functions
like eval_n_summary() or  eval_rare_richness_importance(). I have the same
problem with these functions even with the built-in data sets that are
distributed with the *prioritizr R* package (I am using this tutorial;
https://cran.r-project.org/web/packages/prioritizr/vignettes/prioritizr.html#package-overview
). I do not know what's happening. Thank you very much for your help!

**Comment by jeffreyhanson** [comment]
Ok excellent! Yeah, the `eval_n_summary` (and other functions starting with `eval_`) function is really new and so is only available in the latest version of prioritizr (i.e. versions >= 7.0.1). Could you please try re-installing the package from CRAN (ie. using the R code: `install.packages('prioritizr')`) to make sure you have the latest version? If it still doesn't work after that, could you please post your session information (i.e. output from `sessionInfo()`) so we can work out what's going wrong?

**Comment by negira** [comment]
I re-installed the package and it works now, thank you for your help!

**Comment by jeffreyhanson** [comment]
Excellent! Glad its working now.

**Comment by jeffreyhanson** [comment]
I'll close this issue since it seems like it's all working now, but please feel free to re-open the issue or post a new one if you have any further questions.
