### ISSUE TITLE
Cuts portfolio and order of objectives for alternative solutions

### ISSUE THREAD

**Issue by gboussarie** [prioritizr/prioritizr#197]
Hi everyone. Thank you so much for providing such a useful tool.

For the context, I am running prioritizr (Gurobi) in a multi-zones problem, and will be in interaction with managers to delineate priority areas for different activities (fishing, sediment extraction, wind farms...) _vs._ biodiversity and ecosystem services protection.
A lot of people are counting on these areas for income or would not agree with a given final proposed plan for diverse reasons. Also, the "cost" is transferable meaning that for instance fishing can be transferred elsewhere, while I include fisheries objectives to keep core fishing areas in economic zones. As a result, the proposed solutions must be flexible and quite different from each other, while the cost is not the only factor of choice if it stays within reasonable limits.

I have explored the different options and I believe the cuts portfolio is the best way to solve this problem. However, I also used a high BLM to obtain clumped zones and therefore acceptable solutions for managers. One problem is that past the third or fourth obtained solution, the zoning does not make sense because of the way the cuts portfolio works I guess (adds penalties for similar solutions, but I am not sure this performs well with 5 different types of zones and very different number of PUs on each type of zone? I will have to check how it works exactly. Also, the penalty to avoid similar solutions gets "higher" than the BLM past the first 2-3 solutions and it takes over, giving very scattered solutions). Anyway, this is another "issue" for me, and not my question here.

My issue is that when I shuffle the order of the objectives prior to solving the problem, I always obtain the same best solution but past the first best solution, I obtain different ones (sometimes same in different order). I was thinking about doing this to keep the best, say, 3 solutions for each sequence of objectives, and getting rid of the very similar solutions by using a custom code and kappa index or something similar. Before doing so in a very dirty way, have you thought about developing something like that (meaning shuffling objectives then using cuts portfolio then getting rid of similar solutions)? Maybe I missed it somewhere? Computation time is not a major issue here given the size of the problem.

Thanks a lot ! 
Germain

**Comment by jeffreyhanson** [comment]
Hi @gboussarie,

Thanks for reaching out! Yeah, your work sounds really interesting!

In general, I would recommend using the [add_gap_portfolio()](https://prioritizr.net/reference/add_gap_portfolio.html) function because it can generate multiple solutions much, much faster than all the other portfolios and it can also generate solutions that are relatively different from each other if you use a relaxed gap parameter (e.g. use a gap of 0.5 for 50% from optimality). Although this function requires using Gurobi, this shoudn't be an issue since it sounds like you have Gurobi installed? Also, broadly speaking, you would ideally want thousands of different solutions to generate a portfolio.

Also, regarding the cuts portfolio, it works by iteratively re-solving a problem multiple times. Within each iteration, it adds constraints to ensure that previous solutions are not feasible, and so each iteration should return a distint solution. It doesn't add constraints/variables to prefer solutions that are different from previous solutions, so you can end up with solutions that are very similar if you use it to generate a small number of solutions. As such, this portfolio isn't really that useful because it can take a very long time to obtain multiple solutions that are different from each other. 

Yeah, good question. If you have multiple solutions -- and some of them are more similar or different to each other -- how do you identify which solutions are different from each other? One approach is create a table that contains information on the selection of planning units within each solution (i.e. each row is a different planning unit, each column is a different solution, and cell values contain solution status [e.g. 1 or 0]). Then, you can use clustering (e.g. hierachical clustering, see `base::hclust`, or k-medoids, see `clusterR::Cluster_Medoids`) or ordination (e.g. NMDS, see `vegan::metaMDS`) to characterize variation among differnet solutions and group similar solutions togeaher. For more information on this, please see [Harris et al 2014](https://doi.org/10.1111/1365-2664.12345). They also recommend using Jaccard distances when running ordination and cluster analyses.

Also, you mention that you're dealing with multiple objectives. Just to clarify, are you reffering to different features when you say this (e.g. different species or land use classes), or are using multiple linear penalties?

Does that help? Please let me know if anything's not clear, or if I can provide additional details?

**Comment by gboussarie** [comment]
Hi Jeffrey,

Thank you for your reactivity !

I incorrectly ruled out the gap portfolio after some quick tests with a small gap (0.1) so I had very similar results. I understand my mistake, thank you. Indeed I use Gurobi and after some tests, I believe obtaining thousands of solutions will not be so painful in the simple scenarios I start with. When adding hypotheses on different scenarios, it might be a bit tricky in terms of computation time (e.g. high blm, zone-specific boundaries, contiguity constraints - I might rule out the latter), but I will see that and adjust after some testing. In this regard, your documentation and the resolved issues section is very useful.

I understand the cuts portfolio now and will probably not use it then, thanks.

I will definitely try what you suggest, that makes sense and the paper you suggest is helpful. I have seen that approach somewhere else in practice (in a tutorial) but cannot find it anymore. It won't take much time to code it anyway.

You are right, I am dealing with multiple features, not objectives (species, ecosystem services, catch values, windfarm potentials...). I will also probably include multiple linear penalties at some point.

This helps a lot, thanks again. I will not hesitate to contact you again if needed.

**Comment by jeffreyhanson** [comment]
Hi,

No worries - happy to help!

Yeah -- depending on the spatial distribution of your costs and features (and other considerations too) -- you might only end up with very similar solutions (i.e. in terms of the location of priority areas) when using the gap portfolio with a small optimality gap. Maybe try using a gap of 0.2 first and see how that goes? If you still only need up with very similar solutions maybe try increasing it further (e.g. 0.3) and see how it goes. Also, it might be worth increasing the number of solutions in the portfolio too. E.g. if you can generate 1,000 solutions really quickly, then maybe try generating 10,000 solutions to see if that helps get a range of different solutions.

Great! Yeah, please feel free to reach out again if you have any further questions. I think I've answered all your questions, so I'll close this issue now, but please feel free to reopen it if you have any more questions.
