### ISSUE TITLE
add partly binary and partly integer decision

### ISSUE THREAD

**Issue by Marie73** [prioritizr/prioritizr#199]
Hi,

there are three types of decisions in the documentation of prioritizr package (binary, proportional,  semi-continuous). For my optimization problem I need partly binary type and partly integer type of decision. Do you have some ideas how I can get this or do you think about implementation of this to your package?   

My optimization problem is equivalent to the one in this article: 

https://stackoverflow.com/questions/47879667/optimization-choosing-subset-of-sets-which-minimises-the-cost

Basically, I have list of products which I want to transport from one warehouse to another. I can take them in boxes (where can be combination of different products) or by unit. It is cheaper to take them in boxes than by unit. In the case of boxes, it is binary decision (take/not take). In terms od products, I can take 0,1,2,3,... units. The goal is take boxes and units of products which cover the list, minimaze the costs and dont overgrow the demand too much. For this i would like to use lpsymphony, because it can run parallel.

Thank you for answer
Marie

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for reaching out! It sounds like you're dealing with a type of [bin packing optimization problem](https://en.wikipedia.org/wiki/Bin_packing_problem). Is that right? To generalize your specific problem to a variant of the bin packing problem, it might be helpful to think of it as having a set of _I_ boxes and _J_ products. Given this, it sounds like you need to identify which products (_j_ in _J_) need to go into which boxes (_i_ in _I) in order to minimize the overall cost of the boxes. Here, the overall cost of the boxes depends on whether they contain at least one product or not (in other words if a box has >= 1 product it might cost _x_; but if it has no products, it will cost 0). How does that sound?

I'm sorry, this type of optimization problem is very different from those that prioritizr can solve. So, I think I don't think prioritizr will be much help here. I had a quick look (so apologies if you've already tried these methods and they don't work) and it looks like there might be other R packages that could help with this, such as the [gbp R package](https://cran.r-project.org/web/packages/gbp/vignettes/gbp-vignette.html) and [knapsack R pacakge](https://rdrr.io/rforge/knapsack/man/binpacking.html). If the cost calculations are really complex (e.g. maybe the shipping cost is a non-linear function based on the weight of the box?), then you might need to write some custom code to formulate an intger programming problem (e.g. using box capacities, product weights, cost values) that precisely matches the real-world context of the optimization problem? If you plan to do this, then you could (for example) write code to generate the vectors/matrices needed for the [lpsymhony R package](https://www.rdocumentation.org/packages/lpsymphony/versions/1.0.2/topics/lpsymphony_solve_LP) to generate a solution.

Also, by expressing this problem as a bin-packing problem, we're assuming that shipping costs only depend on box contents. But this might not actually be the case if you also need to ship different products to different warehouses, and shipping products to certain warehouses takes higher priority (e.g. because certain demands are more important, or because different warehouses have different shipping costs because they are located in different places). Is that relevant here?

Does that help? Please let me know if there's any further advice I can provide?

**Comment by Marie73** [comment]
Hello, thanks a lot for the answer.

I think that it is not a bin packing optimization, because I dont choose, what I put in a box. I choose boxes, which I transport. The boxes are already in the warehouse and they contain some combination of products. The question that the algortihm should solve is to take or not to take box as it is or take the products as units, which is more expensive. 

For example 
DATA: Let say that I need to transport: productA 15x, productB 10x. There is a box1 (10x A, 10x B | cost 20) and box2 (15x A, 50 x B | cost 65) and to take product as unit costs 2. 
SOLUTION: If I take box2, I fulfill demand, but it costs 65 and I take much more than I want. If I take box1, it is not enough. so I take the rest of product A by unit, which cost 2 per unit -> 5*2 =10. That means that to take box1 and 5x productA costs 20+10 = 30, which is less than take all products by units (15+10)*2 = 50 and less than take box2, therefore it is optimal solution. 

If I build the rij_matrix as:
     box1 box2    A_1  ....    A_15      B_1 .... B_10
A     10    15        1    ....       1           0   ....     0
B     10     50       0    ....       0           1  ....      1
I think I can use binary decision.

But what is a new problem of mine is this:
![session aborted 3](https://user-images.githubusercontent.com/85279432/121867926-bc6ebc80-cd00-11eb-8064-6371a48668c4.PNG)

It counts for 20 minutes and then it fell down. If I calculated on the smaller sample it works. 

And I am not sure if I use the calculation power which I can. Because usually are 3% CPUs used during calculation and I see at least 2 cores used in the monitoring.

**Comment by jeffreyhanson** [comment]
Ohh - I see! Thank you for clarifying that. I'm sorry, I assumed that you would have to optimize what went into each box. You're absolutely correct - if you're only working with pre-packaged then I think you could adapt prioritizr to your optimization problem.

May I ask how large the quantities of each different product are? Instead of formulating the optimization problem to contain a variable for each product that indicates the number of single product boxes to transport, I'm wondering if it would be possible to create a series of single product boxes that the optimization algorithm can select (or not) to transport? This won't scale well if the demand for certain products is very high though. For example, would something like this work (note that you could optimize the R code to reduce time spent preparing data inputs)?

```
# load packages
library(prioritizr)

# create data
## demand for products
demand <- c("product A" = 15, "product B" = 10)

## cost of shipping each product individually
single_product_cost <- c(2, 2)

## cost of each pre-packaged box
box_cost = c(20, 65)

## pre-packaged boxes with multiple products
box_data <- matrix(c(10, 10, 15, 50), nrow = 2)
rownames(box_data) = names(demand)
colnames(box_data) = c("box 1", "box 2")

# compile data for prioritizr
## create rij data for prioritizr
## these are (1) pre-packaged boxes that each contain multiple products
## and (2) individual products
rij_data <- box_data
for (i in seq_along(demand)) {
  single_boxes <- matrix(0, ncol = demand[i], nrow = nrow(box_data))
  single_boxes[i, ] <- 1
  colnames(single_boxes) <- 
    paste0(names(demand)[i], " [", seq_len(demand[i]), "]")
  rij_data <- cbind(rij_data, single_boxes)
}

## set costs for the planing units for prioritizr
## these indicate the costs of (1) transporting pre-packaged boxes
## and (2) individual products
pu_cost <- box_cost
for (i in seq_along(demand)) {
  pu_cost <- c(pu_cost, rep(single_product_cost[i], demand[i]))
}
names(pu_cost) <- colnames(rij_data)

# run prioritizr to identify solution
## build problem
p <- 
  problem(
    pu_cost, 
    data.frame(id = seq_along(demand), name = names(demand)),
    rij_data)  %>%
  add_min_set_objective() %>%
  add_absolute_targets(demand) %>%
  add_binary_decisions() %>%
  add_lpsymphony_solver(gap = 0)

## solve problem
s <- solve(p)

## print solution
names(s) <- names(pu_cost)
print(s)

# post-process solution to identify which boxes
## identify boxes to transport
transport_boxes <- colnames(box_data)[which(s[seq_len(ncol(box_data))] > 0.5)]

## identify number of products to send
n_products_to_transport <- demand * 0
for (i in seq_along(n_products_to_transport)) {
  v <- startsWith(names(pu_cost), names(demand[i]))
  n_products_to_transport[i] <- sum(s[v])
}

## print results
message("send boxes: ", paste(transport_boxes, collapse = ","))
message("additionally, send the number of products individually:")
print(n_products_to_transport)
```


Of course, this isn't as comutationally efficient as using a combination of binary (i.e. which boxes to transport) and integer variables (i.e. how many of each product to transport). I've been thinking about possible ways to implement this and think it might cause some issues. This is because we would have to add an integer decision type variable to prioritizr, and prioritizr was never really designed to work with decision variables that can take on a value greater than one. I think it would probably be easier to write up some code to implement your specific MILP problem that could be understood by a solver.

Re Rstudio crashing: Ah that's strange. I do know that lpsymphony somtimes causes errors like that on Linux and MacOS systems (e.g. when the solution is solved during the pre-solve step). Could you please try a different FOSS solver (e.g. Rsymhony or rcbc) and see how that goes?

**Comment by Marie73** [comment]
There is around 60 000 products on a warehouse. Usually there is a need to transport around 3 000 products - in sum 10 000-20 000 units. 
I am not sure, if i understand your single-product box idea correctly. Do you mean that instead of 15 columnsA in rij_matrix, I will make one column as boxA that contain 15 product A? That wont be possible to combine with other boxes, if needed - like we have in our example, where the optimal solution is box1 and just 5 units of product A.

Thank you for code, I wrote it as you with two changes: 
1.  use of sparse matrix for rij_matrix.
2. instead of add_absolute_targets, I use add_manual_targets, because in real-life problem there is a minimal demand, but maximal too, because I can not transport whatever I want and there are some business boundaries. 

Rstudio crashing: 
add_lpsymphony_solver(gap = 0.01)   ... crash / ok   ?
add_cbc_solver(threads = 30, gap = 0.01)     ... ok. rcbc seems even better than lsymphony, so thank tou for idea 
Here is my session info:
![image](https://user-images.githubusercontent.com/85279432/122271745-0c57aa00-cee0-11eb-82d1-33970ff838ec.png)

Possible solution of crashing: Make a problem smaller, put there less conditions in manual target. As I said, there is around 60K product and just 3K need to be transported. Therefore, many of minimal targets are 0, which are useless conditions. It very helps to delete them - it calculates 5 minutes instead of 25 minutes. But it doenst change the fact, that I wonder, why it sometimes crash when the probem is bigger. I would like to avoid it in future.

I have one more question, if i can. As a future development of this model, we would like to transport producst from the main warehouse to more than one other warehouses. That means that next to the demand <- c("product A" = 15, "product B" = 10), there would be second independent demand eg. demand2 <- c("product A" = 10, "product B" = 20), which should be transported to different warehouse than the first demand. Do you think that we can optimaze that in one problem()?

**Comment by jeffreyhanson** [comment]
I'm sorry @Marie73, I've been really busy the last month and dropped the ball. Would it still be helpful for me to respond to your last message, or did you figure it out?

**Comment by Marie73** [comment]
Hello, I understand.

I would still apreciate the answer to this question:

As a future development of this model, we would like to transport products from the main warehouse to more than one other warehouses. That means that next to the demand <- c("product A" = 15, "product B" = 10), there would be second independent demand eg. demand2 <- c("product A" = 10, "product B" = 20), which should be transported to different warehouse than the first demand. Do you think that we can optimaze that in one problem()? 

Would it be possible to define problem by rij_matrix and zones, where zones are target warehouses? 

There is a plan to have one main warehouse and supply the target warehouses from it. But hypothethically speking, if there are more warehouses from which we supply and more target warehouses, would it be possible to solve it in one problem? Or if there is a set of warehouses and  between all of them or some of them we can transport goods?


And just to inform you, the algorithm for suppling one warehouse from main warehouse is almost in a production in our company by this time and it looks very promising. :)

**Comment by jeffreyhanson** [comment]
Thanks for understanding. Yeah, I think it would be possible to simultaneously optimize product transport for multiple warehouses. I've written some code below to show how you can use multiple zones to acheive this (basically, each zone is a different warehouse). Note that this assumes you have one "source warehouse" that has all the boxes and products, and you're interested in transporting the boxes/protectes from this "source warehouse" to other "destination warehouses" (for lack of better terminology). What do you think? I think it works correctly - but I would recommend double checking that I haven't made any mistakes.

```
# Initalization
## load packages
library(prioritizr)
library(tibble)
library(dplyr)

# create data
## note: here we use _w1, _w2, and_w3 to indicate data for three warehouses
## that need products/boxes shipped to them

## demand for products for each warehouse
demand_w1 <- c("product A" = 15, "product B" = 10)
demand_w2 <- c("product A" = 8, "product B" = 2)
demand_w3 <- c("product A" = 5, "product B" = 4)
demand <- cbind(demand_w1, demand_w2, demand_w3)
colnames(demand) <- c("w1", "w2", "w3")
rownames(demand) <- c("product A", "product B")

## cost of shipping each product individually to each warehouse
single_product_cost_w1 <- c("product A" = 2, "product B" = 2)
single_product_cost_w2 <- c("product A" = 10, "product B" = 11)
single_product_cost_w3 <- c("product A" = 1, "product B" = 6)
single_product_cost <- cbind(
  single_product_cost_w1, single_product_cost_w2, single_product_cost_w3
)
colnames(single_product_cost) <- c("w1", "w2", "w3")
rownames(single_product_cost) <- c("product A", "product B")

## cost of shipping each pre-packaged box to each warehouse
box_cost_w1 <- c("box 1" = 20, "box 2" = 65)
box_cost_w2 <- c("box 1" = 30, "box 2" = 12)
box_cost_w3 <- c("box 1" = 52, "box 2" = 88)
box_cost <- cbind(box_cost_w1, box_cost_w2, box_cost_w3)
colnames(box_cost) <- c("w1", "w2", "w3")
rownames(box_cost) <- c("box 1", "box 2")

## define contents of pre-packaged boxes
## note that we assume that each box will contain the same contents
## regardless to which warehouse it is shipped
box_data <- matrix(c(10, 10, 15, 50), nrow = 2)
rownames(box_data) = c("product A", "product B")
colnames(box_data) = c("box 1", "box 2")

# compile data for prioritizr
## create initial matrix to use for creating matrices for each zone
### create planning units for boxes
initial_rij_box_matrix <- box_data

### create planning units for single products
n_ind_products <- apply(demand, 1, sum)
initial_rij_single_product_matrix <- matrix(
  0, nrow = nrow(demand), ncol = sum(n_ind_products)
)
colnames(initial_rij_single_product_matrix) <- c(
  rep.int(paste("single", names(n_ind_products)), n_ind_products)
)
for (i in seq_len(nrow(demand))) {
  pidx <- grep(
    names(n_ind_products)[i], colnames(initial_rij_single_product_matrix)
  )
  initial_rij_single_product_matrix[i, pidx] <- 1
}
## merge data togeather
initial_rij_matrix <- cbind(
  initial_rij_box_matrix,
  initial_rij_single_product_matrix
)

## create rij data for prioritizr
## this is a list of matrices (one for each zone), and which each contain
## a matrix that has boxes + individual products as planning units and
## warehouses as features
## and (2) individual products
rij_data <- replicate(n = ncol(demand), initial_rij_matrix, simplify = FALSE)
names(rij_data) <- colnames(demand)

## create cost data for prioritizr
pu_cost <- matrix(0, nrow = ncol(initial_rij_matrix), ncol = ncol(demand))
for (i in seq_len(ncol(demand))) {
  pu_cost[, i] <- c(
    ## add in box costs
    box_cost[, i],
    ## add in single product shipment costs
    rep.int(single_product_cost[, i], n_ind_products)
  )
}
colnames(pu_cost) <- colnames(demand)
rownames(pu_cost) <- colnames(initial_rij_matrix)

# run prioritizr to identify solution
## build problem
p <-
  problem(
    pu_cost,
    data.frame(id = seq_len(nrow(demand)), name = rownames(demand)),
    rij_data) %>%
  add_min_set_objective() %>%
  add_absolute_targets(demand) %>%
  add_binary_decisions() %>%
  add_lpsymphony_solver(gap = 0)

## solve problem
s <- solve(p)

# post-process solution
## identify boxes to transport
wid <- which(s > 0.5, arr.ind = TRUE)
results <- tibble(
  warehouse = colnames(demand)[wid[, 2]],
  item = rownames(wid)
)

## summarize results
results_summary <-
  results %>%
  dplyr::group_by(warehouse, item) %>%
  dplyr::summarize(number = length(item)) %>%
  dplyr::ungroup()

## print results
print(results_summary)
```

Yeah, I think it would also be possible to optimize transport of boxes/products between multiple different warehouses (e.g. 3 "source warehouses" that have the boxes/products, and 5 "destination warehouses" that need need the boxes/products shipped to them). Assuming that the "destination warehouses" don't need to retain a minimal number of products/boxes, I think you could do this by modifying the above example to have (i) a planning unit for each box and a planning unit for each combination of single product and source warehouse, (ii) a 3d-array for `single_product_cost` (i.e. it's currently a 2d matrix/array indexed as `[product, destination warehouse]` and you would want a 3d array indexed as `[product, destination warehouse, source warehouse]`), and (iii) use this 3d-array to create the `pu_cost` data. That's a bit trickier though - not something I can put togeather in a couple of hours sorry.

Awesome - it's really cool to hear that this stuff is being used!

**Comment by Marie73** [comment]
Hello,
thank you very much, it is exactly, what I need. 

Q1 : Is it neccesary to replicate matrix initial_rij_matrix by number of warehouses to create rij_data? This martix has in real life problem more than 500 K columns.

Q2 : Is it true, that we can pick the box 1 just to one of destination warehouses? 


I dont understand properly the paragraph about more source warehouses. It is not so important for me, but if you have time and interest, I have few questions:
Q3 : Can be one warehouse both source and destination? 
Q4 : Why the destination warehouses don't need to retain a minimal number of products/boxes? I mean we care just about, what we need to transport to destination warehouse, not what is in there.
Q5: I also dont understand this point:
(i) a planning unit for each box and a planning unit for each combination of single product and source warehouse,
-> it would create a huuuge number od planning unites. And I dont see, why we do that.

Q6 : I think that if the source warehouses are not the destination warehouses, we can imagine them as one big source warehouse. But then it would be problem to retain products in concrete source warehouses. Now we create the demand of products so it is not tie down the source warehouse.

**Comment by jeffreyhanson** [comment]
Hi,

No worries - glad to hear it works! Regarding your questions:


> Q1 : Is it neccesary to replicate matrix initial_rij_matrix by number of warehouses to create rij_data? This martix has in real life problem more than 500 K columns.

Yeah, unfortunately, this has to be done when using prioritizr. This is because prioritzr doesn't let you mix and match binary and continuous variables for planning units. If you coded up your own ILP formulation, then you could use continuous decision variables to handle the shipping of individual products - and that would massively reduce problem size and complexity.
 
> Q2 : Is it true, that we can pick the box 1 just to one of destination warehouses?

Yeah, each box is allocated to a single destination warehouse. A single box cannot be allocated to multiple destinaiton warehouses (unless there's a bug).

> Q3 : Can be one warehouse both source and destination?

Currently, the problem formulation assumes that all the products/boxes are being shipped from a certain warehouse (that's not a destination warehouse). I suppose you could treat one of the destination warehouses as a "source" warehouse by setting all the transport costs for this warehouse to zero.

> Q4 : Why the destination warehouses don't need to retain a minimal number of products/boxes? I mean we care just about, what we need to transport to destination warehouse, not what is in there.

Ah - thanks for clarifying that. Yeah, I guess it might be useful to retain a minimal unmber of products/boxes in the source warehouse if you're worried about unforeseen spikes in demand. E.g., if you have certain destination warehouses that are more important then other ones and you don't have perfect information on exactly how many products each warehouse needs at all times, then it might be worth keeping a "reserve"/"backup" set of boxes/products in the source warehouse so that products can still be shipped in emergencies (even if this means that some destination warehouses won't get products immedeately). Or maybe this isn't relevant to your situation?

> Q5: I also dont understand this point:
(i) a planning unit for each box and a planning unit for each combination of single product and source warehouse,
> -> it would create a huuuge number od planning unites. And I dont see, why we do that.

Yeah, the multi-destination warehouse problem involves deciding which box/product goes to which destination warehouse. To encode this, we create a binary decision variable (i.e. indicated by a planning unit) for each box/product and each warehouse. This is because we (or maybe just me? Perhaps someone with more experience could acheive this) can't simply create a categorical integer decision variable (e.g. reflecting different warehouse ids) to indicate which boxes/products should be shipped to different warehouses. So, for example, if we had 1 box (`Box A`) and 3 destination warehouses (e.g. `Warehouse 1`,  `Warehouse 2`,  and `Warehouse 3`), then we would need to use three binary decision variables (i.e. `Box 1 -> Warehouse 1`, `Box 1 -> Warehouse 2`, `Box 1 -> Warehouse 3`) to describe all possible scenarios. In other words, it's somewhat like [one-hot coding a categorical predictor variable in machine learning contexts](https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/).

> Q6 : I think that if the source warehouses are not the destination warehouses, we can imagine them as one big source warehouse. But then it would be problem to retain products in concrete source warehouses. Now we create the demand of products so it is not tie down the source warehouse.

Yeah, that's right! If you had multiple source warehouses, then you could encode them into the problem by (1) creating a lookup table with information on which product/box is in which source warehouse, (2) calculating costs for a given product/box based on the shipping costs for the warehouse the product/box is located in, and (3) after generating the solution, cross-reference it with the previous lookup table to see which warehouse the box/product should be shipped from. However, since multiple source warehouse could have multiple (i.e. duplicate) individul products, you would proably want to replicate the `initial_rij_single_product_matrix` matrix for each potential source warehouse to account for that fact that individual products could potentially be shipped from various source warehouses (e.g. shipping product A -> warehouse 1 might cost $12, and shipping product B -> warehouse 1 might cost $2). But that might not be too important if cost of shipping all invididual products is roughly the same regardless of which source warehouse they're shipped from. 

Does that help? Let me know if you have any follow up questions?

**Comment by jeffreyhanson** [comment]
It's been a while now since there was any activity on this issue, so I'll assume that this issue has been resolved. Please feel free to re-open this issue, or open a new issue, if the issue hasn't been resolved or if you have any follow up questions?
