### ISSUE TITLE
Output solution gap

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#204]
Hi,
Is there any way to access/ save the Gurobi solution gap (% gap from optimality) value, other than viewing it in the console when the model has finished running?

Reason I'd like this is that I'm knitting my R markdown to a pdf and I don't want the full model run output in there, just gap %.

Many thanks for all the recent updates to prioritizr, they are making it even more user friendly!
Cheers
Jason

**Comment by jeffreyhanson** [comment]
Hi,

Nah, there isn't any way to access this information for a prioritizr solution unfortunately. I had a quick look and it seems like some of the solvers could support this functionality (e.g. Gurobi), but others won't because they don't return this information (e.g. Rsymphony, rcbc). So I don't think we could add this for all solvers. Did you need this for a specific solver? 

No worries - great to hear that you're finding them useful!

**Comment by jflowernet** [comment]
Thanks Jeff. Ah yeah, I guess all the solvers have fairly different outputs. I'm using Gurobi, if you've got any ideas for a workaround?

**Comment by jeffreyhanson** [comment]
Hmm, did you just want to save the Gurobi optimizaiton log somewhere so you can refer to the gap value later, or did you want to extract the gap value to report in the knitted Rmarkdown file (e.g. pdf or html file)?

**Comment by jflowernet** [comment]
Ideally the latter

**Comment by jeffreyhanson** [comment]
Ah ok - and are you generating a single solution, or using a portfolio?

**Comment by jflowernet** [comment]
Both! I've got some scripts outputting just a single solution and knitting to pdf, and others with a look to look at several different options (e.g. varying boundary penalty)

**Comment by jeffreyhanson** [comment]
Ah - ok that makes things tricky then. If it was just a single solution, then we could manually save the Gurobi log files, import them into R, and then extract the gap using a custom wrapper function (i.e. that doesn't need to added to prioritizr). However, to get something working with the portfolio functions, we would need to add this functionality directly to prioritzr.

**Comment by jflowernet** [comment]
Ah, no worries Jeff. It was really just a 'nice to have' kind of output in the pdf, but I can keep a record somewhere else of the runtime.
Thanks for talking it through!

**Comment by jeffreyhanson** [comment]
Hmm, it gets even more tricky, because if we're use a portfolio function that relies on Gurobi's built-in pool search abilities - then Gurobi will only return a gap value for the first solution (see `mipgap` in `result` of this example: https://www.gurobi.com/documentation/9.1/examples/poolsearch_r.html). So, to implement this properly, we would need to add some maths to calculate the gap values for each subsequent solution generated using the portfolio (based on thier objective values).

**Comment by jeffreyhanson** [comment]
Ah ok - no worries. I'm sorry this isn't something I can quickly add to prioritizr today. If it would be helpful, I could look into it further sometime next week or the week after that?

**Comment by jflowernet** [comment]
You've already gone above and beyond the call of duty Jeff, thank you!

**Comment by jeffreyhanson** [comment]
Sorry - I totally forgot to respond to your last message.

Ok sounds good - yeah, please feel free to re-open if adding this functionality is more important in the future.
