### ISSUE TITLE
Strange output with constant PU cost

### ISSUE THREAD

**Issue by XavierCLL** [prioritizr/prioritizr#205]
Hi PiroritizR team :)

I have some strange output in a project with a specific configuration of PrioritizR, I'm using a constant PU cost, which means that all PU cost pixel values are equal to 1, and 36 features layers, here one example of the strange output:

![Solution Yale 4 - 30p ALT](https://user-images.githubusercontent.com/11801453/128643483-421384bd-7dcd-4496-9932-9b04b0cd82e5.png)

I understand the best process to debug and see what is happening is to create a reproducible test, I used the Salt Spring Island example for that, here is the code to reproduce something similar that I have:

```R
library(prioritizr)
library(prioritizrdata)

# load planning unit data
data(salt_pu)
salt_pu[!is.na(salt_pu[])] <- 1

# load conservation feature data
data(salt_features)

# create problem with 10% relative targets
p1 <- problem(salt_pu, salt_features) %>%
      add_min_set_objective() %>%
      add_relative_targets(0.40) %>%
      add_binary_decisions() %>%
      add_default_solver()

# solve problem
s1 <- solve(p1)
plot(s1)
```

![Rplot01](https://user-images.githubusercontent.com/11801453/128643620-c9544fe1-23bc-4b0b-8d26-0ff1add3f023.png)

if you reduce the relative targets to less than 0.3 looks good but > 0.35 looks bad, In my real data any relative target value generates a bad output, the only way to fix that is don't have a constant PU cost, what do you think what is the best way to fix that having a constant PU cost?, is it a bug? or  I'm doing something wrong?

Thank so much!
Xavier

**Comment by jeffreyhanson** [comment]
Hi Xavier,

Thanks for reaching out about this! Also, thanks so much for providing all these details - it's extremely helpful! Yeah, this strange result isn't too uncommon. I'll try and explain what's causing this and then offer some suggestions to address it.

We can see (in the first map) that the selected planning units are forming lines/bands across the study area (e.g. stretching east to west). This pattern generally indicates that the optimization problem has many optimal (or near-optimal) solutions, and so the optimization process doesn't have enough information to identify "real" / "meaningful" priority areas. In other words, the optimization problem could be under-specified such that it lacks sufficient detail/criteria to generate a meaningful prioritization.  This can often happen when using (1) equal cost values and a small number of binary features, or (2) equal cost values and a set of (mostly) non-overlapping features (e.g. different ecosystem types). As an anology, it's sort of like trying to fit a multiple regression model with multi-collinearity -- the software will fit the model and you will get a result, but you know that something's off because the coefficients are clearly incorrect (e.g. they might be really high).  Since you mention that you're using equal cost values and <100 features, I suspect that might be the case here? 

So, why do we see these lines then? I'll try and explain with some examples. Let's say that we generated a prioritization using equal cost values and a single binary feature that occurred in all planning units: if we set a 40% target, then any solution that selects 40% of the study area would be optimal. Although we might expect prioritizr to randomly select 40% of the study area in such cases; in practice, prioritizr will often return solutions that select planning units that are next to each other and form lines across the study area. This is because (1) the solvers used to generate solutions contain algorithms that can be influenced by the order that the variables appear in the optimization problem, and (2) the order of the variables that correspond to the planning units follows their spatial location (in most cases, definitely with raster format though). **Please note that this influnce/bias is normally not an issue.** For example, let's pretend we had a problem with >100 features and variable cost data (e.g. land acquisition costs): if we generated a solution by simply selecting planning units based on their variable order, then such a solution would not be near-optimal --- and so the solver would not return that solution because it does meet the optimality gap (unless we set the optimality gap to be excepionally high). However, if we supply an under-specified problem, where there are many, many optimal (or near-optimal) solutions, then this infleunce/bias does have a large affect on the solution. Does that make sense?

Ok - so what can we do about this then? The best thing to do is add more information to the problem. Here's some ideas:
1. Try adding more features to the problem. This can help the optimization process identify solutions that contain "biologically meaningful" (for lack of a better term) priority areas, by enabling it to distinguish between solutions that "double up on the same stuff" and solutions that follow "get lots of different stuff" (i.e. following the principle of complementarity). 
2. Try adding variable cost data to the problem. This helps the optimization process distinguish between costly solutions vs. cheap solutions. Note that "cost" here doesn't need to be "economic costs", it could be opportunity costs, social costs, surrogates for economic costs, or inverse metrics of habitat quality. 
3. Try using continuous data for the features instead of binary data. For example, if you were using a feature for carbon sequestration, you could use values that describe "expected amount of carbon sequestration (kg)"  instead of binary values indicating: 1 = "high amoint of carbon sequestration" and 0 = "low/none carbon sequstration (I hope that actually makes sense? I haven't done much carbon sequestration stuff...). You could also try using probability/percentage data instead of presence/absence data. Note that if you do this, then you need to be careful that the solution doesn't contain lots of places with low probability values. If that happens, one stratgy to avoid this is clamping the feature data using a threshold (i.e. set values below a certain threshold to zero, and keep values above the threshold as continuous) -- so that the prioritization won't select places with really low values but it can still distinguish between "moderate" and "high" value places.
4. If none of that works or isn't possible (e.g. because more data doesn't exist, or the decision maker doesn't care about other possible costs/features), you could add some contraints or penalties to force the optimization process to reject obviously incorrect solutions (i.e. those with strange lines). For example, you could add boundary penalties -- which will penalize solutions that have lines because they have a high total perimeter and make them highly sub-optimal -- meaning that prioritizr shouldn't return return them (unless you set a really high optimality gap value). If you try this option, then you'll likely need to coduct a boundary calibration exercises to find the "right" `penalty` value that (i) doesn't contain the lines and (ii) doesn't select too large of an area.

Does that help? Please let me know if anything I've written isn't clear or if you have any follow up questions?

**Comment by XavierCLL** [comment]
Hi Jeff!

That was an awesome and detailed answer, you are the best!

I'm completely sure that kind of setting and your answer will help everyone to understand the process to prioritize with different kinds of input data. I had the notions of the problem with cost and binary layers (my case) weren't clear for the optimization process with PrioritizR and It would have multi-optimal solutions, but you explained the problem perfectly! thanks.

With that in mind, I can handle the problem now! thanks again and you won a beer if we meet one day :)

Regards,
Xavier

**Comment by jeffreyhanson** [comment]
No worries, I'm happy to help! 

Ok, excellent! Please let me know if you run into any futher issues and I can try to help. 

Sounds great - hopefully we cross paths at a conference or something sometime in the future :)
