### ISSUE TITLE
Question: how to restrict the output by area (num. pixels)?

### ISSUE THREAD

**Issue by XavierCLL** [prioritizr/prioritizr#206]
Hi @jeffreyhanson 

I wonder if the following case is easily possible: I want to maximize the features (with the minimum cost) restricted by a maximum area or pixels to allocate, for instance, 30% of the area. I could do that using a constant PU cost witch all pixels = 1 and I used `add_max_utility_objective` equal to the number of pixels that I want to allocate, that works but of course it doesn't work with a real float PU cost, exists an easy trick/function for that? any idea?

Thanks!
Xavier

**Comment by jeffreyhanson** [comment]
Hi @XavierCLL,

Just to clarify, are you asking about generating prioritization using a budget-limited objective (e.g. `add_max_utility_objective()`) that has (1) a budget based on cost data and (2) an additional constraint to ensure that the total area doesn't exceed a certain threshold? Is that right? If so, someone else recently emailed me about this, and we've added a `add_linear_constraint()` function to a developmental branch of prioritizr that you can use to acheive this (see https://github.com/prioritizr/prioritizr/blob/lin-const/R/add_linear_constraints.R for documentation and examples). Although it needs a code review before we can merge it into the main GitHub branch, you can install it with the following code:

```
if (!require(remotes)) install.packages('remotes')
remotes::install_github('prioritizr/prioritizr@lin-const')
```

Does that help? Let me know if I've misunderstood your question, or if you have any follow up questions?

**Comment by XavierCLL** [comment]
Hi @jeffreyhanson thanks for your answer!

Sorry for the delay, I wanted to try setting up my problem with the new function implemented (nice new feature indeed), but I couldn't because I guess my problem is a bit different.

I want something similar to the function  `add_max_utility_objective` that does not use targets, is to secure as much of the features as possible without exceeding **a specific (percent of the global) area at minimum cost**, is that feasible/logical? and is it possible with PrioritizR?

Thanks again Jeff!

**Comment by jeffreyhanson** [comment]
No worries! Ah ok - I'm sorry that function wasn't able to help.

Yeah, may I ask how you want to handle trade-offs between different features? For example, let's say you wanted to maximise carbon sequestration and had two features comprising (i) above-ground sequestration capacity(in kg) and (ii) below-ground sequestration capacity (in kg). In this case, you might not really care about whether your conservation actions enhance carbon sequestration by (i) focusing only on above-ground sequestration, (ii) focusing only on above-ground sequestration, or (iii) a combination of both -- you might only care about just maximizing the total. If your conservation scenario is like this (and assuming all features have the same units), then the `add_max_utility_objective()` is useful. 

However, this issue with the `add_max_utility_objective()` is that it does not explicitly care about generating solutions that ensure adequate coverage across multiple features. In the previous example, we just wanted to maximise the total and we didn't care about whether that would happen due to managing areas for above-ground or below-ground sequestration -- so the `add_max_utility_objective()` works perfectly. If you do want to ensure that solutions maximise coverage across multiple features, then you should use a different objective function (e.g. `add_min_shortfall_objective()` or `add_max_phylo_div_objective()`). This is because these objectives allow you to specify trade-offs between different features (i.e. using targets).

For example, let's say that you wanted to increase coverage of various eco-system types, and you have four features comprising (i) forest, (ii) grassland, (iii) shrubland, and (iv) tundra. If you simply wanted to increase percentage coverage of all features as much as possible, you could use the `add_min_shortfall_objective()` with targets of 100% -- and this might return a solution that gets roughly 40% of each feature. Yet the issue with this approach is that different ecosystems types (or species, or etc) might require different levels of conservation efforts to maintain their long-term persistence. For example, if forested areas in the study system have been heavily logged in the past (e.g. current forests only encompass 10% of the historic range), then you might need to conserve a larger percentage of their current distribution (e.g. >=80% of existing forests ) for them to persist. Whereas, in our pretend study system, the tundra eco-systems might not be heavily impacted by human activities, and so a minimal level of coverage might be sufficient desirable (e.g. maybe 20% is good enough). Does that make sense? This issue is especially relevant when dealing with species, because some species are much closer to extinction than others. Put simply, is it better to have (i) 20% coverage of a CR species and 20% coverage of a LC species or (ii) 95% coverage of a CR species and 5% of a LC species (all else being equal -- which it never is in reality, but let's pretend)*? How does that sound?

Regarding the specific area constraint, you can do this by (i) using a budget limited objective function (e.g. `add_max_utility_objective()`,  `add_min_shortfall_objective()`), (ii) setting the planning unit costs values based on the spatial area of each planning unit (e.g. in km^2), (iii) setting the budget for the prioritization as 30% of the total area of the planning units. This is because the cost/budgets values don't have to be economic values - then can be what ever units/data you want. They just say that the sum of the cost values in the selected areas must not exceed the budget. Does that make sense?

I hope that helps. Sorry, I think I've rambled a bunch, so let me know if anything's unclear? The main point I'm trying to make is that you might want to think about how you want to handle trade-offs between different features - and that depends on your features, study system, and over-arching objectives. This is because simply maximizing everything equally as much as possible might not actually result in a prioritization that helps you achieve your objectives (e.g. long-term persistence of biodiversity) because not all populations/species/features/eco-systems currently have the same extinction risk (e.g. providing 100 ha of habitat for a CR species might improve its long-term persistence by 50%, but providing 100 ha of habitat for LC species might improve its long-term persistence by 1%). 

*of course, this ultimately depends on your objectives - but let's assume that you want to maximise the overall long-term persistence of both species.

**Comment by XavierCLL** [comment]
Hi @jeffreyhanson, again a formidable and detailed answer!!

That makes me rethink my problem very well, because you mention significant things about the importance to preserve features based on their characteristics, prioritization or goals.

However, in my first part of my research, all features have the same importance to preserve, and instead of budget, I have an overall protected area as a goal (> to the current). And you mention a function useful for that `add_min_shortfall_objective`, but for me, it is similar to the  `add_max_utility_objective` but those show different results, I prepare an example:

```R
library(prioritizrdata)

data(salt_pu)

salt_pu_ones <- salt_pu
salt_pu_ones[!is.na(salt_pu_ones[])] <- 1

data(salt_features)

####

p1 <- problem(salt_pu_ones, salt_features) %>%
      add_min_shortfall_objective(10000) %>%
      add_relative_targets(1) %>%
      add_binary_decisions() %>%
      add_default_solver()

s1 <- solve(p1)
plot(s1)

####

p2 <- problem(salt_pu_ones, salt_features) %>%
  add_max_utility_objective(10000) %>%
  add_binary_decisions() %>%
  add_default_solver()

s2 <- solve(p2)

plot(s2)
```
<img src="https://user-images.githubusercontent.com/11801453/129983769-fc781850-d227-4526-98d4-a9b737940722.png" width="400"><img src="https://user-images.githubusercontent.com/11801453/129983772-297046e1-c1eb-4f34-aef9-37b5a9651e05.png" width="400">

<img src="https://user-images.githubusercontent.com/11801453/129984365-ebe1f224-fa4e-49ec-ad69-687782369be9.png" width="350">

They look similar but they are different, What do you think is "better" in this case? is `add_min_shortfall_objective` a better function to have a good balance when all features have the same weight?

Thanks for all your tips and examples, that really help me in the future steps.

Regards,
Xavier

**Comment by XavierCLL** [comment]
Thanks Jeff!, I'm going to close this question, the main question of this issue was answered very well by you. My last question, I guess it is due to the differences in the mathematical implementation and I guess both are ok.

**Comment by jeffreyhanson** [comment]
Hi @XavierCLL,

I'm so sorry - I completely forgot to respond to your previous comment. Rearding your question:

> They look similar but they are different, What do you think is "better" in this case? is add_min_shortfall_objective a better function to have a good balance when all features have the same weight?

I think the better one is that which better acheives the conservation objectives of the planning scenario. So, if the goal is to improve protected area coverage for all features, then the `add_min_shortfall_objective()` is more apropriate. However, if you just want to maximize the sum of the values -- which is just trying to maximize the probability of covering native species, regardless of their habitat affinities; see * below for description of data -- then tthe `add_max_utility_objective()` makes more sense. Following the CARE principles, I would say that `add_min_shortfall_objective()` would be best -- to ensure that the prioritiztion covers a comprehensive range of biotic elements -- but that might just be my personal opinion and not match the conservation objectives of the planning exercise.

> Thanks Jeff!, I'm going to close this question, the main question of this issue was answered very well by you. My last question, I guess it is due to the differences in the mathematical implementation and I guess both are ok.

Great - I'm glad my answers were helpful. Sorry again for dropping the ball. If you do ask another question and don't hear back from me after a week, please send me a reminder :)

----

* Here's a description of the `salt_features` from the vignette: 

> [A] raster stack containing ecological community feature data. Field and remote sensed data were used to calculate the probability of occurrence of five key ecological communities found on Salt Spring island. Each layer in the stack represents a different community type. In order these are; Old Forest, Savannah, Wetland, Shrub, and a layer representing the inverse probability of occurrence of human commensal species. For a given layer, the cell value indicates the composite probability of encountering the suite of bird species most commonly associated with that community type.

**Comment by XavierCLL** [comment]
Hi @jeffreyhanson,

As always, thanks so much for your explanation between that two functions, that help me to decide which one to choose, and `add_min_shortfall_objective` works better and looks very promising for my case.

Thanks again,
Xavier
