### ISSUE TITLE
unusually large difference between solutions when targets are increased by 10%

### ISSUE THREAD

**Issue by ninzyfb** [prioritizr/prioritizr#224]
Hi there,

apologies i have another issue i need help with.

When i run the same problem with the only difference being increasing my relative targets by 10% my solution goes from being extremely fragmented to one large continuous block and i am very confused by why that happens?

My targets vector change from low to medium:
low: t =  0.3 0.4 0.2 0.2 0.2 0.3 0.3 0.4 0.4 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.4 0.2 0.4 0.4 0.2 0.2 0.4 0.4 0.2 0.4 0.3 0.3 0.2 0.2 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.4 0.2 0.3 0.2 0.2 0.2 0.2
medium: t = 0.4 0.5 0.3 0.3 0.3 0.4 0.4 0.5 0.5 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.5 0.3 0.5 0.5 0.3 0.3 0.5 0.5 0.3 0.5 0.4 0.4 0.3 0.3 0.3 0.3 0.5 0.3 0.3 0.3 0.3 0.3 0.3 0.5 0.4 0.5 0.3 0.4 0.3 0.3 0.3 0.3

The two outputs are attached and the code is below:

problem_single = problem(c,f) %>% # costs and features
      add_min_shortfall_objective(budget = 1080) %>%
      add_relative_targets(t) %>%
      add_binary_decisions() %>%
      add_gurobi_solver()

<img width="958" alt="mediumtargets" src="https://user-images.githubusercontent.com/47356207/150737105-3e253e46-6d9b-4f92-9457-51266556b1ed.png">
<img width="987" alt="lowtargets" src="https://user-images.githubusercontent.com/47356207/150737125-96dd21ee-dcb4-425e-844c-62b43974a7d9.png">

**Comment by ricschuster** [comment]
That's an interesting one for sure.

There are a couple of things I can think of here:

1) `add_gurobi_solver`. Try setting the `gap` parameter to 0 to make sure that you reach optimality (the default gap is 0.1 or 10%).

2) `eval_feature_representation_summary`. See how each of the features is represented in the two solutions. Are the (obvious) differences comparing the two scenarios. Here I mean not the increase in feature representation that can be expected by increasing the targets, but do you see patterns in differences between features (i.e. do some features increase a lot, while others don't).

3) number of pu's in solution. Is the budget reached in both scenarios? You can use `eval_n_summary` for this. It looks like the low target scenario has about the name number of pu's in the solution, but I just want to double check.

@jeffreyhanson do you have any other ideas?

**Comment by jeffreyhanson** [comment]
Thanks @ricschuster! Yeah, those are really good ideas/points!

One possible explanation for this could be that all of the targets for all of the features can be met under both scenarios. In situtations where all of the targets can be met for a given budget, the min shortfall objective can sometimes produce prioritizations that include extra planning units that are not needed (i.e. not needed to meet the targets - note that the budget will always be met). If you're interested in understanding how increasing the targets from those specified in the low scenario to those specified in the high scenario will change the prioritization (e.g. in terms of spatial distribution, or overall cost) -- whilst also ensuring that the total budget is <= 180 -- I would suggest using (1) a min set objective and (2) the `add_linear_constraints()` function to ensure that the total cost is <= 180. This combination will produce prioritizations that aim to minimize overall cost as much as possible -- meaning that you won't have extra planning units selected in the solution that aren't needed to meet the targets -- whilst ensuring the total cost budget is met. So, for example, something like this could work:

```
problem_single = problem(c,f) %>% # costs and features
add_min_set_objective() %>%
add_relative_targets(t) %>%
add_linear_constraints(threshold = 180, sense = "<=", data = c) %>%
add_binary_decisions() %>%
add_gurobi_solver()
```

PS. Just in case you weren't aware, `c()` is a function the base R package. So assigning your data to the variable `c` can sometimes cause problems. E.g., if you've ever heard that you shouldn't call your data `data`, then this is based on the same premise.

**Comment by ninzyfb** [comment]
Hi Richard and Jeff,

Thank you for your reply. Yes i am still quite puzzled by this one. To answer your questions:
1. i changed the gap to 0 but it did not affect the solution
2. i had a look at the summaries and yes there is quite a range by the amount at which some features increase compared to other. The differences in relative held ranges from -7 to +100 from the low to higher targets.
3. both solutions pick 1080 pus so they have the exact same amount.
4. i tried your technique Jeff but then when i set the higher targets it tells me that:
"Error in .local(a, b = b, ...) : no solution found (e.g. due to problem infeasibility or time limits)" this is actually an issue i also posted yesterday.

i tried using add_min_largest_shortfall_objective with a gap of 0 but the same thing occurs. could the fact that my distribution maps are rasters with continuous values rather than binary be a problem? also when i change from add_min_largest_shortfall_objective(budget = 1080) to add_min_set_objective() with a linear constraint of 1080 the solutions for the low targets are different (see below) and i don't see why that should be the case? the add_min_largest_shortfall one is far more fragmented than the min_set_objective + linear constraint one.

low target with add_min_set_objective() and linear constraint:
<img width="1011" alt="Screenshot 2022-01-25 at 08 13 14" src="https://user-images.githubusercontent.com/47356207/150921237-274a8af4-e772-40a5-acb4-c2a05f5cb351.png">

**Comment by ricschuster** [comment]
Thanks @ninzyfb 

> i had a look at the summaries and yes there is quite a range by the amount at which some features increase compared to other. The differences in relative held ranges from -7 to +100 from the low to higher targets.

You could try balancing things out with the `add_feature_weights` function, but I'm not entirely sure if that would help.

I don't think the continuous rasters should be an issue, but its a possibility.

Would you be willing to share your data, so we could investigate this further?

**Comment by ninzyfb** [comment]
Hi Richard,

Ok thank you, absolutely i don't mind that at all. Here is a link to a folder which has the planning units (template_10km.tif) and the rasters that i've been using as biodiversity features. I've also added a simplified script which should have enough to recreate the problem.

Link: https://www.dropbox.com/sh/po4d25xy1vof8sq/AACKLnAtpXNe6gCcxAMaDE44a?dl=0 

Thanks in advance for your help!

**Comment by jeffreyhanson** [comment]
Thanks for sharing the data - that's really helpful!

If we generate (1) a min set prioritization with the low targets (`min set low`) and (2) a min shortfall prioritization with the low targets (`min shortfall low`) and then calculate the total amount of selected planning units: we can see that the the first prioritization contains 912 planning units and the second contains 1080 planning units. This tells us that the min shortfall prioritization with the low targets (`min shortfall low`) contains a lot of extra planning units that aren't doing anything (i.e. they aren't needed to meet the targets). We can further verify this by looking at the target coverage statistics, many species under the min shortfall prioritization with the low targets (`min shortfall low`) have coverage much higher than the targets. So, why do we see this? This is because, in the absence of additional information on spend the remainder of the budget (1080 - 912 = 168), the optimizer has selected extra planning that appear very scattered. 

In other words, it's like giving someone a shopping list for groceries that has $30 worth of items on it, giving them $100 to buy groceries, and then telling them we don't care what they should do with the over $70. The person might chose to only (1) spend the $30, (2) spend some of the $100 by buying the shopping list items and also some extra items, or (3) spend all of the $100. on the shopping list items and extra items. Since we didn't tell them how to spend the remaining $70, there's a lot of possible different shopping items the person might bring back. They might chose to spend the extra $70 on some things that make sense to us -- but that's extremely unlikely, because we didn't give them any guidance. Does that make sense?

So how can we address this? This depends on how important those targets are. The easy fix is simply increasing the targets for all scenarios such that at least 1080 planning units are needed to meet the targets for all features. This way you don't have to worry about changing the problem formulation (e.g. objective, constraints, or penalties) to generate meaningful solutions (i.e. solutions wherein all planning units help contribute to conservation goals). However, if the targets are chosen for specific reasons, we need to think about what the prioritization should do if less than 1080 planning units are needed to meet the targets. For example, here's some ideas:

1. You could add additional features (e.g. species, habitat types) to help inform the prioritization process. By having more features, the prioritization generated with low targets will have more information on where to allocate conservation effort. This means that you can keep using a min shortfall objective for prioritizations and keep the same targets for the species in your current prioritization. Personally, I would recommend this approach -- assuming there is a specific reason why 1080 planning units is chosen as a threshold -- because this issue suggests that you might not have enough data to identify 1080 areas that are actually a priority for conservation.

2. If the prioritization should only select the minimum number of planning units needed to meet the targets -- when less than 1080 planning units are needed to meet the targets -- then you'll need to use a min set objective for situtations when the less than 1080 planning units are needed. 

3. You might decide that spatial fragmentation is important, so you can use the min shortfall objective for all prioritizations -- regardless of whether targets are low or high -- and add boundary penalties to specify that any budget surplus should focus on reducing spatial fragmentation. 

4. You could add an additional feature with a really high target (e.g. 100%) and a really low weight -- along with the current min shortfall objective and low/medium/high targets -- that broadly describes conservation value (e.g. inverse anthropogenic disturance, ecosystem intactness) so that any surplus planning units are sited in places that help meet the conservation goals. 

What do you think? Please let me know if you have any follow up questions?

--------------

In case thisis helpful, here's the code and maps I generated to help understand what's going on.

```
# ---------------------------------------------------------------------------------
######### Shark and ray species conservation planning using prioritizr - Parent script
#AUTHOR: Nina Faure Beaulieu (2021)
#PROJECT: the shark and ray conservation plan developed under the WILDOCEANS 3-year shark and ray project in South Africa
#!Run each script one at a time as running the whole at once seems to cause some bugs
#the output line describes what each script produces
# ---------------------------------------------------------------------------------

####
#THIS SCRIPT: This is the parent script which calls all of the other scripts
####

# ---------------------------------
# PACKAGES
# ---------------------------------
library(dplyr)
library(tidyr)
library(prioritizr)
library(gurobi)
library(stringr)
library(rasterVis)
library(viridis)
library(rgeos)
library(raster)
library(scales)
library(readxl)
library(fasterize)
library(sdmvspecies)
library(RColorBrewer)

# ---------------------------------
# DEFINE WORKING DIRECTORY
# ---------------------------------

# all the subscripts are in the scripts folder
# all the data is in the planning folder
# make sure you choose the correct path and set the directory to the overall WILDOCEANS folder so you can find both
# path =??? # mac path
# setwd(paste0(path,"???"))

# ---------------------------------
# PLANNING UNIT (pu)
# output: planning unit grid (EEZ with uniform value of 1)
# ---------------------------------
# grid cell value = cost of grid cell
# this is the basic planning unit, every 5km2 grid cell has a value of 1
pu = raster(
  list.files(
    pattern = "template_10km.tif", full.names = TRUE, recursive = TRUE
  )
)

# ---------------------------------
# CONSERVATION FEATURES
# ---------------------------------
feature_stack_aseasonal = stack(
  list.files(
    pattern = "_Aseasonal_res10_ensemblemean.tif", full.names = TRUE,
    recursive = TRUE
  )
)

# ---------------------------------
# CONSERVATION TARGETS
# output: this adds targets to featurenames dataframe
# ---------------------------------
targets = read.csv(list.files(pattern = "targets.csv", recursive = TRUE))

# ---------------------------------
# CONSERVATION PROBLEM & SOLVING
# output: prioritizr problem object
# ---------------------------------
options(scipen = 100) # turns of scientific numbering

# min set prioritization with low targets
problem_low1 = problem(pu, feature_stack_aseasonal) %>%
  add_min_set_objective() %>%
  add_relative_targets(targets$low) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()

solution_low1 = solve(problem_low1)

# min set prioritization with high targets
problem_high1 = problem(pu, feature_stack_aseasonal) %>%
  add_min_set_objective() %>%
  add_relative_targets(targets$high) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()

solution_high1 = solve(problem_high1)

# min shortfall prioritization with low targets
problem_low2 = problem(pu, feature_stack_aseasonal) %>%
  add_min_shortfall_objective(1080) %>%
  add_relative_targets(targets$low) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()

solution_low2 = solve(problem_low2)

# min shortfall prioritization with high targets
problem_high2 = problem(pu, feature_stack_aseasonal) %>%
  add_min_shortfall_objective(1080) %>%
  add_relative_targets(targets$high) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()

solution_high2 = solve(problem_high2)

# ---------------------------------
# CALCULATE SUMMARY STATISTICS
# ---------------------------------

# calculate target coverage
cov_low1 = eval_target_coverage_summary(problem_low1, solution_low1)
cov_high1 = eval_target_coverage_summary(problem_high1, solution_high1)
cov_low2 = eval_target_coverage_summary(problem_low2, solution_low2)
cov_high2 = eval_target_coverage_summary(problem_high2, solution_high2)

# calculate number selected
n_low1 = eval_n_summary(problem_low1, solution_low1)
n_high1 = eval_n_summary(problem_high1, solution_high1)
n_low2 = eval_n_summary(problem_low2, solution_low2)
n_high2 = eval_n_summary(problem_high2, solution_high2)

# ---------------------------------
# VISUALIZE RESULTS
# ---------------------------------

# plot results
plot(
  stack(solution_low1, solution_high1, solution_low2, solution_high2),
  main = c(
    paste0("min set low (n = ", n_low1[[2]], ")"),
    paste0("min set high (n = ", n_high1[[2]], ")"),
    paste0("min shortfall low (n = ", n_low2[[2]], ")"),
    paste0("min shortfall high (n = ", n_high2[[2]], ")"),
      "min set high", "min shortfall low", "min shortfall high"
  )
)
```

![image](https://user-images.githubusercontent.com/3610005/151087973-31327382-dd15-4989-9961-790a8be2a693.png)

**Comment by ninzyfb** [comment]
Hi Jeffrey, thank you so much! this makes complete sense. I was being very conservative with my targets but i think i can start giving the package more of a headache to solve my problems by increasing the targets a little.

I realised through running different scenarios today that i misinterpreted how add_min_set_objective() worked. I thought that if say i set a relative target of 30% for all features even though that was impossible within the given constraint, the solver would still solve it but just not fulfilling all the targets. I now realise that that is what the other objectives are for: to specify how you want to "fail" your targets given a difficult problem to solve. My issue with this is that i do not have a budget. I want to minimise the cost within a total area budget of 1080. This is fine when i have a uniform cost layer as my budget os 1080 and i can use the min_shortfall_objective(). But if i add my cost layer with fishing pressure, 1080 will no longer represents the same area restriction. So basically what i am trying to do is  tell the solver to:
1. try and fit the targets given a cost layer and a maximum area budget of 1080 and if it cannot meet the targets within this budget just do it by minimising the shortfall. 
But i guess my solution is to play around with different budgets.

Thank you again for all your help!

**Comment by jeffreyhanson** [comment]
No worries! 

Yeah, that's exactly right. If you use the min set objective then the targets are treated as "hard constraints" - meaning they must always be met. If they cannot be met (e.g. because the targets are too high, you have locked out planning units needed to meet the targets, or added extra linear constraints that prevent the targets from being met), then you'll get an error message about infeasibility.

Yeah, if the maximum area budget of 1080 is really important given the goals of the conservation planning exercise, then I would suggest not changing that. This is because even though you might get a solution/prioritization by using a different threshold, it won't actually be useful for informing conservation activities. Since you want to (1) explore a broad range of different targets, (2) impose a 1080 maximum area constraint/budget, and (3) account for fishing pressure: I suggest handling the fishing pressure layer in a slightly different way. 


For example, one option is to use the `add_linear_constraints()` function to set a `<=` constraint to ensure that the total amount of fishing pressure scores do not exceed a certain threshold. For example, we could add a constraint to ensure that the prioritzation must only select planning units with fishing pressure scores that sum to a total of less than 20% of the total fishing pressure scores. You could try a range of different percentage-based thresholds to explore trade-offs between feature representation and thresholds for the fishing pressure constraint.

```
fp_threshold = raster::cellStats(fishing_pressure, "sum") * 0.2
problem = problem(pu, feature_stack_aseasonal) %>%
  add_min_shortfall_objective(1080) %>%
  add_relative_targets(targets$low) %>%
  add_linear_constraints(threshold = fp_threshold, sense = "<=", data = fishing_pressure) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()
```

Another option would be to create a binary layer based on the fishing pressure scores (e.g. based on a quantile threshold, or your own domina knowledge) and use these to lock out planning units with high fishing pressure (this is sometimes done in terrestrial systems with human footprint index data to ensure that highly modified areas are not selected). For example, you could create a binary layer based on the top 5th percentile of pressure scores:

```
fp_threshold = raster::quantile(fishing_pressure, probs = (1 - 0.05), na.rm = TRUE, names = FALSE)
fp_binary = raster::round(fishing_pressure >= fp_threshold)
problem = problem(pu, feature_stack_aseasonal) %>%
  add_min_shortfall_objective(1080) %>%
  add_relative_targets(targets$low) %>%
  add_locked_out_constraints(fp_binary) %>%
  add_binary_decisions() %>%
  add_gurobi_solver()
```

A further option could be to create a multi-zone problem with zones for (1) biodiversity protection, and (2) fishing activities. You could set targets for the biodiversity protection zone using the feature data and the 1080 area constraint. Additionally, you could set targets for the fishing activities based on the feature data (e.g. if you want to ensure that fishing activities have access to a certain amount of sea occupied by certain species). To account for existing fishing activities, you could try locking in planning units to the fishing zone if existing fishing pressure if over a certain threshold. That said, this approach is more complicated and is only reallt worth the extra hassle if you explicitly need to account for multiple constraints/variables/factors/criteria for fishing activities.

**Comment by ninzyfb** [comment]
Hi Jeffrey, thank you as always for such an in depth explanation. That makes complete sense and really helps solve my problem. I really like the idea of creating a binary layer and would not have come up with that had you not suggested it. Thank you for developing such a great package! I will now close the issue as i have no more questions.

**Comment by jeffreyhanson** [comment]
No worries - I'm happy to help! Thank you!
