### ISSUE TITLE
Settings targets for including whole feature patches

### ISSUE THREAD

**Issue by jflowernet** [prioritizr/prioritizr#226]
Hi Jeff and all,

I've got a feature that has many patches scattered across the planning area; ocean planning and the feature is seamounts if that helps. The feature is all binary, i.e. present or not present. I want to set a target that will prioritise whole patches, rather than parts of the patches, so the solution includes whole seamounts rather than potentially small areas of many seamounts. I'm guessing this is tricky/ not possible because the target might not be met exactly by an exact number of whole features, e.g. if the target is 50% and that represents the area of 2.5 features. I would also be happy to set a target for number of these patches (seamounts) that could be included.

Any thoughts how to approach this?

Many thanks!

**Comment by jeffreyhanson** [comment]
Hi,

Yeah - that's a tricky question! Prioritizr doesn't really have any built-in functionality for this - but I have an idea that might work. 

I assume your planning unit data are currently based on a grid? Could you add additional planning units to the grid so that correspond to the spatial boundaries of the sea mounts (i.e. each sea mount is a different planning unit)? Thus the full planning unit dataset includes a combination of grid cell-level plann units and sea mount-level planning units, wherein there are spatial overlaps in some of the planning units (because some grid cells partially overlap with the sea mounts). Next, could you update the feature data (or rij data) so that (1) the sea mount-level planning units have 1s (presences) for sea mounts, (2) grid cell-level planning units only have 0s (absences) for sea mounts, and (3) the sea mount-level planning units contain the feature values for non-sea mount features (e.g. fish species? sea grass? etc) that correspond to the sum of the grid cell-level planning units that overlap with them.

With this setup, the optimization process will involve selecting a combination of grid cell-level and sea mount-level planning units. In order to meet the sea mount targets, the prioritization will need to select some sea mount-level planning units (because these planning units are the only ones with presences for the sea mounts). In order to meet non-sea mount targets (e.g. fish species), the prioritization can select (1) sea mount-level planning units, (2) grid cell-level planning units, or (3) a combination of both sea mount-level planning units and grid-cell level planning units. By including sea mount-level and grid cell-level planning units in spatially overlapping areas, this means that the prioritization can chose between (i) selecting an entire sea mount to get the sea mount and all the other biodiversity found within the sea mount, or (2) selecting a grid cell within a sea mount to only get the biodiversity found within the grid cell.

Hopefully, the optimization process won't select planning units that spatially overlap (i.e. grid cell-level and sea mount-level planning units that overlap with each other). If this happens you could add a series of linear constraints -- one constraint for each combination of sea mount planning unit and the grid cell-level planning units that overlap with it -- to specify that the solution must not select a sea mount-level planning unit and also any of the grid cell planning units that overlap with it.

Does that help? Let me know if you have any follow up questions?

**Comment by jflowernet** [comment]
Thanks so much for thinking this through so thoroughly Jeff!

I'm trying to wrap my head around it, so excuse the follow up questions.

1. I'm used to using raster features as inputs, so I think you are then suggesting masking each input feature, by each of the new planning unit levels? So e.g. if there are 3 seamounts, and therefore 3 seamount level planning units, each 'fish' feature would be split into 4 new rasters: 1 grid cell-level, and 3 seamount level rasters?
2. I don't think I'm understanding correctly how whole seamounts will be targeted for inclusion in a solution. If each seamount is now a separate feature, how would targets be set for a total number of them to be included in the solution?

I'm including this reprex to check I'm understanding the grid cell-level and seamount-level planning units correctly:

``` r
library(prioritizr)
#> Loading required package: raster
#> Loading required package: sp
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1; sf_use_s2() is TRUE
#> Loading required package: proto

#create a simple planning grid
pu_raster <- raster(nrows = 20, ncols = 20, xmn = 0, xmx = 20, ymn = 0, ymx = 20, vals = 0)

#create some areas - 3 points that are buffered
seamount_areas <- st_multipoint(rbind(c(2, 2), c(8, 17), c(17, 5))) %>% 
  st_buffer(2) %>% 
  as("Spatial")

#rasterize the seamounts
seamount_raster <- rasterize(seamount_areas, pu_raster, field = 1)

plot(seamount_raster)
```

![](https://i.imgur.com/4rAK70O.png)

``` r
#these would be the grid-cell level and seamount-level planning units then? With each seamount a separate unit
par(mfrow = c(1,2))

plot(rasterToPolygons(pu_raster))

plot(rasterToPolygons(seamount_raster, dissolve = TRUE))
#> Loading required namespace: rgeos
```

![](https://i.imgur.com/kKSXXmi.png)

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jeffreyhanson** [comment]
Thanks for putting togeather this reprex - that's really helpful!

Sorry, I didn't do a good job of explaining it - we basically have an extra planning unit for each seamount (not a seperate feature for each seamount). I've had a go at trying to implement this and I think I've got it working (see below). I've added comments, but let me know if any part of the code doesn't make sense?

```
# load packages
library(prioritizr)
library(terra)
library(tibble)
library(dplyr)

# set seed for reproducibility
set.seed(500)

# define number of fish spp
n_fish <- 4

# create a simple planning grid (assuming cost of each planning unit is equal)
pu_raster <- raster(
  nrows = 20, ncols = 20,
  xmn = 0, xmx = 20, ymn = 0, ymx = 20, vals = 1
)

# create data for fish species
fish_stack <- raster::stack(lapply(seq_len(n_fish), function(x) {
  setValues(pu_raster, round(runif(ncell(pu_raster)) > 0.5))
})) %>% setNames(paste0("fish_", seq_len(n_fish)))

# create sea mount data
seamount_raster <-
  st_multipoint(rbind(c(2, 2), c(8, 17), c(17, 5))) %>%
  st_buffer(2) %>%
  as("Spatial") %>%
  rasterize(pu_raster, field = 1)

# create a separate layer for each sea mount
seamount_stack <-
  seamount_raster %>%
  as("SpatRaster") %>%
  terra::patches() %>%
  as("Raster") %>%
  {lapply(sort(unique(values(.))), function(i) {
    raster::Which(. == i)
  })} %>%
  raster::stack() %>%
  setNames(paste0("seamount_", seq_len(3)))

# create grid-cell level planning unit data
## initialize data
pu_grid_data <-
  ### add in indices for planning units in raster to be organized
  tibble(id = as.list(seq_len(ncell(pu_raster)))) %>%
  ### add in cost data
  mutate(cost = raster::as.data.frame(pu_raster)[[1]]) %>%
  ### add in fish data
  bind_cols(as_tibble(raster::as.data.frame(fish_stack))) %>%
  ### add in seamount data
  mutate(seamount = 0)

# create sea mount-level planning unit data
pu_sm_data <- lapply(names(seamount_stack), function(i) {
  ## initialize data for planning unit that corresponds to i'th sea mount
  curr_sm_pu <-
    ## add in indices for planning units in raster to be organized
    tibble(
      id = list(raster::Which(seamount_stack[[i]] > 0.5, cells = TRUE))
    ) %>%
    ## add in cost data
    mutate(
      cost = raster::cellStats(
        pu_raster * seamount_stack[[i]], "sum", na.rm = TRUE
      )[[1]]
    ) %>%
    ## calculate total amount of each non-sea mount feature in i'th sea mount pu
    bind_cols(
      raster::as.data.frame(fish_stack * seamount_stack[[i]]) %>%
      setNames(names(fish_stack)) %>%
      dplyr::summarize_all(sum)
    ) %>%
    ## add data for i'th seamount
    mutate(
      seamount = unname(
        raster::cellStats(seamount_stack[[i]], "sum", na.rm = TRUE)
      )
    )
  ## return data
  curr_sm_pu
}) %>% do.call(what = bind_rows) %>% as_tibble()

# merge sea mount-level data and grid-cell level data togeather
pu_data <- bind_rows(pu_grid_data, pu_sm_data)

# calculate feature data
feature_data <-
  ## initialize data with the name and total amount of each feature
  ## note we use seamount_raster here because we want to set targets
  ## based on overall distribution of seamounts (not each one separately)
  raster::stack(fish_stack, setNames(seamount_raster, "seamount")) %>%
  raster::cellStats(sum, na.rm = TRUE) %>%
  {tibble(id = seq_along(.), name = names(.), total = unname(.))} %>%
  ## set targets, let's use 20% as an example
  mutate(rel_target = 0.2) %>%
  ## now compute the targets as absolute values
  ## (this is needed because we have spatial overlaps in the planning unit
  ## data, so that if we gave prioritizr relative targets then it wouldn't
  ## calculate the percentages correctly)
  mutate(abs_target = rel_target * total)

# create a conservation planning problem
prob <-
  problem(x = pu_data, features = feature_data$name, cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_absolute_targets(feature_data$abs_target) %>%
  add_binary_decisions() %>%
  add_default_solver(gap = 0)

# solve problem
raw_sol <- solve(prob)

# since the solution contains a combination of grid cell-level and
# seamount-level planning units, we need to do some post-processing
# to identify which "real" planning units (i.e. raster pixels) were selected
pu_ids <- unique(unlist(pu_data$id[which(raw_sol$solution_1 > 0.5)]))

# we can now use these values to create a raster
sol <- pu_raster * 0
sol[pu_ids] <- 1
names(sol) <- "solution"

# plot solution
plot(sol)
```

![sol](https://user-images.githubusercontent.com/3610005/154410417-b16f729d-190a-403e-a104-26853b987813.png)

**Comment by jflowernet** [comment]
This is amazing Jeff, thank you so much. I will go through in detail tomorrow, and follow up. Thanks!

**Comment by jflowernet** [comment]
Thanks again Jeff, this is a pretty amazing solution to this problem that I would never have figured out! 

I have never used data frames as problem inputs, but your example made it clear how this works and how to specify all the parameters. I would never have known you could use lists as the planning unit id's; a very useful trick to know!

I worked through your example step by step to check I understood everything and have tried upping the % of seamounts and it seemed to work well, picking up whole seamounts as necessary. I also checked feature representation and all targets are being met. 

Next step is to try this out in the real world zoning we are working on! Thanks again Jeff!!

**Comment by jeffreyhanson** [comment]
No worries - glad to hear it works! 

Yeah, the data frame input format is pretty flexible and performant (e.g., runs much faster than working with raster data). The main reason the documentation doesn't mention it much is because the extra data wrangling required to translate data to and from spatial formats can be a bit confusing.

Yeah, I don't know if prioritizr properly supports list-columns in the planning unit data - I haven't tested it fully, so that's why the code uses `pu_data$id` instead of `raw_sol$id` - but list-columns in general can be very handy. AFAIK tibble and dplyr supports them fully, but IIRC you might find issues with base R data frames and rbind.

Awesome! Let me know if you run into any further issues. In particular, you might need to adapt the code so that it handles missing (NA) values in the raster data. If that's sorted out your questions for now, would you mind if we closed this issue?

**Comment by jflowernet** [comment]
Good to know about the performance boost using data frames. That could also be useful. 

Absolutely, happy to close it for now. And thanks again for all your help!
