### ISSUE TITLE
Issue with boundary parameter estimation using Cohon's method

### ISSUE THREAD

**Issue by SuJie26** [prioritizr/prioritizr#228]
Hi

I am calculating the boundary parameter using Cohon's method. I have six scenarios with different levels of restoration areas (i.e. 500 ha, 750 ha, 1000 ha, 1500 ha, 2000 ha, and 3000 ha). Everything goes well with areas from 500 ha to 2000 ha. However, when I run the model based on zero cost with an area of 3000 ha, it generates the error of "Error in .local(a, b = b, ...) : 
  no solution found (e.g. due to problem infeasibility or time limits)"

This error only comes out in the zero-cost model, so I believe there is nothing wrong with the setting of targets and constraints. 

Can you please let me know what might cause the error and how can I fix it? 

Many thanks in advance.
Jie

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for reaching out about this! I'm sorry, I think I need a bit more information to help understand why you're seeing this error. Could you pease post a small reproducible example with the code and data so I can see what's going on? If the data or code can't be shared publicly, could you please email it to me (my email address is on my GitHub profile page).

**Comment by SuJie26** [comment]
Thank you for your prompt reply.

I have sent the data and code to you by email. Here I also attach my code below if anyone may find it helpful with the same issue.

======================================================
##Load data
#Feature data by each species
files=c("/Features_species/ac.tif",
        "/Features_species/ai.tif",
        "/Features_species/am.tif",
        "/Features_species/bg.tif",
        "/Features_species/ko.tif",
        "/Features_species/rs.tif",
        "/Features_species/sa.tif") 
mix=stack(files)
my_rules <- c(1, 6, 0,  6, 9, 1)
reclmat <- matrix(my_rules, ncol=3, byrow=TRUE)
mix_binary<-  reclassify(mix,reclmat)
ss <- raster(resolution=c(50,50), crs=proj4string(mix_binary), ext=extent(mix_binary)) 
mix_binary <- resample(mix_binary, ss)
print(mix_binary)

#cost raster
cost <- raster("/Cost data/annual cost2.tif") 
ss <- raster(resolution=c(50,50), crs=proj4string(cost), ext=extent(cost)) 
cost <- resample(cost, ss)
fun <- function(x) { x * 2500 }
cost <- calc(cost, fun)
print(cost)

fun <- function(x) { x * 0 }
cost_0 <- calc(cost, fun)
area <- cost
values(area) <- 2500
print(area)
tas_bd <- boundary_matrix(cost)

##This is the model that caused errors##
p1 <- problem(cost_0, mix_binary)%>%
  add_min_set_objective()%>%
  add_boundary_penalties(penalty = 1, data = tas_bd)%>%
  add_relative_targets(0.65)%>%
  add_linear_constraints(threshold =30000000, sense = "=", data = area)%>%
  add_neighbor_constraints(2)%>%
  add_binary_decisions()%>%
  add_gurobi_solver(gap = 0)  ##For saving time, I suggest using the default gap for testing.

s1 <- solve(p1)

**Comment by jeffreyhanson** [comment]
Thanks for providing all these details - that's really helpful! 

The infeasible error occurs when there are constraints (either in isolation, or in combination with other constraints) that cannot be met. For example, this can occur with when setting targets so high that they cannot be met even if all planning units are selected (e.g. using specifying targets using absolute values), or locking out planning units that are needed to meet certain targets (e.g. setting 10% targets for all features and locking out planning units that contain features which only occur in those locked out planning units).

To help track down the issue, I tried simplifying the problem to identify the specific constraints that were causing the issue (i.e. removing a constraint, trying to solve it, and then adding back in if it worked). It would seem that having a combination of 65% targets and 30000000 for the linear constraints is causing the issue. This would suggest that maybe it is impossible to have a solution that both secures 65% of each feature and has exactly 30000000 `area` values. To verify this, we can build a min set problem with the `area` data as cost data, and solve it to optimality to identify the minimum possible `area` vaue given these targets:

```

# build problem
p1 <- problem(area, mix_binary) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.65) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0)

# solve problem
s1 <- solve(p1)

# print minimum threshold value
eval_cost_summary(p1, s1)[[2]]
#> 33305000
```

So we can see that the threshold parameter must be at least 33305000 -- and this number is larger than 30000000 -- so it explains why we're seeing errors about infeasibility. Indeed, if we set the threshold number as 40000000, we can now get a solution. Note that I suggest using `<=` when setting the constraint so that the solution do not contain more than 40000000 selected units, because using `=` specifies that the solution should have exactly 40000000 selected units (and this might cause infeasibility issues with the neighbor constraints).

```
# build problem
p2 <- problem(cost_0, mix_binary) %>%
  add_min_set_objective() %>%
  add_boundary_penalties(penalty = 1, data = tas_bd)%>%
  add_relative_targets(0.65) %>%
  add_linear_constraints(threshold = 40000000, sense = "<=", data = area) %>%
  add_neighbor_constraints(2) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.3)

# solve problem
p2 <- solve(p2)
```

Also, in a previous message, you mentioned that solving the problem with smaller threshold values (e.g. 500, 750) worked succesfully. When I try this on my computer, I receive an error about infeasbility. Is it possible that maybe there was different about the cost or feature data when you tried generating solutions with the smaller threshold values? Specifically, I tried the code below:

```
# try lower threshold
p3 <- problem(cost_0, mix_binary) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.65) %>%
  add_linear_constraints(threshold = 500, sense = "<=", data = area) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0)

# solve prolbem
s3 <- solve(p3)
#> throws infeasbility error
```

I hope that helps? Let me know if anything I've written isn't clear, or if you have any follow up questions?

**Comment by SuJie26** [comment]
Thank you so much for your prompt reply. That is very clear and helpful.

I am sorry that I might not explain this clearly in the previous message. For the smaller threshold values, I used smaller relative targets. For example, 500 ha with 10% of relative target, 750 ha with 15% of relative target, and they all work successfully. 

For the 3000 ha with 65%  of relative target, actually, it works well when I used the actual cost instead of the zero cost. Is it the same reason for the error that you find when I used the zero cost? If so, in this case, how can I calculate the boundary parameter through Cohon's method?

Many thanks again.

**Comment by jeffreyhanson** [comment]
Oh - I'm sorry - I think I'm still misunderstanding something. When I try generating a solution with a 30000000 threshold value and a 65% target, I recieve infeasibility issues when using the `cost` or `cost_0` data as cost values. Is this the same behavior you're seeing?

```
# define problem
p1 <- problem(cost, mix_binary)%>%
  add_min_set_objective() %>%
  add_relative_targets(0.65) %>%
  add_linear_constraints(threshold = 30000000, sense = "<=", data = area)%>%
  add_binary_decisions() %>%
  add_gurobi_solver(first_feasible = FALSE, gap = 0)

# solve problem
s1 <- solve(p1)
#> infeasibility error

# define problem
p2 <- problem(cost_0, mix_binary)%>%
  add_min_set_objective() %>%
  add_relative_targets(0.65) %>%
  add_linear_constraints(threshold = 30000000, sense = "<=", data = area)%>%
  add_binary_decisions() %>%
  add_gurobi_solver(first_feasible = FALSE, gap = 0)

# solve problem
s2 <- solve(p2)
#> infeasibility error
```

**Comment by SuJie26** [comment]
Oh sorry, I try them again, yes, they both come out the infeasibility errors. I am sorry for my mistakes.

Now I understand the problem, and your suggestion is very helpful. Thank you a lot.

Can I ask one more question, if I insist on the total area constraint equal to 30000000 ha, how can I know the threshold/maximum of relative target that can work?

Many thanks again.

**Comment by jeffreyhanson** [comment]
No worries at all - I'm happy to help!

Sure - I would suggest using the `add_min_largest_shortfall()` objective for this task. This objective function tries to maximize coverage of the worst represented feature in the solution. Here's one way of doing this:

```
# prepare area data
## mask area by cost so that NA values in same pixels
area_mask <- mask(area, cost)

# define problem
p1 <- problem(area_mask, mix_binary) %>%
  add_min_largest_shortfall_objective(budget = 30000000) %>%
  add_relative_targets(1.0) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0)

# solve problem
s1 <- solve(p1)

# compute target coverage
r1 <- eval_target_coverage_summary(p1, s1)

# find largest possible relative target
min(r1$relative_held)
#> 0.5900731

# verify that we can generate a min set solution with this target
s2 <- problem(cost, mix_binary) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.59) %>%
  add_linear_constraints(threshold = 30000000, sense = "<=", data = area) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0) %>%
  solve()
```

Also, when I was constructing this problem, I realized that there were some inconsistencies between the cost and the feature data (this is why I included the data prep step at the start of the code). I would suggest updating the feature and cost data so that they have NA values in exactly the same pixels/grid cells. This is important because prioritizr defines planning units based on which pixels have non-NA cells/values in the cost data. So, if you have a pixel that has NA in the cost data and a finite value greater than 0 (e.g. 0.1, 1, 100 , etc) in the feature data, then this means that it is impossible for the solution to meet a 100% target for the features (because even if the solution selected all planning units, it still would not be able to select grid cells/pixels with NA cost values).

So, one way to standardize the data would be like this:

```
# build mask, with NA values in places missing data across any layers
pu_mask <- sum(mix_binary) + cost

# mask cost data
cost <- mask(cost, pu_mask)

# mask feature data
mix_binary <- mask(mix_binary, mix_binary)

# create zero cost layer (NA values in same pixels as pu_mask)
cost_0 <- cost * 0

# create constant area layer (NA values in same pixels as pu_mask)
area <- (cost * 0) + 2500
```

How does that sound?

**Comment by SuJie26** [comment]
It sounds wonderful! Much appreciated!!!
Thank you so much for your patience and for helping me out with all these issues that I even did not notice.

All is good with my work now, I am happy to close it.

Many many thanks again!!!
