### ISSUE TITLE
Asymmetrical connectivity penalties

### ISSUE THREAD

**Issue by eleanorstewart17** [prioritizr/prioritizr#230]
Hi there, 

I'm trying to incorporate asymmetrical connectivity into my problem and from what I understand, to do this I need to include the reverse of every planning unit pair in the connectivity data file. Is this the case even when the value is 0? I know traditionally we wouldn't include a planning unit pair if the boundary/connectivity value is 0. I have found when I do this the runtime increases exponentially and I have yet to get an output using this method so I'm wondering if I may be missing something?

Additionally - where does the result of the `eval_connectivity_summary()` function come from? Is it sum of the connectivity values of all selected planning unit pairs from the original data included in the `add_connectivity_penalties()` function?

Thanks a lot in advance!

**Comment by jeffreyhanson** [comment]
Hi,

Nah, you only need to specify connectivity strength values for pairs of planning units where the connectivity value is not zero. For example, if you were specifying the connectivity data using the data.frame format option, then this means that you wouldn't need to include rows for pairs of planning units that have 0 connectivity. If you were specifying connectivity using the sparse matrix option, then you would assign the a value of 0 to cells that corresond to planning units with 0 connectivity between them -- but because this is a sparse matrix format then the zeros won't be used in the optimization problem. Does that answer your question? I'm not exactly sure what you mean by "reverse of every planning unit pair", I'm think you mean "combination of every planning unit pair" - but please correct me if I'm missing something?

Yeah, the `eval_connectivity_summary()` calculates the total sum of connectivity values between selected planning units. Basically, it looks at all the selected planning units in the solution, then it extracts connectivity values for pairs of planning units that are both selected in the solution, and then sums this subset of connectivity values togeather. 

Does that help? Please let me know if anything I've written isn't clear?

**Comment by eleanorstewart17** [comment]
Thanks a lot! I'm still a bit confused - how do I represent an asymmetrical connection between planning units 1 and 2 if the connection in one direction is 0.6 and in the other direction is 0? Should I specify a very low value instead of 0? 

> Yeah, the eval_connectivity_summary() calculates the total sum of connectivity values between selected planning units. Basically, it looks at all the selected planning units in the solution, then it extracts connectivity values for pairs of planning units that are both selected in the solution, and then sums this subset of connectivity values togeather.

Great, thank you for clearing this up!

**Comment by jeffreyhanson** [comment]
Yeah, so if we had 10 planning units in total and a connectivity matrix called `cm` then we would do something like this:

```
# assign values
cm[1, 2] <- 0.6
cm[2, 1] <- 0
```

**Comment by jeffreyhanson** [comment]
Does that help? Let me know if you want a more complete example (e.g. that includes creating the matrix to begin with)?

**Comment by eleanorstewart17** [comment]
Thanks very much, yes, I think that does clear it up for me!

> Nah, you only need to specify connectivity strength values for pairs of planning units where the connectivity value is not zero.

So just to clarify - this comment only applies when the connection is symmetrical? If I want to show an asymmetrical connection where there is no connectivity in one direction I would need to include a value of 0 in the connectivity matrix data (as you showed above) and this would be recognised as asymmetrical and used in the optimisation problem? 

Thanks!!

**Comment by jeffreyhanson** [comment]
Sorry, that comment wasn't very clear. I should have said that you only need to specify non-zero values, if the matrix values are initialized at zero when you create the matrix. This is the same for symetric and asyemtric data. Yeah, you can achieve this behavior by supplying a zero value for one combination (e.g. `m[1,2]`), and a non-zero value for another combination (`m[2,1]`).

**Comment by eleanorstewart17** [comment]
Okay great, that's really cleared things up for me - thanks again!!

**Comment by jeffreyhanson** [comment]
No worries! Since you don't have any further questions at the moment, I'll close this issue. Please feel free to re-open this issue, or open a new issue, if you have anymore questions.
