### ISSUE TITLE
two different results with add_relative_targets and features as the same

### ISSUE THREAD

**Issue by nwallia** [prioritizr/prioritizr#239]
Hi all,

Thank you in advance for all your help on this and all the work you've done in ensuring that prioritizr is utilized, documented, learned and troubleshooted so effectively. It's been a great learning experience. 

I've been running different scenarios identifying priority caribou habitat to restore in different ranges. At this time, I'm comparing the results I receive using two different habitat layers (habitat being the proxy for caribou since we don't have GPS collar data for most of the provinces). 

I'm also very new to R so my problems are fairly rudimentary. 

Btw, the minimum "undisturbed" threshold for caribou ranges is 65% (35% disturbed). Since this range, according to federal data, is 34% disturbed, I'm running this with a target of 1% restoration (in addition to 6% and 11% for 70% and 75% undisturbed respectively) using the add_relative_targets constraint (setting the target as a proportion of the maximum level of representation of features to restore in the study area) 

`fnames <- c("Polyg", "Linear", "Fire") #these are disturbance types`
`target = 0.01`

`#Problem with Intact Forests Layer as habitat`
`p <- problem(pu, fnames, cost_column = "Cost_IFL")%>%`
  `add_min_set_objective() %>%`
  `add_binary_decisions() %>%`
  `add_rsymphony_solver()`

`p1 <- p%>% add_relative_targets(target)`
`s1 <- solve(p1)`

![image](https://user-images.githubusercontent.com/104106108/164344571-954ec81d-0efc-4ce1-992e-891a942f13e5.png)

`#Problem with Ontario Land Cover Compilation as habitat`
`x <- problem(pu, fnames, cost_column = "NEAR_OLCC")%>%`
 `add_min_set_objective() %>%`
  `add_binary_decisions() %>%`
  `add_rsymphony_solver()`

`x1 <- x%>% add_relative_targets(target)`
`y1 <- solve(x1)`

`lock_out <- pu[pu$Lock_OLCC == TRUE, ]`
`x3 <- x1 %>% add_locked_out_constraints(lock_out)`
`y3 <- solve(x3)`
`plot(st_as_sf(y3[, "solution_1"]), main = "Lock Out Constraints - OLCC ",`
     `pal = c("grey90", "darkgreen"))`

![image](https://user-images.githubusercontent.com/104106108/164344551-e63ecb49-b922-4298-b95b-edee3d50c7bb.png)

The IFL map makes sense with such a small target but confused why I could be getting such a different output when nothing has changed except my "Cost" field (Cost = NEAR_OLCC). Any ideas? Again, many thanks as always, for your attention to this.

**Comment by jeffreyhanson** [comment]
Hi,

Awesome! Thanks for providing all that information - that's really helpful! Just to check that I understand correctly, are you asking why changing the cost data is having such a huge impact on the total area covered by the solutions? Is that right? If so, this could be because one of the cost data/columns (i.e. `"NEAR_OLCC"`) has (1) zero or near-zero values, or (2) more variation in the cost values than the other cost data/columns (so that lots of cheap planning units need to be selected to avoid planning units with really high costs). If you plot the different cost data/columns, do they look like? If possible, could you share them here?

**Comment by nwallia** [comment]
Appreciate your prompt response. Yes, you're exactly right - I'm wondering why changing the cost data is having such a large impact on the solution particularly when my target is so low (1% restoration). 

Sharing my cost data and it does appear that I have many zero or near-zero values. (Just an FYI, I derived my cost data, not as economic cost of restoration, but distance to "good habitat" where a planning unit closer to good habitat, whether IFL or OLCC, is preferred to restore). In the case of OLCC "good habitat" is spread out across the range, but fragmented/in small patches which is where all the zeroes are coming from. 

![cost_IFL](https://user-images.githubusercontent.com/104106108/164530090-09bfd9b7-26a1-4421-8aa4-ca4f37e14c1e.png)

![cost_OLCC](https://user-images.githubusercontent.com/104106108/164530281-18bed368-41a5-4d92-afa6-12903bdced6b.png)

Also I realize I forgot to include `add_locked_out_constraints` for in my IFL code snippet above, but its identical to the OLCC code.

**Comment by jeffreyhanson** [comment]
Ah ok - thank you for sharing all this information! Yeah, may I suggest transforming the data to ensure that there are no zeros? This is because a zero cost means that a planning unit does not cost anything at all, so this means that the solutions often include extra planning units with zero costs even if they are not needed to meet the targets (or improve species' representation). So, I would suggest modifying the values in the cost columns by adding a small number to them. For example, something like this:

```
pu$NEAR_OLCC <- pu$NEAR_OLCC + 0.01
pu$Cost_IFL <- pu$Cost_IFL + 0.01
```

If that doesn't fix it, I would also suggest trying a stricter optimality gap. By default, prioritizr uses an optimality gap of 0.1, meaning that solutions will be within 10% of optimality. To ensure that solutions are optimal, you can specify an optimality gap of zero like this: `add_rsymphony_solver(gap = 0)`

Also, if you find that Rsymphony is taking too long to run, I would suggest using the CBC solver. This is a freely available open source solver that is much faster than SYMHPONY for these types of problems (see here for installation instructions: https://prioritizr.net/reference/add_cbc_solver.html). 

How does that sound? Let me know if that doesn't work or if you have any further questions?

**Comment by nwallia** [comment]
Transforming the cost data worked! Also refining the optimality gap seemed to further optimize the solution. 
![y3_v2](https://user-images.githubusercontent.com/104106108/164817104-41815b6b-cf19-42c4-8408-a939013a2ac7.png)
!

Actually, I havent found Rsymphony taking too long, although will try the CBC just to compare...the longest part of this is loading the plots via ggplot (for presentations/negotation purposes, it helps to have the feature/disturbance/habitat data included in the solution). Prioritizr and the open source solvers are working great! 

Glad it was a simple fix - appreciate your prompt attention to this! I will close the thread now.

**Comment by jeffreyhanson** [comment]
Awesome - glad to hear that it worked! Interesting - great to hear that Rsymphony isn't too slow. Yeah, if Rsymphony isn't too slow for your dataset, then I wouldn't bother using CBC. Thanks!
