### ISSUE TITLE
Running replacement importance on different problem/solution combination

### ISSUE THREAD

**Issue by ninzyfb** [prioritizr/prioritizr#241]
Hello, i would like to know if the workflow i am currently trying makes sense given the code or if it means i am misunderstanding how these functions work.

I am currently building my conservation problem using the gurobi solver (gap of 0) and generating a portfolio of 100 solutions using binary decisions only. I then sum these 100 solution together and get a final raster with values ranging from 0 to 100. I then keep only cells with values of 100 (i.e. cells chosen in every single solution) as my final solution.

However i then also want to run the replacement cost function but this would take to long to run on all 100 solutions. So what i have done to reduce time is taken my final solution and changed values of 100 to 1. I then also altered the problem so that it is now set with proportion decisions (to speed up the replacement function).I then run the eval_replacement_importance using the new problem and the summed solution. 

Is this appropriate to do or am i misunderstanding how these functions work? Thank you for your help! All the code is below:

## INITIAL PROBLEM
`problem_single = problem(pu,features)%>%`
      `add_relative_targets(t) %>%`       # protection targets (will apply to each feature)
      `add_min_set_objective()%>%`
      `add_gurobi_solver(gap=0) %>%`       # solutions needs to be optimal
      `add_gap_portfolio(number_solutions=100, pool_gap = 0)%>%`      # generate 100 solutions per problem
      `add_binary_decisions()`      # binary decisions`

## SOLVE
`solution_single = solve(problem_single)`

## CREATE RASTER STACK FROM SOLUTION
`solution_single = stack(unlist(solution_single))`
  
## create solution frequency raster (sum all solutions together)
`solution_sum= calc(solution_single,sum)`
    
## only keep values chosen 100% of the time and change 100 to 1
`values(solution_sum)[which(values(solution_sum)<100)] = 0`
`values(solution_sum)[which(values(solution_sum)==100)] = 1`

## REDEFINE PROBLEM (changing decisions to proportional)
`problem_single = problem(pu,features)%>%`
      `add_relative_targets(t) %>%`       # protection targets (will apply to each feature)
     `add_min_set_objective()%>%`
      `add_gurobi_solver(gap=0) %>%`       # solutions needs to be optimal
      `add_gap_portfolio(number_solutions=100, pool_gap = 0)%>%`       # generate 100 solutions per problem
      `add_proportion_decisions()`     # binary decisions

## RUN IRREPLACEABILITY FUNCTION
`ir <- eval_replacement_importance(problem_single, solution_sum, rescale = FALSE)`

**Comment by jeffreyhanson** [comment]
Hi @ninzyfb,

Yeah, may I ask what the overall goal of this analysis is? In most cases, I wouldn't recommend generating a new solution using only planning units with high "importance" (e.g., irreceplaceability or selection frequency) values. Although the "importance" values can be helpful to identify which planning units are absolutely critical for meeting the targets (which can inform scheduling or stakeholder discussions), a solution that _only_ contains such planning units is unlikely to meet the targets for all biodiversity features. In other words, planning units with high "importance" might be _neccesary_ (e.g., they need to be protected in order to meet all the targets, because they contain biodiversity not found anywhere else) but they are not _sufficient_ (e.g., protecting these places alone is not enough to meet all the targets, and additional places need to be protected to meet all the targets).

For example, let's say we wanted to generate a prioritization for a study area. Let's also say that our overall goal is that we want to adequately represent a comprehensive snapshot of biodiversity (per the CARE principles). This means that we want to identify priority areas that will secure habitat for highly rare/endemic/threatened species as well as more common/non-threatened species too. Since planning units that contain highly rare/endemic/threatened species often have higher "importance" values (assuming equal costs), if we generated a solution that only contained planning units with high "importance" values (based on the method you described), then the solution would very likely not meet the targets for all species (it might only meet targets for the very rare/endemic/threatened species). As such, this solution would not achieve our overall goal. Instead, to acheive our overall goal, we might want a min set solution that meets all the targets for all the species. Certainly, selection frequencies can help us interpret the relative importance of different planning units in the min set solution---but these planning units alone will not meet the overall goal.

This rationale/explanation is why the [Marxan Good Practices handbook](https://pacmara.org/wp-content/uploads/2010/07/Marxan-Good-Practices-Handbook-v2-2010.pdf) recommends using/reporting both individuals solutions (e.g., the best solution, or individual solutions in a portfolio) as well as the selection frequencies in conservation planning exericses. Specifically, it says "When interpreting and communicating summed solutions [i.e., selection frequencies], it is very important to be clear that the summed solution output is not a reserve network fulfilling the criteria of a given scenario. To clarify the difference, the summed solution [i.e., selection frequencies] should be presented in conjunction with one or more of the better individual solutions." (page 100).

Does that help? Please let me know if I've misunderstood your question, or if anything I've written doesn't make sense?

**Comment by ninzyfb** [comment]
Hi Jeff,

As always thank you for such a detailed and informative response. To answer your first question, the goal of this analysis is to identify a number of areas to bring forward to stakeholders and engage in discussions about where important shark and ray areas are found within our EEZ (South Africa).

I did notice that when running the `eval_target_coverage_summary()` function on this new summed solution many targets were not met anymore which points exactly to the issue you mention about using only the important cells. However because i know that we are only wanting to present the most important cells i thought this might not be that problematic. Especially since it is extremely unlikely that the entire solution will be converted to a protected area network and we are also trying to focus on endangered and endemic species.

Thank you very much for pointing me towards the Marxan Good Practices Handbook, i will definitely take your suggestion on board and present (1) a map of selection frequencies, and then (2) one of the optimal solutions from the solutions portfolio and run the importance function on that one solution.

Thanks again for your help, Nina

**Comment by jeffreyhanson** [comment]
No worries! Ah ok - awesome - yeah that sounds great! I might suggest that (i) it could be useful to show multiple (near) optimal solutions to show different spatial configurations (e.g., so if there's one place selected in one solution that one of the stakeholders doesn't want protected, then you have another solution ready to present), and (ii) if you think the entire min set solution with the targets is too large/costly, it might be worth imposing a budget using the min shortfall objective (e.g., based on, area or opportunity costs to fishing) or generating multiple prioritizations under a range of different targets (e.g., setting targets as 5% of their current value, 10% of current value, 20% of current value, etc). It might also be worth (iii) generating a portfolio with a larger number of solutions and a relaxed optimality gap (e.g. 15%) to obtain a portfolio with solutions that are much more different from each other (in terms of which places are selected or not). What do you think? These are just ideas though - please feel free to ignore them if you don't think they would make sense for your situation :)

**Comment by ninzyfb** [comment]
Thanks so much Jeffrey! i will definitely have a play with the different suggestions and see what works best :)

**Comment by jeffreyhanson** [comment]
No worries - happy to help!
