### ISSUE TITLE
different solution when feature stack is made up of binary or continuous layers

### ISSUE THREAD

**Issue by ninzyfb** [prioritizr/prioritizr#244]
Hi Jeffrey, Sorry i have another question. I am struggling to understand why when using the same targets and features, the solution differs if these features are made up of continuous values or made up of binary values.

By that i mean that in one features stack, each layer is the distribution of a species where each cell has a probability of suitable habitat ranging between >0 and 1. All other values are set to NA. Whilst for the other stack, i have convert all non-zero values to 1 and all other values to NA. The targets for both problems are the same so i would assume the solution to be the same? And since they are not i was wondering if there was documentation that explained how the solver uses continuous probability values differently to binary ones? Thanks so much! all the code and data should be available from this folder: https://www.dropbox.com/sh/bmnsd53c9gca9lq/AADPRC2cJhiLzkelnUhzpdeAa?dl=0 

### loading features and targets
sdms_thresholds = readRDS(list.files(pattern = "sdms_thresholds.RDS", recursive = T,full.names = T))
t = readRDS(list.files(pattern = "t.RDS", recursive = T,full.names = T))

### creating continuous feature stack
features_continuous = sdms_thresholds
values(features_continuous)[which(values(features_continuous)==0)] = NA

### creating binary feature stack
features_binary = sdms_thresholds
values(features_binary)[which(values(features_binary)==0)] = NA
values(features_binary)[which(values(features_binary)>0)] = 1

###  setting the problem
problem_single_binary = problem(pu,features_binary)%>%
  add_relative_targets(t) %>%
  add_min_set_objective()%>%
  add_gurobi_solver(gap=0) %>%
  add_binary_decisions()

problem_single_continuous = problem(pu,features_continuous)%>%
  add_relative_targets(t) %>%
  add_min_set_objective()%>%
  add_gurobi_solver(gap=0) %>%
  add_binary_decisions()

### solving the problem
solution_binary = solve(problem_single_binary)
solution_continuous = solve(problem_single_continuous)

### plotting the solution
plot(solution_binary)
plot(solution_continuous)

**Comment by jeffreyhanson** [comment]
Hi @ninzyfb,

Thank you very much for providing the data and code - that's extremely helpful!

Yeah, the reason why we are seeing different solutions is because (1) the targets (by default, when using `add_min_set_objective()`) are saying that the solutions need to contain at least a threshold amount of each feature, and (2) rounding the feature data can fundamentally alter how these targets can be met by solutions.

Let's consider a small example to illustrate this. In particular, let's pretend that we have 1 feature and 6 planning units. Let's also pretend we have some habitat suitability data that denote how suitable the habitat inside each planning unit is for the feature. We can use the following R code to describe this.

```
pu_id <- c(1, 2, 3, 4, 5, 6)
habitat_cont <- c(0.1, 0.4, 0.5, 0.8, 0.2, 0)
```

If we set our target as 50% of the total amount of the feature (i.e., `0.5 * sum(habitat_cont) = 1`), this means that we want a solution that contains a set of planning units with habitat values that sum to a value >= 1. So, assuming that each planning unit has equal costs, the optimal solution would select the fourth and fifth planning units (because `0.8 + 0.2 = 1`). We could describe this first solution like this.

```
sol1 <- c(0, 0, 0, 1, 1, 0)
```

Does that make sense so far?

Now let's try rounding that data. Although rounding data would normally involve converting values greater than 0.5 to one, I saw that your code converts values greater than zero to one -- so I've used that here for consistency.

```
habitat_bin <- c(1, 1, 1, 1, 1, 0)
```

If we set our target as 50% of the total amount of the feature (i.e., `0.5 * sum(habitat_bin) = 2.5`), this means that we want a solution that contains a set of planning units with habitat values that sum to a value >= 2.5. Since the planning units have equal costs, this means that any solution that selects three different planning units -- excepting the last planning unit -- would be considered optimal. For example, a solution that contains the 1st, 2nd, and 3rd planning units would be an optimal solution. We could describe this second solution like this.

```
sol2 <- c(1, 1, 1, 0, 0, 0)
```

We can see that `sol1` and `sol2` are different. Additionally, we can also see that our first solution does not meet the targets for the rounded data problem (because `1 + 1 <= 2.5`) , so it should/would never be returned as a solution to the second problem (assuming the minimum set objective). Does that help? Please let me know if there's any further details I can provide?

**Comment by jeffreyhanson** [comment]
Hi @ninzyfb, I just wanted to follow up and ask if that answered your questions, or if you had any further questions?

**Comment by ninzyfb** [comment]
Hi @jeffreyhanson apologies for the delay the answer was extremely helpful i simply forgot to reply! I have decided to go for the rounded option. I shouldve explained how i got to rounding any values >0 to 1. My initial biodiversity features were rasters where every PU had a probability of occurrence/suitable habitat value between 0 and 1. However i only wanted to keep the "core" range of each species so i used a binarization method to find which threshold value for each map i could use to convert values above that threshold to 1 and below that threshold to 0. So when i am converting all values greater than 0 to 1, this is on the map for which i have already removed values below the threshold. I am of the thinking that since i am then only keeping the core range of each species i would rather each PU has a value of 1 and so gets seen equally by the prioritization algorithm. The solutions seem to make more sense than when i use the continuous values. thank you for your help!

**Comment by jeffreyhanson** [comment]
Glad that helped! Yeah, if your rounding approach only contains the core areas -- because you've previously excluded other areas --  then that makes sense to me. No worries - happy to help!
