### ISSUE TITLE
Warning in presolve_check.OptimizationProblem(compile(x))

### ISSUE THREAD

**Issue by MillerJeju** [prioritizr/prioritizr#260]
Hi, It feels really good to be able to conduct research with prioritiz. The number of units in the research area I am conducting is large. While doing research, I ran into the following error: I tried to search, but couldn't find a solution. Please help me.

jeju_cost is a shp file that includes cost, locked_in, and locked_out, and con is tif file, the result of Maxent 3 species.

`p10_c <- problem(jeju_cost, features = con,
                 cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.10) %>%
  add_locked_in_constraints("locked_in") %>%
  add_binary_decisions()
`
Conservation Problem
  planning units: SpatialPolygonsDataFrame (797875 units)
  cost:           min: 0, max: 5011.53846
  features:       norm_noru, norm_aegibul, norm_dorong (3 features)
  objective:      Minimum set objective 
  targets:        Relative targets [targets (min: 0.1, max: 0.1)]
  decisions:      Binary decision 
  constraints:    <Locked in planning units [2627 locked units]>
  penalties:      <none>
  portfolio:      default
  solver:         default

`> s1 <- solve(p10_c)`
Warning in presolve_check.OptimizationProblem(compile(x)) :
  most planning units do not have any features inside them, try obtaining data for more features to ensure that solutions are biologically meaningful
Error in .local(a, b = b, ...) : 
  problem failed presolve checks, for more information see ?presolve_check

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for reaching out @MillerJeju!

This error is saying that the problem failed one or more presolve checks. The presolve checks are run before solving a problem to check for potential issues that might result in strange, invalid, or undesireable solutions (i.e. solutions that might be mathematically valid, but clearly aren't helpful for policy). Here, we can see the presolve checks are saying that most planning units don't have any features inside them. For example, you might have 200k planning units in total, but only 1k planning units actually have at last one species present inside them. So, depending on the goals of your study, the warning is saying that if you want to identify important areas for biodiversity from among all of the planning units, then you might need more features/species to help ensure that you're not missing out on any important areas. However, if you're only interested in these three species -- and don't care about any other biodiversity in the study area at all -- then you can ignore this presolve check. If that's the case, you can tell prioritizr to ignore the failed presolve check using `solve(p10_c, force = TRUE)`. How does that sound?

Also, I notice that some of your planning unitsh have zero costs. This can cause issues because the solution might randomly contain some of the zero-cost planning units even if they aren't needed to meet the targets. The reason why they are randomly selected is because they are considered free (because they cost absolultly nothing). In most cases, this is undesireable -- because if you're trying to identify priority areas, then having these additional superfluous planning units in the solution make it difficult to identify the "real" priority areas -- so people generally transform the values to avoid zeros. For example, you could rescale the values between 1 and 1000, or add a small number to all the costs (e.g. 0.01) to avoid zeros. What do you think?

Please let me know if anything I've wrriten isn't clear, or if you have any follow up questions?

**Comment by MillerJeju** [comment]
Thank you so much for your reply.
Your answer is the only way to solve the problem for me. Since it is my first time with Prioritizr, I am in the process of pilot testing, so I only conducted 3 species. From your answer, it seems that the planning unit needs to be modified. I'll try some more and let you know the results. I also read the papers you published while doing research, and I was really impressed. I may not be able to do research with you, but it would be great to do related research with you.

**Comment by jeffreyhanson** [comment]
No worries! Yeah, trying out prioritizr with a small dataset is a great way to learn how to use it. Brilliant - let me know if you run into any further issues or have any questions about interpreting the results? I'm always happy to answer any questions about prioritizr. Thanks for the kind words!

**Comment by jeffreyhanson** [comment]
Closing this since I think we've addressed the issue. Please feel free to re-open this issue or create a new issue if you want to chat more about this.
