### ISSUE TITLE
Evaluating solutions for problems with tabular inputs

### ISSUE THREAD

**Issue by Carina-Firkowski** [prioritizr/prioritizr#264]
Hi, 
I'm getting started with `prioritizr` and having issues evaluating solutions when creating a problem using tabular data. I'm currently following the documentation examples and using the sample datasets provided by the package.
```
# specify file path for planning unit data
pu_path <- system.file("extdata/input/pu.dat", package = "prioritizr")
# load in the tabular planning unit data
pu_dat <- data.table::fread(pu_path, data.table = FALSE)

# set file path for feature data
spec_path <- system.file("extdata/input/spec.dat", package = "prioritizr")
# load in feature data
spec_dat <- data.table::fread(spec_path, data.table = FALSE)

# set file path for planning unit vs. feature data
puvspr_path <- system.file("extdata/input/puvspr.dat", package = "prioritizr")
# load in planning unit vs feature data
puvspr_dat <- data.table::fread(puvspr_path, data.table = FALSE)
```

Then, I'm creating the problem with the following objective, target, decision, and solver:
```
# create problem
p1 <- problem(pu_dat, spec_dat, cost_column = "cost", rij = puvspr_dat) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.15) %>%
  add_binary_decisions() %>%
  add_rsymphony_solver(gap = 0.015)

# solve the problem
s1 <- solve(p1)
# solution
head(s1)
```
```
## id     cost       status      xloc     yloc             solution_1
## 3     0.000       0           1116623 -4493479          0
## 30    7527.275    3           1110623 -4496943          0
## 56    37349.075   0           1092623 -4500408          0
## 58    16959.021   0           1116623 -4500408          0
## 84    34220.256   0           1098623 -4503872          0
## 85    178907.584  0           1110623 -4503872          0
```

To evaluate the cost summary of the solution, I first tried:
```
# calculate solution cost
cost <- eval_cost_summary(p1, s1)
```
This returned `Error: solution object should contain a single column with solution values`.
Then, I tried:
```
# calculate solution cost
cost <- eval_cost_summary(p1, s1[,"solution_1"])
```
And it returned `Error: argument to x and solution object have planning unit data in different formats`.

I get the same errors when running the `eval_target_coverage_summary` function, as well as:
```
# calculate replacement cost scores
replacementImportance <- p1 %>%
    eval_replacement_importance(s1)
```
or
```
# calculate replacement cost scores
replacementImportance <- p1 %>%
    eval_replacement_importance(s1[,"solution_1"])
```

Any help would be appreciated. Thanks!

**Comment by jeffreyhanson** [comment]
Hi @Carina-Firkowski,

Thank you very much for reaching out! 

I think this is happening because `s1` is a `data.frame`, and so `s1[,"solution_1"]` will return a numeric vector (instead of a data frame with a single column). To address this, you could do  `s1[,"solution_1", drop = FALSE]` . Alternatively, if you convert the data frame object to a `tibble::tibble` object (using `tibble::as_tibble()`), then `s1[,"solution_1"]`  will return a data frame with a single column (i.e. a `tibble::tibble()` with a single column). I suspect the examples you're referring to have the data frames stored as a `tibble::tibble` (and not a `data.frame`), so  `s1[,"solution_1"]` works in the examples.

Does that help? Please let me now if that doesn't fix it.

**Comment by Carina-Firkowski** [comment]
Hi @jeffreyhanson,
Adding `s1[,"solution_1", drop = FALSE]` worked perfectly.
Thanks so much!

**Comment by jeffreyhanson** [comment]
Awesome - glad to hear its working!
