### ISSUE TITLE
Error: number_of_total_units(x) not equal to nrow(solution@data)

### ISSUE THREAD

**Issue by MillerJeju** [prioritizr/prioritizr#265]
Hi, I believe my problem is quite simple. I really want to advance my research using Prioritizr. 

By setting several constraints and checking the solution, I also checked the shp file. The jeje_cost_got map is a shp file.  
However, a problem occurred in checking irreplaceability. This is the first time I have done research using R. I mainly referred to Prioritizr Github and https://github.com/KCarrollEcology/StarProtocols2021_Wolverine/blob/main/Priortizr_code.Rmd.
At first, there was a problem like this: Error in x$ed: $ operator is invalid for atomic vectors, so after editing, the following error occurred and I couldn't move on to the next step.

> rc17_abosl_p0$rc[rc17_abosl_p0$rc > 100] <- 1.09
Error in `*tmp*`$rc : $ operator is invalid for atomic vectors

> rc17_got_p0 <- p17_got_p0 %>%
 +   add_default_solver(gap = 0, verbose = FALSE) %>%
 +   eval_replacement_importance(s17_got_p0[, "solution_1"])
Error: number_of_total_units(x) not equal to nrow(solution@data)
In addition: Warning message:
In res(x, ...) : overwriting previously defined solver

This is the code from the problem setting.

```
## got, penalty 0, target 17%      
p17_got_p0 <- problem(jeju_cost_got, es, cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.17) %>%
  add_locked_in_constraints("locked_in") %>%
  add_locked_out_constraints("locked_out") %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap=0)

print(p17_got_p0)


## got, penalty 0.05, target 17%
p17_got_p005 <- problem(jeju_cost_got, es, cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_boundary_penalties(penalty = 0.05) %>%
  add_relative_targets(0.17) %>%
  add_locked_in_constraints("locked_in") %>%
  add_locked_out_constraints("locked_out") %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap=0)

print(p17_got_p005)

## got, penalty 0.1, target 17%
p17_got_p01 <- problem(jeju_cost_got, es, cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_boundary_penalties(penalty = 0.1) %>%
  add_relative_targets(0.17) %>%
  add_locked_in_constraints("locked_in") %>%
  add_locked_out_constraints("locked_out") %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap=0)


print(p17_got_p01)


s17_got_p0 <- solve(p17_got_p0)
s17_got_p005 <- solve(p17_got_p005)
s17_got_p01 <- solve(p17_got_p01)


rc17_got_p0 <- p17_got_p0 %>%
  add_default_solver(gap = 0, verbose = FALSE) %>%
  eval_replacement_importance(s17_got_p0[, "solution_1"])


rc17_got_p005 <- p17_got_p005 %>%
  add_default_solver(gap = 0, verbose = FALSE) %>%
  eval_replacement_importance(s17_got_p005[, "solution_1"])


rc17_got_p01 <- p17_got_p01 %>%
  add_default_solver(gap = 0, verbose = FALSE) %>%
  eval_replacement_importance(s17_got_p01[, "solution_1"])


s17_got_p0 <- s17_got_p0[ which(s17_got_p0$solution_1 == 1 ),]
s17_got_p005 <- s17_got_p005[ which(s17_got_p005$solution_1 == 1 ),]
s17_got_p01 <- s17_got_p01[ which(s17_got_p01$solution_1 == 1 ),]


writeOGR(s17_got_p0, dsn="G:/got/solve/s17_got_p0.shp", driver="ESRI Shapefile", layer = "solution_1")
writeOGR(s17_got_p005, dsn="G:/got/solve/s17_got_p005.shp", driver="ESRI Shapefile", layer = "solution_1")
writeOGR(s17_got_p01, dsn="G:/got/solve/s17_got_p01.shp", driver="ESRI Shapefile", layer = "solution_1")


rc17_got_p0$rc[rc17_got_p0$rc > 100] <- 1.09
rc17_got_p005$rc[rc17_got_p005$rc > 100] <- 1.09
rc17_got_p01$rc[rc17_got_p01$rc > 100] <- 1.09


writeOGR(rc17_abosl_p0, dsn="G:/got/rc/rc17_got_p0.shp", driver="ESRI Shapefile", layer = "solution_1")
writeOGR(rc17_abosl_p005, dsn="G:/got/rc/rc17_got_p005.shp", driver="ESRI Shapefile", layer = "solution_1")
writeOGR(rc17_abosl_p01, dsn="G:/got/rc/rc17_got_p01.shp", driver="ESRI Shapefile", layer = "solution_1")
```

**Comment by jeffreyhanson** [comment]
Hi,

I'm sorry, I don't exactly understand what's causing the error.  Could you please post a minimal reproducible example with the data so that I can re-create the error on my computer?

**Comment by MillerJeju** [comment]
[test.zip](https://github.com/prioritizr/prioritizr/files/10739100/test.zip)

Thank you Jeffrey!!
I attached my test data. PlanningUnit_test3 is cost and 2 Ecoysystem services value. Please clip the tif file when you use the data.
In my real data. I have 200MB Planning Unit and 5 Ecosystem service data.

**Comment by jeffreyhanson** [comment]
I'm sorry, I can't seem to reproduce the error. I've included the code I'm using below, could you please see if it works on your computer? If not, could you please try updating the version of prioritizr installed on your computer, and post your session information (`sessionInfo()`)? If it does work, could you please edit it so that it produces the error you saw before and post the updated code?

Also, for future reference, a reproducible example should include code and data and, ideally, the example code should look something like this. It should be a short script that loads the relevant packages at the top, imports the data, and then has only the neccesary code needed to produce the error (or in this case, try and produce the error). When making a reproducible example, you'll often need to create a new script (i.e., not just post parts of the script your working on for the "real" analysis). This is important so that the person trying to help you can simply copy-and-paste the script into their computer and get exact error that you're seeing. After they can get the exact error message that you're seeing, its makes it a lot easier for them to work out what's going wrong. So, by posting a really good reproducible example, you're helping the person whose trying to help you, and making it a lot easier for the person helping you to get the code working. For example, as you can see below, I've had to make some assumptions about the data (e.g. which file has the PUs, which has the features, how the data should be imported), and it's possible that some of the assumptions I'm making aren't correct or a different from your code -- which makes it harder for us to work out what's going wrong in your code. How does that sound?

----

```
# load packages
library(prioritizr)
library(raster)
library(sf)

# load data
pu_data <- read_sf("PlanningUnit_test3.shp")
feature_data <- raster::stack("cs_norm.tif")

# coerce data types
pu_data$locked_in <- as.logical(pu_data$locked_in)
pu_data$locked_out <- as.logical(pu_data$locked_out)

# ensure feature data and planning units have same CRS
feature_data <- raster::projectRaster(feature_data, crs = st_crs(pu_data)[[2]])

# create problem
p1 <-
  problem(pu_data, feature_data, cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.17) %>%
  add_locked_in_constraints("locked_in") %>%
  add_locked_out_constraints("locked_out") %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0)

# solve problem
s1 <- solve(p1)

# calculate replacement cost
rc1 <- eval_replacement_importance(p1, s1[, "solution_1"])

# print result
print(rc1)
```

**Comment by MillerJeju** [comment]
Thank you so much Jeffrey!! When I first posted about this, I was very inexperienced. I'm very sorry. I ran it with the code you posted and it worked fine. It seems that there was an error that the Planning Unit was converted to raster in the process of using the code I uploaded first. I post the code I solved below.

```
library(prioritizr)
library(raster)
library(sf)
library(rgdal)
library(beepr)
library(gurobi)
library(sp)
library(rgeos)


# import planning unit data
jeju_cost_absol <- as(read_sf("landprice_absol_final.shp"), "Spatial")



# format columns in planning unit data
jeju_cost_absol$locked_in <- as.logical(jeju_cost_absol$locked_in)
jeju_cost_absol$locked_out <- as.logical(jeju_cost_absol$locked_out)


# Ecological source
cs <- raster("cs_norm.tif")
names(cs) <- "csTop"

hq <- raster("hq_norm.tif")
names(hq) <- "hqTop"

swy <- raster("swy_norm.tif")
names(swy) <- "swyTop"

sq <- raster("sq_norm3.tif")
names(sq) <- "sqTop"

sdm <- raster("sdm_norm.tif")
names(sdm) <- "sdmTop"

stk <- stack(cs, hq, swy, sq_resample, sdm_resample )

es <- crop(stk, jeju_cost_absol)

# ensure feature data and planning units have same CRS
jeju_cost_absol@proj4string <- es@crs


## Target 17%  
p17_absol_p0 <- problem(jeju_cost_absol, es, cost_column = "cost") %>%
  add_min_set_objective() %>%
  add_relative_targets(0.17) %>%
  add_locked_in_constraints("locked_in") %>%
  add_locked_out_constraints("locked_out") %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap=0)

print(p17_absol_p0)


## Solve problem
s17_absol_p0 <- solve(p17_absol_p0)


# calculate replacement cost
rc0 <- eval_replacement_importance(p17_absol_p0, s17_absol_p0[, "solution_1"])


#print results
print(rc0)
```

**Comment by jeffreyhanson** [comment]
Awesome! Glad to hear its all working now. No worries at all, everyone's inexperienced when they try new stuff :) I just wanted to add a bit of detail about the reproducible example stuff because I thought it might be helpful for the future (e.g. if you post stuff on stack overflow, or other github repositories). If you don't have any futher questions, I'll close this issue?

**Comment by MillerJeju** [comment]
Yes, please close this issue. Thank you so much!!

**Comment by jeffreyhanson** [comment]
Ok - no worries, happy to help!
