### ISSUE TITLE
relative target issue

### ISSUE THREAD

**Issue by MillerJeju** [prioritizr/prioritizr#267]
Hi, I'm doing a study using Prioritizr and it's very interesting. 

I'm running with a relative target of 17%. I've tried no penalty and a boundary panelty value of 0.05. I set the existing protected area to locked_in in the study area. When I don't set the boundary penalty, there are no new solution areas other than the existing protected areas, but when I penalize, there are new solution areas.  Is the reason why no soltuon areas are found when I don't set the boundary penalty, because the existing protected areas are 18%? If so, is there a reason why the solution areas are identified when the boundary penalty is applied?

**Comment by jeffreyhanson** [comment]
Hi @MillerJeju,

Yeah, that could explain what's happening. Assumming that the locked in areas already meet the targets (which can be verified with `eval_target_coverage_summary()`, see https://prioritizr.net/reference/eval_target_coverage_summary.html), then the prioritizations won't need to select additional planning units to meet the targets (under the min set objective). Since you're objective is to minimize costs, the optimization process -- when you don't have boundary penalties -- is only focussing on the meeting targets as cheaply as possible, and so the prioritization will simply just contain the locked in planning units. However, when you add boundary penalties, you're saying that you want to minimize the weighted sum of the costs and also the total boundary length (perimeter) of the solution. Since the penalty is non-zero, this means that you're happy to have a more expensive solution, so long as the solution can have a reduced total boundary length. So, the optimization process no longer just cares about minimizing cost, it also cares about selecting planning units to help reduce total boundary length. This is why the solution with the boundary length contains extra planning units selected. If you set the penalty value closer to zero, then the optimization process will care more about minimiznig costs, and less about minimizing the total boundary legnth. Indeed, setting the penalty value to zero is basically the same as not adding in the boundary penalties at all.

How does that sound? Please let me know if anything I've written doesn't make sense, or if you have any follow up questions?

**Comment by jeffreyhanson** [comment]
Also, in terms of a more practical answer, if all the targets are already met, then this might suggest one of the following:

1. You might need to set more ambitious targets. If the protected area system is already meeting the targets, then this suggests that the protected area system might already be covering core/critical areas, and higher targets might be needed to identify areas for expanding the protected area system beyond these core/critical areas. For example, maybe the targets were set so that every species should have >= 10km^2 of habitat in protected areas (based on IUCN AOO threshold for CR species), and so maybe it would be more worth setting targets >= 500 km^2 to identify areas for protected area establishment (based on IUCN AOO threshold for EN species).
2. You might need to set more meaningful targets. For example, the targets might be set using policy (e.g. 17% based Aichi targets), and these might not be appropriate for your features (e.g. species). For example, the Rodrigues method (https://doi.org/10.1641/0006-3568(2004)054[1092:GGAPRF]2.0.CO;2) is one approach for setting targets for species, and one of its advantages is that it sets much higher percentage targets for species with smaller ranges.
3. You might need to consider additional features. For example, if all the targets are already met by the existing protected areas system, then this might suggest that you need more features (e.g. species, ecosystem types) to identify important areas for expanding the protected area system. For example, if you're only considering one group of species (e.g. just birds), then you might missing important areas for other taxa (e.g. reptiles). Similarly, if you're only considering highly threatened taxa, then you might be missing important areas to maintain remaining habitat for less threatened taxa.
4. Finally, it's also possible that the protected area system is, actually, already complete. This is usually not the case, but it is worth thinking about. For example, if you're deliberately restricting your analysis to highly threatened species (because that's the aim of the analysis), and the results show that these species are already adequatley covered by existing protected areas, then this might suggest that other actions might be needed for these species (instead of protected area expansion). For example, these species might need captive reintroduction programmes, or better management of protected areas (e.g., some of the threatened species might be really sensitive to pest species, and so it might be more important to upgrade existing protected areas to reduce abundance of pest spcies).

I'm sure there are other possibilities too, these are just some things that I thought of off the top of my head :)

**Comment by MillerJeju** [comment]
Thank you very much for your kind response. 
That's really interesting about the penalty values, and it's also great that the Prioritizr takes into account the conservation goal based on the penalty value. Last December released Kunming & Montreal Framework from CBD, they increased the conservation goal to 30%, so it would be interesting if I can cover the conservation goal from 17% to 30%.

Your suggestions are really impressive. I think it would be interesting to do a study that considers not only species targets but also what ecosystem services are involved. I'll try to read some of the literature on what you've suggested. Thanks so much, Jeff.

**Comment by jeffreyhanson** [comment]
Yeah, that's an excellent point @ricschuster! 

@MillerJeju, do you have any further questions? If  not, would you mind if I closed the issue?

**Comment by MillerJeju** [comment]
Thank you so much @ricschuster !!

No, I don't have. Thank you @jeffreyhanson!

**Comment by jeffreyhanson** [comment]
No worries!
