### ISSUE TITLE
add_boundary_penalty & eval_connectivity_summary issues

### ISSUE THREAD

**Issue by MillerJeju** [prioritizr/prioritizr#270]
Hello, I find it fascinating every time I use Prioritizr. I apologize for asking questions too often. In my research, I am conducting studies that consider connectivity. I understand that when using the add_boundary_penalty() function, higher penalty values prefer solutions with a higher degree of spatial clumping, and smaller penalty values prefer solutions with a smaller degree of clumping. I assigned penalty values of 0.05 and 0.1 to obtain a solution, and then used eval_connectivity_summary() to check the degree of connectivity. However, is it possible for the connectivity value of 0.05 to be higher than 0.1? I think it may vary depending on the distribution of the already set protected areas. I am curious about the reason for this. Below is an example of the code I used.

```
pu1$pas <- round(pu$locked_in)
#pu1 is plannig units
#locked_in is protected areas

#setting the connectivity matrix
cm <- connectivity_matrix(pu1, "pas")

#evaluate connectivity of solution
#p1 with 0.05 penalty
#p2 with 0.1 penalty
con_s1 <- eval_connectivity_summary(p1, s1[, "solution_1"], data = cm)
con_s2 <- eval_connectivity_summary(p2, s2[, "solution_1"], data = cm)
```

**Comment by jeffreyhanson** [comment]
Ah, I think the reason for this discrepancy is that you're not using connectivity penalties to generate the solutions. Instead, you're using boundary penalties to generate solutions. Athough boundary penalties are generally thought to help with connectivity because they will spatially cluster togeather, you're evaluating the connectivity using a specific set of assumptions (i.e., per the `cm` matrix). This means that we might see differences between boundary penalties and the connectivity held in a solution. For consistency I would suggest (i) using connectivity penalties to generate the solution (e.g., something like `add_connectivity_penalties(cm, penalty = 1)`) or (ii) evaluating the solutions based on boundary length (e.g., something like `eval_boundary_summary(s1)` . How does that sound?

Also, by using the locked in values to create the connectivity matrix, you're saying that "connectivity" only counts when you have (i) two locked in planning units next to each other in a solution, or (ii) one locked in and one non-locked in planning units next to each other in a solution. Thus it doesn't "count" for connectivity if you have a solution where two planning units are selected (not locked in) thast are next to each other.

**Comment by MillerJeju** [comment]
That's great @jeffreyhanson. Thank you so much!!
I understand what you're saying. In my research, `eval_boundary_summary(s1)` seems more appropriate.

**Comment by jeffreyhanson** [comment]
No worries! Excellent - sounds good!

Did you have any further questions on this topic? If not, we'll the close the issue?

**Comment by MillerJeju** [comment]
@jeffreyhanson 
That was all. Thank you so much!!

**Comment by jeffreyhanson** [comment]
Ok great! I'll close this now then.
