### ISSUE TITLE
Boundary penalty & sensitivity analysis

### ISSUE THREAD

**Issue by MillerJeju** [prioritizr/prioritizr#275]
Hi there,
When setting the boundary penalty, I looked at the previous studies and performed a sensitivity analysis. Is there a way to analyze the sensitivity analysis in Prioritizr? I think it would be nice to have a quantitatively logical procedure for assigning penalty values. 

They conducted a sensitivity analysis on the two studies.
Benez-Secanho FJ, Dwivedi P, Ferreira S, Hepinstall-Cymerman J, and Wenger S (2022) Trade-offs between the value of ecosystem services and connectivity among protected areas in the Upper Chattahoochee watershed. Environmental Management, 69: 937–951.

Duchardt CJ, Monroe AP, Heinrichs JA, O’Donnell MS, Edmunds DR, and Aldridge CL (2021) Prioritizing restoration areas to conserve multiple sagebrush-associated wildlife species. Biological Conservation, 260: 109212.

**Comment by jeffreyhanson** [comment]
Hi @MillerJeju,

Yeah, there's a few ways to quantatively determine a "good" penalty value. For example, you can use Cohon's method or a constraint approach (e.g., adding constraints to say that I'm willing to pay 15% extra for a reduce total exposed boundary length as much as possible). These are described in the calibrating trade-offs vignette (https://prioritizr.net/articles/calibrating_trade-offs_tutorial.html). Let me know if anthing's not clear in the vignette? 

That said, there isn't really a "correct" boundary penalty. This is because it represents the trade-off between your primary objective (e.g., minimizng cost) and a secondary objective (i.e., minimizing total exposed boundary length) and different people will have different ideas on what the right trade-off is depending on the context. In some sitatuations, a much lower boundary length would be best, and in other situations, a much higher boundary length is really important.  Does that help?

**Comment by MillerJeju** [comment]
Thank you!! @jeffreyhanson 

We are currently using R following your suggestions. Although it may take some time to complete the analysis, we are grateful for the information you provided. We are using the Cohon method, but it seems to produce only one appropriate penalty value. What if we use two or three penalty values instead? We have noticed that some papers using this package set the values without conducting sensitivity analysis. Would this pose a problem? For now, we are trying to analyze the data by specifying penalty values of 0.05 and 0.1 before using the Cohon method. As you mentioned, the interpretation of the analysis results may depend on the study's context.

**Comment by jeffreyhanson** [comment]
Yeah, that's right. The Cohon method is designed to find a single penalty value. If you're interested in a couple of different values, you could try increasing or decreasing it by some percent - but there will be a bit of trial and error to find some "acceptable" values. Regarding the sensitivity analysis, my impression is that most people conduct a rudimentary sensitivity analysis where they try a few different values and pick one that gives a reasonable result (e.g., just eye balling how the spatial priorititzations looks on a map). Yeah, I would say -- depending on the goals of the study/exericse -- that can be good enough. For instance, if you're specifically doing a study where connectivity is super important, then you'd definitely want something more robust. However, if you're just adding boundary penalties to make the spatial prioritization a bit easier to interpret then something simple/rudimentary is fine. Of course, the reviewers might have different opinions :) Does that help?

**Comment by MillerJeju** [comment]
Thank you for your  @jeffreyhanson 
That was very helpful. I think I just need to set the paper better for my research purpose. 
I think it's okay to close this issue.

**Comment by jeffreyhanson** [comment]
No worries - happy to help! Since I think we've answered all your questions now, I'll close the issue - but please feel free to reopen it or start a new one.
