### ISSUE TITLE
weighting disturbance features for a restoration problem

### ISSUE THREAD

**Issue by nwallia** [prioritizr/prioritizr#277]
Hi! 

You may remember my problem based on some questions I posted some time ago....still working on it! 

I am looking on ways to improve my caribou habitat restoration model. right now my cost data is derived from distance to suitable habitat and its trying to select disturbance features to restore to hit the 65% undisturbed habitat target. Initially my features were separated by either Anthropogenic and Fire and the results were quite binary and coarse. I am looking at trying add_feature_weights to weigh specific features (such as seismic lines or roads) to tell the model to preferentially select those features. 

My problem looks like this. 

```
fnames <- c("contains_Cutblocks", "contains_Fires","contains_Seismic Lines",
            "contains_Trails","contains_Road","contains_Communities", 
            "contains_Oil and Gas","contains_Agriculture","contains_Pests",       
            "contains_Mining","contains_NA","contains_Power","contains_Railway")

# amount of habitat needed to achieve 65% undisturbed in range
target = 0.26
target_2 = 0.31
target_3 = 0.36

## Problem with BC Core Habitat as Cost
p <- problem(pu, fnames, cost_column = "NEAR_DIST")%>%
  add_min_set_objective() %>%
  add_binary_decisions() %>%
  add_rsymphony_solver(gap = 0.01)

p1 <- p%>% add_relative_targets(target)
s1 <- solve(p1)
```
fnames is created by using the unique function to query for unique values in my disturbance type column in my PU file. It then creates a new column called "contains_(value)" and populates it with 1 if the original disturbance column contains that value. 

```

# assign a particularly high weighting to the linear features
w <- c(0, 0, 500, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0)

# create problem with high weighting for the third feature and fifth and solve it
s5 <- p1 %>% add_feature_weights(w) %>% solve()

```
however, I get this error: ` error in evaluating the argument 'a' in selecting a method for function 'solve': length(weights) not equal to x$number_of_features()
`
It looks like both the length of w and the number of features are the same. Is there a better way I can incorporate preferentially selecting specific features (i.e. seismic lines and roads) over others? 

Many thanks, as always for your help!

**Comment by jeffreyhanson** [comment]
Hi, 

Hmm, that's strange - would you might sharing your data so I can work out whats going on? Also, could you please try this with the GitHub version of prioritizr, in case this is due to a bug in an older version?

Also, I see that you're planning on using the weights with a min set objective. The min set objective doesn't use weights (in other words, they will be ignored). So I'd suggest (i) updating the targets so that they reflect the importance of different features, or (ii) using a budget-limited objective that uses targets (e.g., min shortfall objective).

How does that sound?

**Comment by nwallia** [comment]
Ok reran with the github version of prioritizr and also tried restructuring my problem. And I'm getting a new error after trying to run my initial problem: 
```
 ## Problem with BC Core Habitat as Cost
p <- problem(pu, fnames, cost_column = "NEAR_DIST")%>%
  add_min_set_objective() %>%
  add_binary_decisions() %>%
  add_default_solver()

```
It reads: ```
Error in `FUN()`:
! `x` is not a recognized class.

```
If i try using my old features (anthropogenic disturbance and fire) the problem executes fine. They are all 'numeric' classes or types. 

(For context: My problem is kind of atypical of a restoration problem because my cost data is not the $$ cost to restore, but the distance to good habitat. So I'd like the model to select planning units [with disturbance features in them] closer to good habitat rather than further away.)

I've been thinking about how to use the min shortfall objective where my "budget" will likely be the maximum distance in my cost column and my target will be the difference between the area that is disturbed to the minimum target caribou need identified in the Recovery Strategy (65% undisturbed/35% disturbed). From there I will try weighing my disturbance features. 

But perhaps I'm messing something up in how my features are delineated or identified...right now its just binary (1 for present, 0 for absent)

Data is here: 
[chin_pu.zip](https://github.com/prioritizr/prioritizr/files/11237336/chin_pu.zip)

Thank you thank you!

**Comment by jeffreyhanson** [comment]
Thanks for sharing your data and explaining all that! 

I had a go at running it on my computer, but I can't reproduce the error you're getting. I've included the code that I used to import the data and run the prioritization. Could you please check to see if I've got something wrong (e.g., maybe you update the columns/data in some way after importing the data)?  It seems to run perfectly fine on my computer, but maybe I'm missing something?

Also, when I import the data from the shapefile, it seems that the columns names have been truncated/abbreviated (possibly because shapefiles have a max limit on the number of characters in a column name), so I had to change `fnames` and the `cost_colunm` to match the column names in the file.

```
# load packages
library(prioritizr)
library(sf)

# load data
pu <- read_sf("chin_pu.shp")

# define variables
target <- 0.26
fnames <- c(
  "cntns_Ct", "cntns_F", "cntn_SL", "cntns_T",
  "cntns_Rd", "cntns_Cm", "cnt_OaG", "cntns_A",
  "cntns_Ps", "cntns_M",
  "cntn_NA", "cntns_Pw", "cntns_Rl"
)

# build problem
p <-
  problem(pu, fnames, cost_column = "NEAR_DI") %>%
  add_min_set_objective() %>%
  add_relative_targets(target) %>%
  add_binary_decisions() %>%
  add_default_solver()

# solve problem
s <- solve(p)
```

``

**Comment by nwallia** [comment]
hi! appreciate you trying to replicate the error and troubleshoot. It turns out that all my feature columns were the "as.numeric" type. So i converted them to integers and the code is running fine! (woohoo!!! but also feeling a bit foolish posting about quite an easy fix)

I did have another question though...mostly looking for feedback or an opinion as to how to set up the model to account for this. 
I have changed the parameters of my model to fulfill as many targets as possible, whilst ensuring that the cost of the solution does not exceed a budget (i.e. max_features_objective) and then using the feature weights to tell the model to preferentially select specific disturbance features (i.e. seismic lines and roads) over others. My cost column has been derived as the distance to good habitat where before, by using the min_objectives argument, the model was set up to select units that are closer to good habitat. Since the max_features argument requires a "budget" I was using the max value in my cost column to derive my budget. However its throwing off my results quite a bit as sometimes its only selecting one or two planning units in areas that are highly disturbed. 

My "targets" are now set up in the initial problem (before I add in the feature weights) to weigh them all the same (i.e. if there are 10 targets, each feature should have 10% representation). However then I add in the feature weights argument etc etc

I'm wondering if you (or others) have any thoughts as to how I could adjust my model? If not, no worries feel free to close the issue as the specific issue I had asked about has been rectified! 

Posting some examples

![w_plot_5](https://user-images.githubusercontent.com/104106108/232636880-6ec57fa7-9711-4647-b391-ca673ad058ee.png)
![w_plot_6](https://user-images.githubusercontent.com/104106108/232636947-e96ff17e-7a86-43c8-9017-7b5a9cc562eb.png)

**Comment by jeffreyhanson** [comment]
Glad to hear you got it working!

Hmm, I'm not sure I understand why it's working after converting to integers. The code should work with `numeric`-type data. Would you mind sharing the R session where it wasn't working (e.g., if you do `save.image('session.rda')`), then that will save everything in your session so I can see exactly what data was being input into prioritizr? For example, I've included some code to convert the feature data into  `numeric`  values -- at the end of the post -- and it seems to work for me? We made a lot of changes from 7.2.2 to version 8, so I'd like to make sure thus error wasn't due to a bug.

Yeah, if you're setting your budget based on the maximum value, then -- unless the highest value is much much much larger than all the other values -- the resulting prioritization probably won't select that many planning units. I would suggest setting the budget as a proportion of the sum of the cost values. For example, you could set a budget as 30% of the total distance values like this:

```
budget <- 0.3 * sum(pu$NEAR_DI)
```

How does that sound?

----

```
# load packages
library(prioritizr)
library(sf)
library(dplyr)

# load data
pu <- read_sf("chin_pu.shp")

# define variables
target <- 0.26
fnames <- c(
  "cntns_Ct", "cntns_F", "cntn_SL", "cntns_T",
  "cntns_Rd", "cntns_Cm", "cnt_OaG", "cntns_A",
  "cntns_Ps", "cntns_M",
  "cntn_NA", "cntns_Pw", "cntns_Rl"
)

# convert data to numeric
pu <- pu %>% mutate_at(fnames, as.numeric)

# build problem
p <-
  problem(pu, fnames, cost_column = "NEAR_DI") %>%
  add_min_set_objective() %>%
  add_relative_targets(target) %>%
  add_binary_decisions() %>%
  add_default_solver()

# solve problem
s <- solve(p)
```

**Comment by jeffreyhanson** [comment]
@nwallia, I just wanted to follow up and ask about the numeric/integer issue? We're planning on releasing an update to CRAN to fix issues in the previous release, but I want to make sure that there isn't some remaining bug/issue that you've found in the latest GitHub/developmental version?

**Comment by jeffreyhanson** [comment]
All good! Thanks for the quick response. Yes, please - could you please send it via email (my email address is on my profile here: https://github.com/jeffreyhanson)? If the attachment is large, it might need to be uploaded to a file hoster (e.g., google drive).

**Comment by jeffreyhanson** [comment]
Thnaks again for sending your data @nwallia! I worked out that the error was happening because one of the feature columns contained `logical` (i.e., `TRUE`/`FALSE) values, and this was fixed when you manually converted data to  to `integer` values. I've put togeather a PR so that prioritizr will provide a more useful error message if/when people run into this in the future.
