### ISSUE TITLE
New presolve check warning: more features are needed on previously feasible problem

### ISSUE THREAD

**Issue by ninzyfb** [prioritizr/prioritizr#286]
Hi Jeff,

I'm getting a weird presolve check warning when running my problems, and I never used to get this before but I have not changed anything. It is telling me most of my PUs do not have a single feature, but when i force = T the solution looks fine to me? I use gurobi as a solver. Ive attached .RDS files for both my cost layer (each PU = 1) and my features (n = 64). Any insights would be much appreciated :) Thanks!

# BASIC CONSERVATION PROBLEM
problem_single= problem(costs,features)%>%
  add_relative_targets(0.5) %>%
  add_max_features_objective(1080) %>%
  add_gurobi_solver()
sol = solve(problem_single,force=T)
plot(sol)
[prioritizr_issue_ninafb.zip](https://github.com/prioritizr/prioritizr/files/11712433/prioritizr_issue_ninafb.zip)

**Comment by jeffreyhanson** [comment]
Hi @ninzyfb,

Yeah, this warning is just saying that many of the planning units have no features present within them. In the worse case scenario, this could potentially mean that "important" planning units are not selected in the prioritization, simply because there isn't enough biodiversity data to identify. It can also cause strange patterns in the prioritizations (e.g. see https://github.com/prioritizr/prioritizr/issues/268, https://github.com/prioritizr/prioritizr/issues/205). So, this warning is designed to help people recognize when they might not have enough features to generate "biologically" meaningful results, but it could be false positive depending what the prioritization is meant to do (e.g. if you care about rare/endemic species, then it doesn't matter if most of the planning units have no features present within them). If your confident that you've got the correct or enough features for your conservation planning exercise, you can safely ignore this warning. In other words, this warning isn't about the mathematical feasibility of the optimization problem, it's more about ensuring the results are informative (sort out like fitting a statistical model with a low degrees of freedom). Does that help?

**Comment by ninzyfb** [comment]
HI jeff, ok great thank you for clarifying, i was worried as usually didnt get this warning but maybe it came with a package updated. It makes sense as my planning area may be slighlty too big considering the extent of the conservaiton features so maybe something to think about for the future.
Thanks!

**Comment by jeffreyhanson** [comment]
No worries! Ok sounds great.
