### ISSUE TITLE
installation of cplexAPI package + re-scaling features data

### ISSUE THREAD

**Issue by fabiofebocastelli** [prioritizr/prioritizr#293]
I'm working on a project that aims to develop alternative scenarios for increasing the strictly protected forest area in the state of NRW, Germany. Using Prioritizr to optimize the alternative solutions, I came across the following issues:

**1.** Sadly I can not download Gurobi at the moment so I opted for CPLEX solver. However, I'm not able to download the cplexAPI package. I followed the instructions [here](https://prioritizr.net/reference/add_cplex_solver.html), first installing the software and then setting the environmental variable. Then, when I run the code:

`if (!require(remotes)) install.packages("remotes")
remotes::install_github("cran/cplexAPI")`

this is what i get:

```
`Loading required package: remotes
Warning message:
package ‘remotes’ was built under R version 4.2.3 
> remotes::install_github("cran/cplexAPI")
Downloading GitHub repo cran/cplexAPI@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\Fabio Castelli\AppData\Local\Temp\RtmpyUd1oo\remotes28c0fe825f1\cran-cplexAPI-3661b93/DESCRIPTION' ... OK
* preparing 'cplexAPI':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking vignette meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'cplexAPI_1.4.0.tar.gz'
Installing package into ‘C:/Users/Fabio Castelli/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'cplexAPI' ...
** using staged installation
** libs
gcc  -I"C:/PROGRA~1/R/R-42~1.1/include" -DNDEBUG -g -D_R_=1 -DUSE_R=1 -I"\cplex\include"    -I"C:/Program Files/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c cplexAPI.c -o cplexAPI.o
In file included from cplexAPI.h:26,
                 from cplexAPI.c:26:
cplexR.h:50:10: fatal error: ilcplex/cplex.h: No such file or directory
   50 | #include <ilcplex/cplex.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-42~1.1/etc/x64/Makeconf:253: cplexAPI.o] Error 1
ERROR: compilation failed for package 'cplexAPI'
* removing 'C:/Users/Fabio Castelli/AppData/Local/R/win-library/4.2/cplexAPI'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/FABIOC~1/AppData/Local/Temp/RtmpyUd1oo/file28c0fce15ed/cplexAPI_1.4.0.tar.gz’ had non-zero exit status`
```

Could anyone give me some support?

**2.** I wanted to give a first try to solve the problem anyway, so I used the HiGHS solver. I got an ERROR related to the values of the features that is hindering me:

```
`Error in `solve()`:
! Problem failed presolve checks.

These failures indicate that numerical issues could stall optimizer or produce incorrect results:

✖ Features must not have target values that are too high (> 1e6).
→ Try re-scaling the feature data (e.g., convert units from m² to km²).`
```

 Apparently, I'm supposed to re-scale the values to lower them, but I'm really not sure how to do it. You can find my script [here](https://github.com/fabiofebocastelli/systematic-conservation-planning/blob/main/Scenario1) In my project on GitHub, you can see the unique values of all my features. They are not high. Maybe the problem is due to the high number of cells of my rasters? or the number of planning units? I don't know how to fix this.

**Comment by jeffreyhanson** [comment]
Hi @fabiofebocastelli,

Thanks for posting your questions here! With regards to them:

1. Just to check, have you installed the IBM CPLEX software? It seems like the cplexAPI R package is having trouble finding it, so my guess is that either IBM CPLEX isn't installed or it can't find where it's installed on your computer. If you have installed IBM CPLEX, then you might need to tell it where it's installed (see https://github.com/cran/cplexAPI/blob/master/inst/INSTALL for instructions).

2. This error message is saying that some of the values in the raster are too high. E.g., some cells have values larger than 1,000,000 (i.e., 1e6). This is not saying that you have too many cells. Sorry, I tried following the link but GitHub says the repo doesn't exist - is it possible that it's a private repo and you might need to make it public? To rescale the values, you could do something like this: `x <-  x / 1000` (or equivalantly, `x <- x * 1e-3`). Broadly speaking, you want all the positive non-zero values to be between 1e-6 and 1e6 (of course, negative and non-zero values are fine too, but this suggested range is specifically for non-zero values). 

How do those suggestions sound? Let me know if that doesn't fix it and I can try and suggest other possible fixes?

**Comment by fabiofebocastelli** [comment]
Dear Jeffrey,

Thanks for your reply! I changed the settings of my repo and you should be able to open it now. 

1. Yes I have installed the software, in particular the version CPLEX Studio IDE 22.1.1. Maybe my modification of the Makevars.win file is not correct. I downloaded the cplexAPI package from [here](https://cran.r-project.org/src/contrib/Archive/cplexAPI/). Assuming that my two paths are :

"C:\Users\Fabio Castelli\Programmi\IBM\ILOG\CPLEX_Studio2211\cplex" for 'CPLEX_STUDIO_DIR' and
"C:\Users\Fabio Castelli\Programmi\IBM\ILOG\CPLEX_Studio2211\cplex\examples\x64_windows_msvc14" for 'CPLEX_STUDIO_LIB', what should be the new content of the Makevars file?

2. The values of my features don't seem to be high, I don't understand that. You can check all the unique values in my repo. 
My relative targets are aiming to force the solution in order to meet a certain share of area for different features.

Thanks,
Fabio

**Comment by ricschuster** [comment]
Hi Fabio,

I can way in on 1. as it looks like you are on a Windows machine. I have wrangled with the clpexAPI package installation on Windows quite a bit over the last couple of years and have only been successful to get it to work a couple of times (I currently don't have a working version for Windows on the machine I am on). I can try again over the next couple of days and let you know if I find a solution. 
What I usually do now (on Windows machines) is run the Windows Sybsystem for Linux (WSL; https://learn.microsoft.com/en-us/windows/wsl/install) and install CPLEX there. Depending on your comfort level with Linux, that could be an option.

**Comment by fabiofebocastelli** [comment]
Hi Richard,

Thank you very much for your reply. Sadly I've never used Linux so I don't feel very comfortable with that. 
Yes, I'd appreciate it if you could give me some suggestions on how to install the clpexAPI package in Windows.

Thanks!
Fabio

**Comment by ricschuster** [comment]
> Hi Richard,
> 
> Thank you very much for your reply. Sadly I've never used Linux so I don't feel very comfortable with that. Yes, I'd appreciate it if you could give me some suggestions on how to install the clpexAPI package in Windows.
> 
> Thanks! Fabio

You are welcome and sounds good. I will dig around a bit and get back to you on clpexAPI on Windows.

**Comment by fabiofebocastelli** [comment]
Amazing, thank you very much! Next week I'll be in Italy and finally be able to download also Gurobi (in order to download it for free you have to be connected to your university network but I'm currently doing a traineeship of 6 months at the European Forest Institute in Bonn, Germany). Though, I'm not sure if once installed it in Italy I'll be able to use it also without the connection to my university network once I'm back in Germany, by any chance do you know it?

**Comment by edwardsmarc** [comment]
> Amazing, thank you very much! Next week I'll be in Italy and finally be able to download also Gurobi (in order to download it for free you have to be connected to your university network but I'm currently doing a traineeship of 6 months at the European Forest Institute in Bonn, Germany). Though, I'm not sure if once installed it in Italy I'll be able to use it also without the connection to my university network once I'm back in Germany, by any chance do you know it?

Hi @fabiofebocastelli, in my experience you will need to be connected to you academic network to download the free gurobi academic license. But once you have it it just sits on your laptop, you don't need to be on the network to use it.

**Comment by jeffreyhanson** [comment]
Thanks @edwardsmarc and @ricschuster!

@fabiofebocastelli, sorry, I haven't installed cplexAPI on a Windows computer before. Given those paths, my guess would be to change the `Makevars.win` file so that it has the following:

```
PKG_CPPFLAGS=-g -D_R_=1 -DUSE_R=1 -I"C:\Users\Fabio Castelli\Programmi\IBM\ILOG\CPLEX_Studio2211\cplex\include"
PKG_LIBS=-L"C:\Users\Fabio Castelli\Programmi\IBM\ILOG\CPLEX_Studio2211\cplex\examples\x64_windows_msvc14" -lm -lcplex12100
```

That said, I'm not sure if "C:\Users\Fabio Castelli\Programmi\IBM\ILOG\CPLEX_Studio2211\cplex\examples\x64_windows_msvc14" would be the right path, because suggests that it contains examples? I would have expected the folder PKG_LIBS folder to contain exe or dll files for running IBM CPLEX - so if that doesn't work, maybe try some other folder paths and see if that works?

**Comment by jeffreyhanson** [comment]
@fabiofebocastelli - thanks so much for sharing the code. 

Sorry, I now realize that I misread the original error message. It's actually saying the target values are too high - after prioritizr converts them from proportions to "absolute" units. For example, if you have 3 planning units with the values 1, 2, and 4 for a species and set a 0.1 relative target, then you are effectively setting an absolute target of 0.7 (`=(1+2+4)*0.1`). Since you have a lot of planning units (i.e., 811,930), even though the pixel values are very small (e.g., <100), the target values can be very high because it involves summing togeather lots of small values (e.g., if you have 400,000 planning units with a value of 30, then `30 * 400000 = 12,000,000`). 

So, I would normally suggest rescaling the values of rasters with values that aren't binary (i.e. 0 or 1). For example, I see the `forest_habitat_types_reclas_25832` has values betwen 1 and 27, so you could try re-scaling them. However, I'm not sure if that's the correct approach here, because it seems that different pixel values (e.g., 1 vs 2 vs 3, etc) in this raster are meant to indicate different types of forest habitat? If so, I would suggest converting this single-layer categorical raster into a multi-layer binary raster, so that you can set seperate targets for each class to ensure that each class is adequately represented by the prioritization. E.g., see the `binary_stack()` function to help with this (https://prioritizr.net/reference/binary_stack.html). Maybe this is also relevant for the TFC raster? What do these values mean? It seems to only have 3 distinct values?

Sorry, I feel like this isn't very helpful - I've only followed up your questions with more questions. Please let me know if anything I've written isn't clear?

**Comment by ricschuster** [comment]
Hi @fabiofebocastelli,
Related to CPLEX and Gurobi: do you have VPN access to your university? 
If you do, its really straight forward to install an academic Gurobi license and you would not have to bother with CPLEX. 
Every university is a bit different, but here are the instructions for my home university as an example: https://carleton.ca/its/help-centre/remote-access/

**Comment by ricschuster** [comment]
That's too bad about VPN access. Unless you have an affiliation with another university you usually can't get access to their VPN.
I do find it strange that your university wouldn't give out VPN access, especially with what we just went through related to Covid.

**Comment by jeffreyhanson** [comment]
@fabiofebocastelli - thanks so much for providing that background info on your project and explaining what the different pixel values mean.

Yeah, I agree, I think the "correct" way to handle these datasets comes down to your goals/objectives. In systematic conservation planning, there's 4 core concepts that are generally used to guide prioritizations to help them conserve biodiversity: _comphrensiveness_ (protected areas should aim to secure a broad range of biotic elements, e.g., different habitat types, different types of species), _adaquacy_ (protected areas should aim to secure a sufficient amount of habitat/populations/individuals for each biotic elements), _representatitiveness_ (protected areas should aim to secure all levels of biodiversity, e.g., realms, bioregions, ecoregions, species, genes), and _efficiency_ (protected areas should ideally minimize expenditure and opportunity costs) (e.g., see https://doi.org/10.1111/brv.12008 for more info). Since you're just looking at forests, then it's clear that some of these concepts might not apply (e.g., _representativeness_). 

I (personally, others might disagree) say that it would be worth trying to incorperate the remaining concepts if they make sense. For instance, you're using targets to get at the _adequacy_ concept and you're minimizing costs in the problem formulation to get at the _efficiency_ concept. If you're interested in conserving biodiversity in some form (and not simply just trying get more trees in conservation areas), then I think it would be useful to try and incorperate the _comprehensiveness_ concept into the prioritization. To achieve this, you could turn the `fht` and `TFC` layers into binary stacks that indicate the presence/absence of different forest habitat types and also different forest types. This will ensure that the prioritization secures different forest types, and doesn't simply "double-up" on forests in the cheapest planning units (in other words, put 90% of the priority areas in places with the cheapest forests). <sup>1</sup> However, if you don't care about biodiversity at all and ONLY care about total forest cover, then I would recommend excluding these layers from the prioritization since they don't relate to your goals/objectives. Either way, I wouldn't recommend including layers where the pixel values correspond to different classes. If the pixel values corresponded to some continuous metric -- such as carbon sequestration potential -- then that would be ok.

Also, regarding the scenarios, I wonder if the problem formulations could be updated to better align with your objectives/goals? Based on "My target in the 1st scenario is to reach a fixed area of new PAs only with state forests", it sounds like you're saying something like "we want to identify priority areas for new protected areas within state forests", meaning that some state forests might be priority areas, and all places that are not state forests cannot be priority areas. Is that right? If so, rather than locking in state forests -- which means that all state forests would be selected as priority areas -- I would suggest locking out places that are (i) not state forests and (ii) not within PWA. Also, since you've got a clear idea on a budget, it might be more helpful to use a budget-limited objective (e.g., min shortfall, https://prioritizr.net/reference/add_min_shortfall_objective.html), which aims to get as close as possible to meeting as many targets as possible given a budget. The issue with the min set objective here is that if it's not possible to meet the targets given the budget, then you'll get an error about problem feasbility because there's no valid solution that would meet the targets given the budget. E.g., something like this for scenario 1:

```
# prepare data
pwa_or_spa <- as.int((pwa > 0.5) | (existing_spa > 0.5))
not_state_f_and_not_locked_in <- as.int((state_f < 0.5) & (pwa_or_spa < 0.5))
constant_costs <-  (state_f * 0) + 1 # create a raster with ones in all cells

# create problem
p1 <- problem(constant_costs, cons_feat_1) %>% 
       add_min_shortfall_objective(budget = 52351) %>% 
       add_relative_targets(targets) %>% 
       add_locked_in_constraints(pwa_or_spa) %>% 
       add_locked_out_constraints(not_state_f_and_not_locked_in)
```

Here, we are locking in PWA and SPA, because they are already protected areas. By locking them in, we can ensure that any of the progress made towards meeting the targets by existing protected areas will be accounted for in the identification of priority areas. E.g., if existing protected areas are already capturing 99% of the first forest class in `fht`, then priority areas might not need to get any more of this forest class and should instead focus on meeting targets for the other features. Since you mentioned that the costs values are a bit arbitrary (i.e., setting values of 25 and 100 based on whether they are damanged or not), I would recommend just assuming constant costs since this kind of arbitrariness can have a huge impact on solutions and can cause issues during review (e.g., see https://doi.org/10.1111/cobi.12051). Another approach could be to use the human footprint layer (or another layer describing human pressure) as a surrogate of cost (this is commonly done when land valuation data aren't readily available).

How does that sound? Please let me know if you've got any follow up questions?

<sup>1</sup> Note that if you just include the layers as is -- with different pixel values corresponding to different classes -- the prioritization process won't actually secure different forest types. This is because the targets work by saying you want a proportion of the sum of the values represented in the prioritization. So, for example, if you had 5 planning units, and 2 forest classes indicated by the pixel values 1 and 2, such that the pixel values in the planning units were: `{1, 2, 2, 1, 2}` and set a 10% target, then the solution `{0, 0, 1, 0, 1}` would meet the 10% target because: `(0*1) + (0*1) + (1*2) + (0*1) + (1*2) >= ((1 + 2 + 2 + 1 + 2) * 0.1)` . As we can see, this solution is not great because it only selects planning units that contain class 2 and ignores class 1 completely. Instead, we need to update the single-layer categorical raster so that it is a multi-layer binary presence/absence raster so that we can set speerate targets for each class.

**Comment by jeffreyhanson** [comment]
> * Yes, my idea was to include the _comprehensiveness_ concept considering `fht` as a presence-absence layer but I didn't know how to frame it; here, very illuminating both your suggestion to turn it into binary stacks and your note1.

Ah - awesome! Glad to hear it makes sense.

> * I'm not sure about your suggestion "since you've got a clear idea on a budget, it might be more helpful to use a budget-limited objective". Actually, I am not considering any given monetary budget here. For reasons related to local social conditions and regulations, we are assuming that setting aside highly damaged forest stands would lead to weaker trade-offs (e.g., some private owners may no longer consider those damaged stands economically profitable). Therefore, we want the software to consider it more advantageous to include those unit cells in the solution, by giving a certain level of priority to them. The limitation (both minimum and maximum) should be determined by the main spatial target of reaching a specific surface area of priority areas to achieve exactly a total of 10% of total forest cover. Without exceeding this limit or falling below it. Hence, my idea is to frame it this way: "Meet the targets at the minimum cost" with `add_min_set_objective()`. Maybe I am missing something? Did I accidentally set a budget someway?

Ah, sorry, I think I could have been clearer in my previous message. By "clear idea on a budget", I meant that you have a 10% area based contraint. This constraint is effectively a budget, wherein the cost units are area of each planning unit instead of acquisition cost. So, I was thinking it might be more useful to treat this threshold explicitly as a budget? Thanks for providing more detail on the damanged forest stands. To account for them, I would suggest it might be worth updating the feature values instead of the cost values. E.g., if you think a highly damaged forest has 10% of the "value" of an intact (non-damaged) forest, then pixel values for the binary feature rasters (e.g., each of the classes in the `fht`  raster) could be updated such that: a pixel value of 1 means that `fht` class is present and has intact forest, a value of 0.1 means that the `fht` class is present and has dmaanged ofrest, and a value of 0 means the class is absent. This way the optimization process either needs to get A LOT of damaged forest to meet the targets, which would probably require a lot of area. In other words, I would suggest updating the feature data so that the pixel values describe the "expected benefit" for each feature (e.g. habitat class), so if some planning units have a lower benefit than others (e.g., because they contain damaged forest), then they should have lower pixel values. How does that sound?

> * SPA is the only layer for existing strictly protected areas, whereas PWA are the potential wilderness areas available for future measures, according to [Brackhane et. al 2019](https://www.sciencedirect.com/science/article/abs/pii/S000632071831766X). So, I want to consider the latter only as a spatial constraint, by giving priority to state forests within those areas. Since that area won't be enough, it'll be necessary to consider also state forests outside PWA, setting high boundary constraints to increase the clumpiness around the core areas within PWA. Does it make sense to you?

Ah,  thanks for explaining that. Yeah, that make sense! I suppose locking in all potential wilderness areas might be an issue if some potential wilderness areas don't not contain any forests, and so you'd be locking in planning units that would't neccesarily be a priority given the objectives? But that might not be an issues if all potential wilderness areas contain forests?

> * Sorry, what do you mean by "assuming constant costs"? Setting the same cost for all the cells?

Yeah, that's right. Specifically, I mean setting all cost values to 1.

**Comment by jeffreyhanson** [comment]
I'll close this issue due to lack of activity, but @fabiofebocastelli please feel free to re-open this if you have any further questions on this topic.
