### ISSUE TITLE
maxcovr: maximum covering location problem

### ISSUE THREAD

**Issue by njtierney** [prioritizr/prioritizr#3]
This looks like a great package, Jeff!

I've been writing a package, [maxcovr](http://www.github.com/njtierney/maxcovr), which helps solve the [maximal covering location problem](http://onlinelibrary.wiley.com/doi/10.1111/j.1435-5597.1974.tb00902.x/abstract). Not sure if that could be useful to you, but just thought I'd let you know in case you want to use code or import things from there.

On a somewhat related note, is it me, or is there not a dedicated modern R package for calculating distances between points and other distance related tasks ?

**Comment by jeffreyhanson** [comment]
Yeah, it should be really useful. 

Thanks for the links. Yeah, maxcovr looks really cool! We're focusing on minimum set cover and maximum coverage problems for the moment - but there might be a few optimization-related things we could import.

Not to my knowledge. I generally use [vegan::vegdist](https://rdrr.io/cran/vegan/man/vegdist.html) for calculating dissimilarity indices (eg. Bray-curtis, Manhattan, etc). I also use [fields::rdist](https://rdrr.io/cran/fields/man/rdist.html), and [fields::rdist.earth](https://rdrr.io/cran/fields/man/rdist.earth.html) for Euclidean and great circle distances. I find `fields::rdist` better then `dist` because you can have it compute distances between two matrices of coordinates,  rather than distances between all points in a single matrix.

**Comment by njtierney** [comment]
Thanks! Please feel free to borrow code that might be of any use from `maxcovr`. I'd say at the moment it's about 50% complete. The code works, but I want the API to be really slick and fit in nicely with the tidyverse.

I have a couple of distance related functions in `maxcovr`, for example `spherical_distance` (borrowed from `rnoaa`), and `nearest`, `nearest_facilist_dist`,  for finding nearest points and returning a dataframe, and also calculating distance matrices from dataframes. I'll see if I can tidy up some of the documentation to make the tasks in maxcovr a bit clearer, but [here's a start](http://www.njtierney.com/maxcovr/reference/index.html)

I haven't worked much with spatial data, but it seems like a lot of them require matrices to work, which might disrupt workflow, since the "modern/tidy" approach is all about that dataframe. 

So, I wonder if there might be a little niche space for a specific R package that takes dataframes with lat/long (or other specified co-ords from diff transformations)? Another package that sorta encapsulates some of these ideas is [`widyr`](https://github.com/dgrtwo/widyr).

**Comment by jeffreyhanson** [comment]
Thanks again posting this. I'm closing this to clear up the issue tracker.

**Comment by njtierney** [comment]
No worries. I should be able to make `maxcovr` public soon, would be great to submit it as a paper say in JSS sometime next year if you have time!
