### ISSUE TITLE
Categorical `SpatRaster` layers break problem creation

### ISSUE THREAD

**Issue by Martin-Jung** [prioritizr/prioritizr#313]
Happy new year!

Maybe a little bit random as I discovered this by accident, but there is a bug in the current stable built that got introduced when creating a new `problem()` using categorical rasters as features. This occurred to me as in cases binary thresholded SDMs are created. 

**Reproducible example:**
```

library(prioritizr)
library(prioritizrdata)

# import planning unit data
wa_pu <- get_wa_pu()
wa_features <- get_wa_features()

# Take a feature and convert to a dummy categorical (thresholded) layer
feat_cat <- wa_features[[1]]
feat_cat[feat_cat<0.2] <- 0
feat_cat[feat_cat>0] <- 1
feat_cat <- terra::as.factor(feat_cat)

# Plot
plot(feat_cat)

# Compare agains toriginal
terra::cats(wa_features)[[1]]
terra::cats(feat_cat)[[1]]

# create problem
p1 <- problem(wa_pu, features = feat_cat)
```
> Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': invalid type "character" in 'R_matrix_as_sparse'

**Possible Solutions:**
- Add another unit test to the package via `terra::is.factor()` or `terra::cats()`
- Run a `as.numeric` on all features by default which solves this issue
- Accept categorical data as input for sparse matrices (sensu additional checks for inputs).
- (Optional eye candy) Support categorical rasters throughout the package as default for inputs and outputs (e.g. `add_binary_decisions()` solutiond).

**Comment by jeffreyhanson** [comment]
Hey,

Happy new years! Thank you very much for raising this issue! I imagine this could be confusing for a new user that's familiar with categorical rasters (honestly, I had no idea categorical rasters existed). I think the best option might be to either (1) convert them automatically to numeric rasters (using `as.numeric()`), or (2) throw a clear error saying that categorical rasters are not supported and tell the user to convert them manually.

Can you think of any issues/situations with (1) (i.e., using `as.numeric()`), where prioritizr might automatically convert a categorical raster to a numeric raster and, as a consequence, produce an output that doesn't align with the users intent? For example, imagine if a user has a categorical feature raster wherein different pixel values/classes correspond to different ecosystem types, then each pixel value is a different feature. In this case, I imagine using `as.numeric()` automatically in prioritizr would result in prioritizr incorrectly proccessing the data. This is because using `as.numeric()` would produce a single integer layer, when the user actually needed multiple binary layers so each ecosystem type is represented as a different feature. Is that right? Or maybe I'm misunderstanding something?

**Comment by ricschuster** [comment]
I personally would go with (2) and throw a clear error. Option (1) makes assumptions that might not be correct and I think it would be better if users need to think about what to do rather than the package assuming what a user might want.

What do you think?

**Comment by Martin-Jung** [comment]
No specific preference for either option.
**Conversion factor to numeric 1):**
Mhh, there could be potentially issues in this if a user has for some reason differently labelled categories that do not align with the numeric values. For example:
```
a <- c("1", "3", "4") |> as.factor()
as.numeric(a)
```

So in that case I agree with Richard and think option 2) (assert_that call checking whether categorical rasters are supplied throughout) would be preferable.

**Comment by jeffreyhanson** [comment]
Ok sounds great - thanks @ricschuster and @Martin-Jung! I'll update prioritizr to throw errors if a user supplies a categorical raster.
