### ISSUE TITLE
How should I incorporate a risk layer? Penalty, feature, feature weight?

### ISSUE THREAD

**Issue by KWB4484** [prioritizr/prioritizr#315]
I'm trying to generate illustrative examples on how prioritization differs when considering only biological value, verus considering cost, risk, and biological value. But I'm not certain I'm doing it the right way. I'm getting a little confused about if a risk layer should be a penalty or a feature, or maybe even a feature weight (but doesn't work with `add_min_set_objective()` so I won't attempt that here).  

I have units (raster cells) with cost estimates (COST), a feature layer of bird abundance (BIRD), and a risk layer representing future grassland loss (RISK).

Suppose I'd like to solve the following problems (with my take on it below).
1- Cost is constant and prioritize units that represent the top 20% of a bird abundance feature. 
```
COST_0<-round(COST*0+1)#constant cost
p1 <- problem(COST_0, BIRD) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_binary_decisions() %>%
  add_default_solver(gap = 0.1)
```
2- Minimize cost, and prioritize the top 20% of bird abundance in areas of low predicted future grassland loss.
```
#penalty for high risk, avoiding high grassland loss areas
p2 <- problem(COST, BIRD) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_binary_decisions() %>%
  add_linear_penalties(c(1), RISK) %>%
  add_default_solver(gap = 0.1)

#or as feature using the "inverse" of loss values?
max<-as.integer(global(RISK, "max", na.rm=TRUE))#get max value
RISK_inv<-abs(RISK-max)#subtract and get absolute
feats<-c(BIRD,RISK_inv)
p3 <- problem(COST, feats) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_binary_decisions() %>%
  add_default_solver(gap = 0.1)
```  
3-Minimize cost and prioritize top 20% of bird abundance in areas of high predicted future grassland loss.

```
#penalty for low risk, avoid low grassland loss areas using "inverse" of loss values?
max<-as.integer(global(RISK, "max", na.rm=TRUE))#get max value
RISK_inv<-abs(RISK-max)#subtract and get absolute
p2 <- problem(COST, BIRD) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_binary_decisions() %>%
  add_linear_penalties(c(1), RISK_inv) %>%
  add_default_solver(gap = 0.1)

#or as feature?
feats<-c(BIRD,RISK)
p3 <- problem(COST, feats) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_binary_decisions() %>%
  add_default_solver(gap = 0.1)
```

**Comment by jeffreyhanson** [comment]
Hi,

Thanks so much for providing all this detail - its really helpful for me to understand exactly what you're asking! 

Yeah, you're exactly correct - there are a few different approaches for handling risk. Each of these approaches has some advantages and disadvantages that are worth bearing in mind.  I'll briefly cover them below, but let me know if you want more detail?

* **Linear penalties (`add_linear_penalties`):** You could account for risk using linear penalties. This basically says that you're willing to sacrifice level of solution quality according to your primary objective (e.g., cost if using min set objective), so that you can do better according to a secondary objective (i.e. penalty). I would say the advantage of this approach is that it's fairly easy to explain/understand. However, I would say the disadvantage is that you need to specify a `penalty` parameter to say how important the secondary objective is relative to the primary objective. For example, if `penalty = 0`, then the optimization process doesn't care at all about the secondary objective, and if `penalty = infinity`, then the optimization process doesn't care at all about the primary objective. Given this wide range of potential `penalty` values and the fact that the units for the `penalty` value don't mean anything intutive (e.g., it's not a percentage), it can be difficult to find a good `penalty` value that represents a good comprimise between the primary and secondary objective (but see the details on the "Blended approch" in the calibrating trade-offs tutorial for some suggestions, https://prioritizr.net/articles/calibrating_trade-offs_tutorial.html#blended-approach). As such, I generally avoid this approach.

* **Locked out constraints (using `add_locked_out_constraints()`):** This approach involves locking out planning units that have "unacceptably" high risk values, so they won't be selected by the prioritization. To implement this approach, you'd (1) select a threshold risk value (e.g., 50th percentile), (2) use the threshold to convert the risk layer into a binary layer with 1s and 0s (0s = places with acceptable risk, and 1s = places with unacceptably high risk), and (3) use the binary layer in the problem formulation with `add_locked_out_constraints()`. The advantage with this approach is that it's easy to communicate and implement. The downside is that, in practice, you'll generally only be able to generate solutions that exclude places with very very high risk values. This is because if you have some features that only occur in the high risk areas and you're using the the min set objective, then you won't have a feasible problem unless the risk threshold is very high (because otherwise you're locking out the only planning units where certain features are found, resulting in infeasibility).

* **Updating feature data using the risk data:** This approach basically is a more complicated version of the previous approach and involves setting a different threshold for each feature. Specifically, you (1) calculate the feature targets using the raw/original feature data as absolute numbers (e.g., `terra::global(features, "sum", na.rm = TRUE)[[1]] * 0.1` to calculate absolute targets for securing 10% of each feature); (2) for each feature, overlay the risk data with the feature data and set a risk threshold for each feature (e.g.,  for a given feature, the 10th percentile of risk values found in planning units with the feature occurs), (3) use those risk thresholds to create a series of binary risk layers (one for each feature), (4) mask/multiply each risk layer by the respective feature data to set feature values to 0 in places where the risk values are greater than the risk threshold calculated for the given feature, (5) use the updated feature data in the prioritization, and (6) set the absolute targets for the prioritizaiton based on targets you calculated in the first step. The advantage with this approach is that it can be applied to a broader range of risk thresholds than the previous approach (e.g., you could explore low, medium, and high risk scenarios, instead of just locking out very very high risk planning units). However, the disadvantage is that it can be a bit challenging to implement. This is because, you'll need to write the codoe to do the thresholding and data pre-processing.

* **Linear constraints (`add_linear_constraints)`:** Another approach is using linear constraints. E.g., with your examples above, you could use `add_linear_constraints(RISK, sense = "<=", threshold = th)`, where `th` is some threshold number (e.g. 10). This is saying that the total sum of the `RISK` values in selected planning units must be less than, or equal to, the `th` variable. The advantage with this approach is that the `threshold` parameter is in the same units as the risk layer. This makes it a lot easier to set meaningful threshold values, and means that you don't need to run such an extensive parameter calibration procedure (compared with the linear penalty approach) -- but you'll likely still need to do some parameter calibration and try out a few values. For example, you could set the threshold as 10% of the sum of the risk values (e.g., something like `terra::global(RISK, "sum", na.rm = TRUE)[[1]] * 0.1`), or you could use expert understanding of data to set the threshold (e.g., maybe the expert says that a total value higher then 80 is really bad). The disadvantage of this approach is that the solution(s) might be sensitive to the threshold value, and it's a bit more complicated to explain to people (e.g., you could think of it as a budget for risk, where you not willing to spend more "risk points" than a certain threshold value). Also, the key difference between this approach and the locked out approach and update feature approach is that this approach looks the the overall risk across the prioritization, whereas the other approaches aim to ensure that each and every planning unit has an acceptable level of risk. For example, this approach might generate a solution that represents a feature only in planning units that have high risk, whereas the other approaches wouldn't do this (depending on the risk thresholds you set). It's also worth noting that this approach (broadly speaking, of course depends on the risk thresholds used) is likely to generate less costly prioritizations that the update feature approaches, because it isn't effectively removing lots of planning units from consideration for particular features (which is what setting the feature values to 0 does).

* **Hierachical optimization** This apporach involves using hierachical optimization to account for risk. Unlike the other approaches, this approach involves generating two prioritizations. You first generate a preliminary prioritization and then use some information from it to generate the real/final prioritization that actually accounts for risk. For the min set problem formulation, this approach involves (1) generating a prioritization that doesn't account for risk, (2) calculating the cost of the prioritization, (3) calculate how much extra you're willing to pay to minimize risk (e.g., you might be willing to pay an extra 20% of cost to reduce risk, so multiply the cost of the first prioritization by 1.2), (4) generate a second prioritization with a similar formulation to the first prioritization, with the following differences (i) cost values set as the risk values and a (ii) linear constraint parametized using the cost data, a "<=" sense, and the threshold set set based on step 3. Personally, this would be my favorite approach. This approach has the advantage that the trade-off parameter is calculated as a cost-based percentage - meaning that it's easy to select a reasonable trade-off parameter (e.g., unlike relying on arbitrary values between 0 and infinity, or percentile thresholds where it's not clear what influence this will have on the prioritization, e.g., we don't know ahead of time whether a 10th percentile will increase total cost of the prioritization by a lot or not much at all) and communicate results to others.  The downside is that this more complicated to implement than the other approaches, and describing the methods is also a bit more complicated. For some examples with this, the calibrating trade-offs vignette shows an example of hierachical optimization to calibrate boundary penalties and this could be apadated for use with risk data (by setting the risk values as cost data, instead of using boundary penalties).

How does that sound? Let me know if you have any questions? Also, let me know if you'd like some examples of papers that implement these approaches and I can update the post with some links?

**Comment by KWB4484** [comment]
Hi Jeffrey -- 

Wow, thank you so much for the detailed response! You've given me plenty to think about. I do have a few follow up questions. One thing I attempted, that you didn't list as a way to incorporate risk, is to include it as a feature with the bird. I just want to confirm that this is a poor choice. Is this not recommended because it would prioritize areas that would focus more on risk than the bird? 

I like the first and last approach. 

For the first approach you mentioned exploring a good penalty value. But in my case, the penalty is a raster that indicates the amount of grass (ha) predicted to be converted to cropland in the next 20 years. So the penalty would be those values. Are you suggesting that I explore different scaling values for the penalty raster? Since the penalty is not a fixed value like it is for boundary constraints I think this is the only option, unless I'm missing something.  

For the last suggestion, I just have a couple questions for clarity. For step "(i)" the risk values become the cost values, as in `p1<-problem(RISK,BIRD)`?  And, is it necessary to increase the total cost threshold for the linear constraint part (e.g., cost*1.2)? If so, I don't understand why. It seems like one could spend the same amount but minimizing risk would provide a different answer, but again, maybe I'm missing something. 

If you have papers for the first and last implementations for incorporating risk into a problem I'd appreciate that too. Very kind of you to offer. Thanks again for your consideration of my question and kind response. It's a great package -- huge utility....and I'm enjoying learning it :-)

Best,
Kevin Barnes

**Comment by ricschuster** [comment]
Hi Kevin,

One example for the hierarchical implementation is our recent paper here: https://conbio.onlinelibrary.wiley.com/doi/full/10.1111/cobi.14048

Code and data are here: https://osf.io/e2fuw/
Please let us know if you have questions about this approach or run into issues with the code.

**Comment by jeffreyhanson** [comment]
> Wow, thank you so much for the detailed response! You've given me plenty to think about. I do have a few follow up questions. One thing I attempted, that you didn't list as a way to incorporate risk, is to include it as a feature with the bird. I just want to confirm that this is a poor choice. Is this not recommended because it would prioritize areas that would focus more on risk than the bird?

No worries! Yeah, although you could include inverse risk as feature (with `>=` targets), I don't think this will neccesarily achieve the desired result. This is because, with the min set objective, you'll be specifying that the prioritization must select planning units with some total measure of inverse risk. In other words, specifying that the prioritization should select some areas with low risk. It doesn't neccesarily mean that the prioritization will avoid planning units with high risk - which I think is the main goal? This is because the prioritization could select some planning units with low risk to meet the feature's targets (i.e., high inverse risk) and also select a whole lot of planning units with high risk (i.e., low inverse risk) as needed to cost-effectively meet the other feature's targets.

> For the first approach you mentioned exploring a good penalty value. But in my case, the penalty is a raster that indicates the amount of grass (ha) predicted to be converted to cropland in the next 20 years. So the penalty would be those values. Are you suggesting that I explore different scaling values for the penalty raster? Since the penalty is not a fixed value like it is for boundary constraints I think this is the only option, unless I'm missing something.

Yeah, that's correct, you'll want to try different `penalty` (scaling) values when using the `add_linear_penalties()` function. This is because the overall objective function  will be: `min: [total cost of selected planning units] + (penalty *  [total risk of selected planning units])`. As such, it's important to find a good `penalty` value, so that the prioritization doesn't focus too much on the cost or too much on the risk.
 
> For the last suggestion, I just have a couple questions for clarity. For step "(i)" the risk values become the cost values, as in `p1<-problem(RISK,BIRD)`?

Yeah that's correct.

> And, is it necessary to increase the total cost threshold for the linear constraint part (e.g., cost*1.2)? If so, I don't understand why. It seems like one could spend the same amount but minimizing risk would provide a different answer, but again, maybe I'm missing something.

It's not neccesary. You could set the cost threshold as the total cost for the preliminary prioritization. This would mean that you want to keep the cost optimal, and also minimize risk as much as possible whilst ensuring the cost is optimal. The issue with this, however, is that you might not be able to reduce risk very much whilst ensuring that the cost is optimal. So, if you relax the cost threshold (by increasing it, e.g., by 10%, 20%, etc) this gives the optimization process more wiggle room to reduce risk (but at the trade-off of slightly more costly solutions). If you think the cost is the number one most important criteria, then you could definitely set the threshold as the cost total of preliminary prioritization - but note that you might get much of a different solution.
 
> If you have papers for the first and last implementations for incorporating risk into a problem I'd appreciate that too. Very kind of you to offer.

No worries! I'll add in some links in a minute to the previous post. Also, thanks for including those links @ricschuster, I'll add that paper into that previous post as well, so any future readers can easily find it.

> Thanks again for your consideration of my question and kind response. It's a great package -- huge utility....and I'm enjoying learning it :-)

Happy to help! Thanks for the kind words.

**Comment by jeffreyhanson** [comment]
@KWB4484, I just wanted to ask if you had any other questions? If not, shall we close this issue?

**Comment by KWB4484** [comment]
Hi Jeff --

Please feel free to close it. The information you've provided has been very
helpful -- I'm super grateful for the time you've spent considering my
questions and providing clear simple input on various methods. Thanks so
much!

**Comment by jeffreyhanson** [comment]
No worries - happy to help!
