### ISSUE TITLE
Optimization Suggestion: Excessive Memory Usage during Processing

### ISSUE THREAD

**Issue by wk-ai** [prioritizr/prioritizr#321]
Hi Jeff,

I hope this message finds you well. I've been using the prioritizr R package in R 3.4.2 , and I've encountered an issue regarding excessive memory usage during the processing of relatively small input data.

Despite input data sizes being less than 2GB, the project is consuming over 25+GB of memory during runtime, which exceeds the available memory on my machine. This has led to interruptions in the computation process due to memory exhaustion.

Upon reviewing my usage pattern, I'm wondering if there might be potential optimizations that could be made within the project itself to address this issue. Specifically, I'd like to inquire if adjustments can be made to better accommodate scenarios where memory resources are constrained.

I'm reaching out to seek your guidance on whether my usage pattern is incorrect or if there are optimizations that can be implemented within the project itself to mitigate this issue. Any insights or recommendations you could provide would be greatly appreciated.

Thank you for your attention to this matter, and for your dedication to maintaining such a valuable project on GitHub.

Best regards,
wk

**Comment by wk-ai** [comment]
Hi Jeff, 

Thanks for your quick reply!

The following is the information of my problem:
print(p2)
A conservation problem (<ConservationProblem>)
├•data
│├•features:    "bio_rich_n6.tif", "carbon_store1.tif", "NEP.tif", "SC_2018_n.tif", and "water.tif" (5 total)
│└•planning units:
│ ├•data:       <SpatRaster> (9187864 total)
│ ├•costs:      constant values (all equal to 1)
│ ├•extent:     -2579302.3166, 2366585.8284, 2092697.6834, 6385585.8284 (xmin, ymin, xmax, ymax)
│ └•CRS:        China_Lambert_Conformal_Conic (projected)
├•formulation
│├•objective:   minimum set objective
│├•penalties: 
││└•1:          boundary penalties (`penalty` = 0.003, `edge_factor` = 0.5, …)
│├•targets:     relative targets (between 0.5 and 0.5)
│├•constraints: 
││└•1:          locked out constraints (948588 planning units)
│└•decisions:   binary decision
└•optimization
 ├•portfolio:   shuffle portfolio (`number_solutions` = 1, …)
 └•solver:      gurobi solver (`gap` = 0.01, `time_limit` = 2147483647, `first_feasible` = FALSE, …)
# ℹ Use `summary(...)` to see complete formulation.

**Comment by jeffreyhanson** [comment]
No worries! 

Ok, it looks like you've got a lot of planning units (9 million). This is a pretty large-scale problem and will require a really good system to solve (e.g., most prioritizations use between 30k -- 1 million planning units). So I think that's the reason as to why prioritizr/R is taking up so much memory. What resolution are your data at the moment? The easiest way to address this would be resample/aggregate the data to a coarser scale (e.g., if you have 10x10 m planning units, you could try 1x1 km planning units). Is that possible? How important is it to generate the prioritization at your current scale? If that's not possible, it might be possible to generate a prioritization with the 9M planning units, but you'll likely need to get a computer/system with 150GB+ disk space, drop the boundary penalties, use the `node_file_start` parameter for Gurobi, and wait at least several days for it to run.

In general, I wouldn't recommend using boundary penalties if you have more than 250k planning units (unless spatial fragmentation is really important to your study, and you have a really, really good computer/system), because they substantially increase the complexity/size of the optimization problem. So, I'd suggest dropping the boundary penalties and seeing if you can solve it without them first. If that works maybe then you could try using neighbor constraints (https://prioritizr.net/reference/add_neighbor_constraints.html)? These constraints -- whilst still serving to reduce spatial fragmentation -- are much simpler and do not increase the size/complexity fo the optimization problem as much as boundary penalties.

Also, you mentioned earlier that the input data were only 2GB. My guess is that the reason why prioritizr needs >25GB RAM to generate prioritization is because the 2GB data are stored in GeoTIFF format (based on the ".tif" feature names). Since data stored in GeoTIFF data format are often compressed to reduce space (e.g., kind of like putting a text file in a zip file), prioritizr/R will need much more memory to fully read/ingest/store the data and create the optimization problem. 

How does that sound?

**Comment by wk-ai** [comment]
> No worries!
> 
> Ok, it looks like you've got a lot of planning units (9 million). This is a pretty large-scale problem and will require a really good system to solve (e.g., most prioritizations use between 30k -- 1 million planning units). So I think that's the reason as to why prioritizr/R is taking up so much memory. What resolution are your data at the moment? The easiest way to address this would be resample/aggregate the data to a coarser scale (e.g., if you have 10x10 m planning units, you could try 1x1 km planning units). Is that possible? How important is it to generate the prioritization at your current scale? If that's not possible, it might be possible to generate a prioritization with the 9M planning units, but you'll likely need to get a computer/system with 150GB+ disk space, drop the boundary penalties, use the `node_file_start` parameter for Gurobi, and wait at least several days for it to run.
> 
> In general, I wouldn't recommend using boundary penalties if you have more than 250k planning units (unless spatial fragmentation is really important to your study, and you have a really, really good computer/system), because they substantially increase the complexity/size of the optimization problem. So, I'd suggest dropping the boundary penalties and seeing if you can solve it without them first. If that works maybe then you could try using neighbor constraints (https://prioritizr.net/reference/add_neighbor_constraints.html)? These constraints -- whilst still serving to reduce spatial fragmentation -- are much simpler and do not increase the size/complexity fo the optimization problem as much as boundary penalties.
> 
> Also, you mentioned earlier that the input data were only 2GB. My guess is that the reason why prioritizr needs >25GB RAM to generate prioritization is because the 2GB data are stored in GeoTIFF format (based on the ".tif" feature names). Since data stored in GeoTIFF data format are often compressed to reduce space (e.g., kind of like putting a text file in a zip file), prioritizr/R will need much more memory to fully read/ingest/store the data and create the optimization problem.
> 
> How does that sound?

Thank you for your detailed response and valuable suggestions. As part of my research, scale analysis is indeed a crucial component. I will prioritize optimizing the code according to your recommendations, taking into account factors such as problem formulation. Additionally, I'll work on expanding both the runtime memory and disk memory to accommodate larger-scale analyses.

I genuinely appreciate your guidance and will keep you updated on the progress.

**Comment by jeffreyhanson** [comment]
Ah - I see!

Yeah, to help run the analysis with that many planning units, then you'll probably also need want to consider manually preparing the data in the `data.frame` format to reduce memory usage. 

Also, if it ends up being to difficult or computationally demanding to run this with prioritizr, you could also try Zonation (see https://github.com/zonationteam/Zonation5, https://doi.org/10.1111/2041-210X.13819). Although Zonation won't provide guarantees on solution quality like prioritizr, it runs a lot faster - so it might be able to handle your large-scale dataset .

Happy to help! Yeah, please let me know if you have any further questions. If you don't have any more right now, shall we close this issue for the moment? You could re-open it later if/when you have any updates or further questions?

**Comment by wk-ai** [comment]
Thanks for your additional suggestions and insights into addressing the memory usage issue.

I appreciate the recommendation to manually prepare the data in the data.frame format to reduce memory usage, and I'll certainly explore that option.

Additionally, your suggestion to consider Zonation as an alternative solution for handling large-scale datasets is noted. I'll take a look at the Zonation repository and the paper you referenced to assess its suitability for my analysis needs.

Please go ahead and close this issue. I'll be sure to reach out if I have any further questions or updates in the future. Once again, thank you for your assistance and prompt responses.

**Comment by jeffreyhanson** [comment]
No worries! Ok, sounds good - I'll close now then. Please feel free to reopen it when if/when you have any further questions.
