### ISSUE TITLE
Different results between 7.2.2 and 8.0.4

### ISSUE THREAD

**Issue by Carina-Firkowski** [prioritizr/prioritizr#342]
Hi there,

In 2022 I worked on a project using prioritizr 7.2.2. Now, in a new phase of the project, I'm revisiting the outputs generated then. When re-running my analysis using version 8.0.4 (the latest release atm), I'm getting a different solution. I re-ran the same analysis using version 7.2.2 again, and the result is consistent with the original. This suggests something has changed since then.

I review the release notes, but couldn't identify a reason for this. Is this difference to be expected? And if so, why?

Happy to provide more details about the problem if necessary.

Thanks for clarifying,
Carina

**Comment by jeffreyhanson** [comment]
Hi,

Thanks for raising this question!

Yeah, are you using boundary penalties? We updated the underlying data strcture for the boundary matrix (still stores the same information, just in a different format) in version 8.0.2. This was to help with 3d planning and ensure correct boundary calculations when there are plannning units "stacked" on top each other. So if you generated the boundary data using an earlier version of prioritizr, you'll want to recreate it using the current version of `boundary_matrix()`. Also, we realized that this update to the data format meant that using `scales::rescale()` on boundary matrix data would produce incorrect results. In version 8.0.2.7, we added a `rescale_matrix()` to help with rescaling boundary matrix data - so if you're using `scales::rescale()` on the boundary data, then replace it with `rescale_matrix()`.

Does that help? If not, can provide some info in the problem formulation and what differences are?

**Comment by Carina-Firkowski** [comment]
Hi Jeffery,
Thanks for the reply! I'm working with a tabular problem, so not generating boundary data. Here's my problem:
```
> scenarioProblem
Conservation Problem
  planning units: data.frame (17 units)
  cost:           min: 1, max: 1
  features:       MJT, MJT4525, MJT4555, ... (29 features)
  objective:      Maximum utility objective [budget (5)]
  targets:        none
  decisions:      Binary decision 
  constraints:    <none>
  penalties:      <Linear penalties [penalty (-1)]
                   Feature weights [weights (min: 0.166666667, max: 1)]>
  portfolio:      default
  solver:         Rsymphony [first_feasible (0), gap (0), time_limit (2147483647), verbose (1)]
```

**Comment by jeffreyhanson** [comment]
Ah I see - thanks for sharing the formulation. I can't see anything obvious that would explain the difference. If possible, could you please share the code and data so I can diagnose what's going on using my computer?

**Comment by Carina-Firkowski** [comment]
Hi Jeffrey, here's the code and data for testing. Thanks!

[temp.zip](https://github.com/user-attachments/files/17014702/temp.zip)

**Comment by jeffreyhanson** [comment]
Thanks so much for putting togeather this example - it really helped a lot with tracking down the issue!

The reason why version 7.22 and 8.0.4 (latest CRAN version) give different results is due to a complicated bug in older versions of prioritizr. Although I'll provide more details below, the short answer is that version 8.0.0+ fixed the bug and is giving the correct results. This is because positive  `penalty` values for the linear penalties should result in solutions that avoid selecting planning unit with high values in `data` (per the parameters for `add_linear_penalties()`). Additionally, negative `penalty` values or the linear penalties should result in solutions that prefer selecting planning unit with high values in `data`. We can see that the current CRAN version (and developmental GitHub version) both provide this behavior with the  example dataset when using values such as `100000` or `-100000`. But version 7.2.2. doesn't provide this behavior, and so has a bug. I'm sorry about this. If you want to get the same result as version 7.2.2, I suggest using `penalty = 1` with version 8+ (i.e., instead of  `penalty = -1` for 7.2.2). But if you want to select places with higher data values, then I suggest using `-1`. How does that sound?

The explanation for this bug is a bit complicated. Originally, we introduced the linear penalties in version 5.0.1.4. Although it produced the correct result if you only compiled a problem once, it had a bug that that flipped the penalty (i.e. convert `penalty = 1` to `penalty = -1`, and vice versa) if you compiled the problem multiple times. This caused issues when running presolve checks, because (with earlier versions of the `solve()` function) a problem would be compiled once for the presolve checks and then compiled again for generating a solution. As such, the `penalty` value for the linear penalties would flipped when solving a problem with presolve checks (i.e., the default behavior). Unfortunately, we didn't catch this bug in the unit tests at the time, because the tests only compiled a problem with the penalties a single time when checking that the compiled problem was correct. This bug was fixed in version 8.0.0, when we did a massive update and -- among other things -- updated the C++ code to add guard rails for ensuring that it wouldn't alter any external R objects (meaning that there wouldn't be any side-effects from running the C++ code, this involved adding `const` before function parameters and explicitly making copies if they needed to be altered, e.g., https://github.com/prioritizr/prioritizr/blob/main/src/rcpp_apply_linear_penalties.cpp#L6).  I'll update the entry for version 8.0.0 in the NEWS file with information on this bug, so that people can find this info easier in the future.

I hope that helps? Please let me know if you have any other questions?

**Comment by Carina-Firkowski** [comment]
Hi Jeffrey, thanks for looking into this! It makes sense, as I recall being a bit puzzled by the outputs when using `penalty = 1` in version 7.2.2 and getting the opposite result than expected based on the documentation (that's why I changed it to `-1`). And also happy to hear there's nothing wrong with the actual results and I'm able to reproduce the findings with `penalty = 1` in 8.0.0+. Thanks again!

**Comment by jeffreyhanson** [comment]
No worries - thanks again for raising this issue!
