### ISSUE TITLE
Minimum shortfall objective does not work with boundary penalties

### ISSUE THREAD

**Issue by XavierCLL** [prioritizr/prioritizr#347]
Hi @jeffreyhanson and @ricschuster 

After testing and running different optimizations when the cost layer is constant, and when I use the budget as a % of the area of protection, `add_min_shortfall_objective` in my opinion, it shows more balanced results than `add_max_utility_objective`, so I use it more. However, I have had problems when I want to use  `add_min_shortfall_objective`  with `add_boundary_penalties` and I am not sure if that is a limitation of the approach, but I think it is a bug.

When I combine  `add_min_shortfall_objective`  with `add_boundary_penalties` the solution ignores completely the budget limitation and always returns 100% of the area. I prepared an example with the issue:

```R
library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
library(stringr)
library(janitor)
library(prioritizr)
library(slam)
library(gurobi)
library(glue)
library(prioritizrdata)

# load planning unit data
salt_pu <- get_salt_pu()
# load biodiversity feature data
salt_features <- get_salt_features()

salt_pu_ones <- salt_pu
salt_pu_ones[!is.na(salt_pu_ones[])] <- 1

#### working without boundary penalties

p1 <- problem(salt_pu_ones, salt_features) %>%
      add_min_shortfall_objective(10000) %>%
      add_relative_targets(1) %>%
      add_binary_decisions() %>%
      add_gurobi_solver(gap = 0.01, threads = 5)

s1 <- solve(p1)
plot(s1)

#### NOT working as expected

p2 <- problem(salt_pu_ones, salt_features) %>%
      add_min_shortfall_objective(10000) %>%
      add_boundary_penalties(penalty = 0.001) %>%
      add_relative_targets(1) %>%
      add_binary_decisions() %>%
      add_gurobi_solver(gap = 0.01, threads = 5)

s2 <- solve(p2)
plot(s2)

#### penalties working but using other method

p3 <- problem(salt_pu_ones, salt_features) %>%
      add_max_utility_objective(10000) %>%
      add_boundary_penalties(penalty = 0.001) %>%
      add_relative_targets(1) %>%
      add_binary_decisions() %>%
      add_gurobi_solver(gap = 0.01, threads = 5)

s3 <- solve(p3)

plot(s3)
```
As always, thanks so much for your help guys.

Xavier

**Comment by jeffreyhanson** [comment]
Hi @XavierCLL, thanks so much for the bug report! I'll look into this later today and let you know how it goes.

**Comment by jeffreyhanson** [comment]
Sorry, I'm having trouble replicating this issue. In particular, when I plot the second solution I see that none of the planning units are selected (shown in yellow). Is it possible that this issue might be due to a mistake in interpreting the prioritizations when plotting them? Confusingly, if a solution contains ones and zeros, then plotting it will produce a map that shows selected planning units in yellow and not selected planning units in purple. Whereas, if a solution only contains zeros, then plotting it will produce a map that shows not selected planning units in yellow.

I've included a reprex below. Please let me know if I've made a mistake, or you're seeing different behavior on your computer? If that's the case, could you please provide your session info to help with track down the issue?

```
# load packages
library(raster)
library(sf)
library(fasterize)
library(prioritizr)
library(slam)
library(gurobi)
library(prioritizrdata)

# load planning unit data
salt_pu <- get_salt_pu()
# load biodiversity feature data
salt_features <- get_salt_features()

# update costs
salt_pu_ones <- salt_pu
salt_pu_ones[!is.na(salt_pu_ones[])] <- 1

# generate prioritization without boundary penalties
## build problem
p1 <- 
  problem(salt_pu_ones, salt_features) %>%
  add_min_shortfall_objective(10000) %>%
  add_relative_targets(1) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.01, threads = 5)

## generate solution and visualize it
## we can see that this prioritization is somewhat fragmented.
## some planning units are selected (shown in yellow) and some planning
## units are not selected (shown in purple)
s1 <- solve(p1)
plot(s1)
```

![s1](https://github.com/user-attachments/assets/a83e0e1f-5bff-433b-b0b5-1bd8d1128abb)

```
# generate prioritization with boundary penalties
## build problem
p2 <- 
  problem(salt_pu_ones, salt_features) %>%
  add_min_shortfall_objective(10000) %>%
  add_boundary_penalties(penalty = 0.001) %>%
  add_relative_targets(1) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.01, threads = 5)

## generate solution and visualize it
## we can see that no planning units are selected (shown in yellow)
## this is a bit confusing because the previous plot uses the color yellow
## to denote planning units that are selected. whereas, here in this 
## plot, the color yellow is used to denote planning units that are not
## selected
s2 <- solve(p2)
plot(s2)
```

![s2](https://github.com/user-attachments/assets/c4130875-ce01-498e-afa3-9c1db891cf3b)

```
# generate prioritization with smaller boundary penalties
## build problem
p3 <- 
  problem(salt_pu_ones, salt_features) %>%
  add_min_shortfall_objective(10000) %>%
  add_boundary_penalties(penalty = 1e-7) %>%
  add_relative_targets(1) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.01, threads = 5)

## generate solution and visualize it
## we can see that this prioritization has less fragmentation than the
## first solution. similar to the first plot, some planning units are selected 
## (shown in yellow) and some planning units are not selected (shown in purple)
s3 <- solve(p3)
plot(s3)
```

![s3](https://github.com/user-attachments/assets/c42d22ed-f3bd-4008-aada-f665de7525d4)

### Session information

```
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Pacific/Auckland
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] prioritizrdata_0.3.2 gurobi_11.0-3        slam_0.1-53         
 [4] prioritizr_8.0.4.4   fasterize_1.0.5      sf_1.0-17           
 [7] raster_3.6-26        sp_2.1-4             testthat_3.2.1.1    
[10] devtools_2.4.5       usethis_3.0.0       

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.6.4    remotes_2.5.0        lattice_0.22-6      
 [4] vctrs_0.6.5          tools_4.4.1          ps_1.8.0            
 [7] parallel_4.4.1       tibble_3.2.1         proxy_0.4-27        
[10] fansi_1.0.6          pkgconfig_2.0.3      Matrix_1.7-0        
[13] KernSmooth_2.23-24   assertthat_0.2.1     lifecycle_1.0.4     
[16] compiler_4.4.1       stringr_1.5.1        brio_1.1.5          
[19] terra_1.7-83         codetools_0.2-20     httpuv_1.6.15       
[22] htmltools_0.5.8.1    class_7.3-22         later_1.3.2         
[25] pillar_1.9.0         exactextractr_0.10.0 urlchecker_1.0.1    
[28] ellipsis_0.3.2       classInt_0.4-10      cachem_1.1.0        
[31] sessioninfo_1.2.2    prompt_1.0.2         nlme_3.1-164        
[34] mime_0.12            digest_0.6.37        stringi_1.8.4       
[37] purrr_1.0.2          fastmap_1.2.0        grid_4.4.1          
[40] cli_3.6.3            magrittr_2.0.3       pkgbuild_1.4.4      
[43] utf8_1.2.4           e1071_1.7-16         ape_5.8             
[46] withr_3.0.1          promises_1.3.0       memoise_2.0.1       
[49] shiny_1.9.1          miniUI_0.1.1.1       profvis_0.3.8       
[52] rlang_1.1.4          Rcpp_1.0.13          xtable_1.8-4        
[55] glue_1.8.0           DBI_1.2.3            pkgload_1.4.0       
[58] R6_2.5.1             fs_1.6.4             units_0.8-5    
```

**Comment by jeffreyhanson** [comment]
To help address this, I've been looking into ways to specify default plotting colors for raster objects. Although we could  update prioritizr to specify default plotting colors using `terra::coltab()`  (see https://rdrr.io/cran/terra/man/colors.html) and ensure that selected planning units are always shown in one color (e.g. green) and non-selected planning units are always shown in a different color (e.g. grey), this has the unfortunate side-effect that the _terra_ won't include legend when plotting rasters with color tables. E.g., see the plot below. I worry that this would make things more confusing for users (e.g., how could someone interpret the map below if they didn't know that green = 1 and grey = 0)?

![s1](https://github.com/user-attachments/assets/2d865202-412b-4e51-b376-165c521db604)

**Comment by XavierCLL** [comment]
Hi @jeffreyhanson

Thanks so much for your detailed response! You're right! When I was testing those methods with the penalties I confused with the colors on the maps I thought that yellow (always) was displaying the solution.

Apart from the color, I tested with lower values but not at that level haha! I thought that penalty values depended on more than the problem rather than the solver method. I thought that the penalties values were independents of the solver methods, but I see that is not true, maybe because of how they use penalties inside the equations or they show different sensitivity to the penalties(?)

Tested with my data and it is working now with that level of penalties, thanks again!

**Comment by XavierCLL** [comment]
Closing this because it was not literally a bug.

**Comment by jeffreyhanson** [comment]
No worries at all! I'm glad to hear it was just an issue with colors being unintuitive.

Yeah, the penalty values do depend more on the problem (e.g., objective function) than the solver (e.g., Gurobi vs. CBC). Here, the problem has a min shortfall objective which generally has pretty small values (e.g., ranging from 0 [if the solution meets all targets] to N [if the solution doesn't select any planning units with any features, where N is the number of features]). So, we need to use really really small penalty values for this objective. For comparison, if using the min set problem, then the objective scales with the cost values because the objective function is calculacted based on cost values. As such, you would probably use a use higher `penalty` value with the min set objective than with the min shortfall objective (all else being equal, unless you had many more features than planning units). How does that sound? Let me know if you have any other questions or if anything I've written isn't clear?

**Comment by XavierCLL** [comment]
When I wrote 'solver methods' I meant objective function, sorry for the confusion, however you explained very well it, the penalties scale/depend on also with the objective function. Definitely there is a weird beaviour of the order of the colors based on the values in the rasters, but IMHO that is beyond the control of the PrioritizR.

I tested with a very small value (1e-10) just to see what happens, and it returns a wrong map (partially filled top/bottom), so what I think here is that a very small value should be like zero penalties, isn't it?. Seeing this, I feel that there is a valid penalty range that you can play with, the problem is knowing that range (e.g. for sensitivity analysis) the only way to know that range is manually testing? or is there another better way?

Thanks so much Jef!

**Comment by jeffreyhanson** [comment]
No worries!

Yeah, as the penalty values gets closer to zero, we expect to see solutions that more closely approximate a solution generated without any penalties.  Here's a small example to help show what I mean. It sounds like you might be getting something different though?

```
# load packages
library(raster)
library(sf)
library(fasterize)
library(prioritizr)
library(slam)
library(gurobi)
library(prioritizrdata)

# load planning unit data
salt_pu <- get_salt_pu()

# load biodiversity feature data
salt_features <- get_salt_features()

# update costs
salt_pu_ones <- salt_pu
salt_pu_ones[!is.na(salt_pu_ones[])] <- 1

# set penalties
blm <- c(5e-7, 1e-7, 5e-8, 1e-8, 1e-10, 0)

# generate prioritization without boundary penalties
## build problem
sols <- 
  lapply(blm, function(x) {
    p <- 
      problem(salt_pu_ones, salt_features) %>%
      add_min_shortfall_objective(10000) %>%
      add_relative_targets(1) %>%
      add_binary_decisions() %>%
      add_gurobi_solver(gap = 0.01, threads = 5)
    if (x > 0) p <- p %>% add_boundary_penalties(x)
    solve(p)
  }) %>%
  terra::rast()

# plot solutions
plot(sols, main = paste0("BLM = ", blm))
```

![sols](https://github.com/user-attachments/assets/5f40a917-d379-422c-8683-a1e539631add)

Yeah, there's a few different ways to calibrate the boundary penalties. Personally, I prefer using a heirchical approach where you set an increased budget for reducing spatial clustering. The Calibrating Trade-offs vignette has some info on this approach and various other approaches (see https://prioritizr.net/articles/calibrating_trade-offs_tutorial.html). But briefly, the main idea for the heirchical approach is that -- rather than specifying some arbitrary parameter (i.e. `penalty` value) to say how much you care about spatial fragmentation -- here you specify an increased budget to say how much extra you are will to pay (i.e., in terms of prioritization cost) to reduce spatial fragmentation. If interested, we used this approach in this paper to compare different approaches for parametrizing connectivity (https://doi.org/10.1111/1365-2664.14251). Here's an a short example below showing how to do this with the min shortfall objective.

```
# load packages
library(raster)
library(sf)
library(fasterize)
library(prioritizr)
library(slam)
library(gurobi)
library(prioritizrdata)

# specify budget
budget <- 10000

# load planning unit data
salt_pu <- get_salt_pu()

# load biodiversity feature data
salt_features <- get_salt_features()

# update costs with ones
salt_pu_ones <- salt_pu
salt_pu_ones[!is.na(salt_pu_ones[])] <- 1

# update costs with zeros
salt_pu_zeros <- salt_pu_ones * 0

# generate initial prioritization with no boundary penalties
p0 <- 
  problem(salt_pu_ones, salt_features) %>%
  add_min_shortfall_objective(budget) %>%
  add_relative_targets(1) %>%
  add_binary_decisions() %>%
  add_gurobi_solver(gap = 0.01, threads = 5)
s0 <- solve(p0)

# calculate total feature representation
fr0 <- eval_feature_representation_summary(p0, s0)

# specify percentages for increasing the budget
## note that you generally want to try between 1% to 30% increases
## in budget when using "realistic" cost values, instead of the
## 0.01% to 1% increases we use here given that the planning units
## all have cost values set to 1
budget_uplift <- c(0.001, 0.004, 0.006, 0.01)

# calculate total budgets
budget_abs <- budget * (1 +  budget_uplift)

# generate prioritization with boundary penalties
## note the following components:
##
## 1. we use min set objective so that (a) we can use zero cost values 
## so that that optimization process only cares about the boundary penalties,
## and (b) we can set targets based on how well the features are
## represented in the initial solution to ensure that all features are
## represented, at least, as good as the initial solution (e.g., if the
## initial solutions secures 32% of feature 1, then all of the following
## solutions must secure >= 32% of feature 1).
##
## 2. we use linear constraints to ensure that the total cost of the solution
## is based on the budget
##
## 3. we use a non-zero penalty value for the boundary penalties. although
## any non-zero value should theoretically give the same result; in practice,
## we don't want to use a penalty value that is too high because very large 
## values can slow down the solver due to numerical instability
##
## 4. we use previous solutions as the starting solution to help ensure
## consistency between incremental runs and speed up the optimization process

sols <- list()
for (i in seq_along(budget_abs)) {
  p <-
    problem(salt_pu_zeros, salt_features) %>%
    add_min_set_objective() %>%
    add_boundary_penalties(penalty = 1) %>%
    add_absolute_targets(fr0$absolute_held) %>%
    add_linear_constraints(budget_abs[i], "<=", salt_pu_ones) %>%
    add_binary_decisions()
  if (i == 1) {
    p <-
      p %>% add_gurobi_solver(gap = 0.01, threads = 5, start = s0)
  } else {
    p <-
      p %>% add_gurobi_solver(gap = 0.01, threads = 5, start = sols[[i - 1]])
  }
  sols[[i]] <- solve(p)
}
sols <- terra::rast(sols)
  
# plot solutions
plot(sols, main = paste0("budget uplift = ", budget_uplift * 100, "%"))
```

![sols2](https://github.com/user-attachments/assets/022d3832-f7ac-46d4-a720-15bd46debb32)

**Comment by XavierCLL** [comment]
Wow, you are the best Jef!! Always with a very detailed and useful answer.

Yes, I also expected to get, with a very low penalty value, a result pretty similar to the none penalty value result, like your demo. But that's not happening with my data, I'm getting weird results with some penalties values, but I'm going to check if something is wrong with my data first.

Awesome that approach to calibrate the boundary penalties using linear constraints with incremental budget. My only concern is that I need to keep the budget fixed in the final result, but for sensitivity analysis I can start with a budget-budget_uplift/2 to budget+budget_uplift/2 and take the middle result. Do you think that this approach is better than just running with different penalty values?
 
I didn't know that I can start a problem using a previous solution! That is a great feature! That reminds me the weather models using a warm start... thanks for the paper link.

**Comment by jeffreyhanson** [comment]
Hmm, is your budget based on the (i) number of planning units (like the example code above), or (ii) do you have cost data for your prioritizations? If (i), then I would suggest just using a penalty approach because that will bea a lot simpler. If (ii), then you could use the constraint approach, and to do this you would want to include an additional linear constraint based on the actual cost data to impose a budgetary constraint. Similar to the examples above, you would include a constraint that limits the number of selected planning units and vary the threshold among different runs. How does that sound? I could put togeather an example if useful?

**Comment by XavierCLL** [comment]
I'll go with the penalty approach, more clear if the number of pixel (area) should be fixed. However It's superb to know that there are other similar approaches. Thanks a lot for your examples!
