### ISSUE TITLE
PriritzR _Not identify meaningful priority areas

### ISSUE THREAD

**Issue by rxccx96** [prioritizr/prioritizr#348]
Dear @jeffreyhanson 
I'm currently utilizing the PriotizR package to identify new priority areas for orchids in Italy. For the planning units (PUs), I'm using the Italian grid and incorporating various normalized indices that we have calculated as features. Since we lack a specific cost layer, we have assigned a uniform cost (equal to 1) across all new PUs. Here’s the conservation problem we’ve developed:

![image](https://github.com/user-attachments/assets/689bd1b6-900e-4d45-901b-91b4b0407390)

I experimented with various conservation targets ranging from 0.1 to 0.6, but the number of planning units (PUs) remains unchanged. We continue to receive the same warning that I had to bypass to obtain a result.

Problem failed presolve checks.

These checks indicate that solutions might not identify meaningful priority areas:

✖ Most of the planning units do not have a single feature inside them.
→ This indicates that more features are needed.

What seems to be the issue, and how can I resolve it?

**Comment by jeffreyhanson** [comment]
Hi @rxccx96,

Thanks for reaching out! The presolve checks are run prior to optimization to try and identify potential issues that might lead to strange or spurious results. Here, this check is that saying that most of the planning unit's don't have any non-zero values for any features inside them. In other words, most of the planning units don't have even a single feature present inside them. This might suggest that you don't have enough biodiversity data (i.e., features) to identify meaningful priority areas across the full extent of the planning units - but this depends on your aims, so this presolve check might be a false positive.

I'll start by explaining the problem/situation that the check was designed to identify/flag. For example, let's say I was interested in identifying priority areas across the USA. So, I generate planning units across the USA using a 1 x 1 km spatial grid. Next, I obtain species range data to characterize the features. Unfortunately, I might only have access to species range data for a single US state (e.g., Washington). So, I obtain species range data for all terrestrial vertebrate species in Washington state. If I try generating a prioritization with these planning units (which cover all of the USA) and these species/features (which only have non-zeros/presences in Washington), this would lead to a spurious result. This is because I don't have enough species/feature data across the entire planning region (i.e., all of the USA) to identify the "real" priority across across the entire planning region. Although I could use these data generate a prioritization -- and it would select a bunch of planning units in Washington -- this prioritization is not well suited to my aim (i.e., of identifying priority areas across the USA). However, if my aim was instead to identify priority areas within Washington state (i.e., not across all the USA), then I would have sufficient biodiversity/feature data to do this and the prioritization that I generate based on these data would be well suited for this aim (it would just be a bit inefficient because it has a lot of superfluous planning units that aren't needed because they are outside my "real" planning region). How does that sound?

With regards to your situation, I wonder if the reason why many planning units don't have any features could be due to the fact that orchid species aren't widespread across Italy? Sorry, I'm not an expert on plants, so this might be a silly question/suggestion. For example, if there's only a handful of orcid species and they tend to have relatively small species ranges - then this might explain why most planning units don't have any features inside them? If that's the case -- and assuming you've got sufficient quality data for enough orcid species -- then I think you can ignore this warning because you'd have sufficient data to meet the aims of your study?

Another explanation/possibility could be that you're using point locality records (e.g., site records where individuals have observed species) rather than species range maps, area of habitat maps, or species distribution models to parametrize the spatial distribution of the orcid species. This can cause issues with spatial prioritizations because point records tend to have large omission errors (e.g., see http://dx.doi.org/10.1111/j.1461-0248.2006.00970.x). Is this a possibility?

**Comment by rxccx96** [comment]
Hi @jeffreyhanson,

Thank you for your quick reply.

We're using a 2x2 km cell resolution, and the orchid-related feature data covers a wide area, including the Alps, Apennines, Sicily, and Sardinia. Naturally, not every 2x2 km cell contains features (e.g., where sampling hasn't been conducted). Our data consists of point data, so we have feature values for specific geographic coordinates.

When we use the solve function and apply a forced distribution, incorporating protected areas (PAs) as locked-in, we obtain the following result:


![Figure_1](https://github.com/user-attachments/assets/1e776201-5eb7-47bc-8c37-15c98afc1a0e)

I think that the result is pretty good and follows the distribution of the different national parks but the scores that we obtained are low

The distribution appears quite accurate, aligning well with the locations of national parks. However, the scores we’re obtaining are surprisingly low.

Thanks you again

**Comment by jeffreyhanson** [comment]
No worries!

Ah, I see - yeah, I think that would explain why this presolve check is flagging a potential issue. If you're confident that sampling effort for the point locality data is spatially comprehensive across the entire study area (e.g., maybe the data derived from atlas sampling method, wherein the area is subdivided into spatial grid cells and observations are sent to each and every grid cell), then that should be fine. If not (e.g., maybe the data were collected opportunistically via citizen scientists or meuseum records?), then sampling bias might be an issue? For example, you might find that the prioritization selects many localities within exsiting protected areas -- but maybe this is simply because most of the point locality data are located in protected areas because that is where most of the sampling effort has been? In case it's helpful, this ref also talks a bit about issues with point record data (http://dx.doi.org/10.1111/j.1523-1739.2004.00434.x).

Just to clarify, which scores are you talking about? The figure only seems to show values of zero and one. Do you mean relative importance scores? If so, which method are you using to calculate them? Could you attach a figure showing what they look like?

**Comment by rxccx96** [comment]
Hi Jeffrey,

You're absolutely right; sampling bias is indeed another potential issue. However, much of our data has been collected from areas outside protected areas as well, so I think we have a good distribution of the data in the study area.

And yes, I’m referring to the relative importance score, which I calculated according to the vignette guidelines using this function:

rc_whtedge <- p %>%
  eval_ferrier_importance(s) 

This is the plot of the total importance score that we obtained: 


![image](https://github.com/user-attachments/assets/cbec3db3-2d35-4915-b0f0-6ecbb6737fd0)

What do you think?

**Comment by jeffreyhanson** [comment]
Hi,

Ah ok - thanks for clarifying that!

Yeah, it looks like most of the planning units aren't absolutely crtiical for meeitng the targets. In other words, it seems like there might be other for meeting each of the species targets seperately that aren't within the prioritization? If you look at the species-by-species score - that help reveal provide more info. 

Also, another method for characterizing the relative importance of selected planning units is using an interative process. This might be more useful here, if you don't have high endemsim? There isn't a dedicated function to do this inn prioritization, but here's some example code (https://github.com/prioritizr/prioritizr/issues/337).

**Comment by rxccx96** [comment]
Thank you so much, Jeff, for clarifying so many issues. I'll give this "silver" approach a try and see how it goes!

Thank you again!

**Comment by jeffreyhanson** [comment]
No worries - happy to help!
