### ISSUE TITLE
sf support

### ISSUE THREAD

**Issue by mstrimas** [prioritizr/prioritizr#6]
Given that `sp` will soon be superseded by `sf` (and that `sf` is much nicer) we will eventually want to consider allowing planning units to be supplied as `sf` objects.

**Comment by jeffreyhanson** [comment]
Yeah, absolutely - thanks for posting this.

**Comment by ricschuster** [comment]
@jeffreyhanson, how difficult would it be to allow supplying `sf` objects to the `problem` function?
I think a lot of people are using `sf` these days.

**Comment by jeffreyhanson** [comment]
Yeah, we could very easily create a method for `problem(x="sf", ...)` that accepts an `sf` object and converts it to an `sp` object and then calls the corresponding `problem(x="Spatial", ...)` code. Integrating `sf` at a deeper level would require more work, since we would have to update all the data extraction, boundary matrix, connected matrix, etc functions to work with `sf`.

**Comment by ricschuster** [comment]
Yeah, that's what I thought. Might be worth to create that method, but I wonder if people would then have issues with the time the conversion takes. Might be easier to insist on `sp` for now to make sure users do the conversion before calling `problem()`.

Do you think deeper integration of `sf` would result in any efficiency gains? If not, might not be worth the effort?

**Comment by jeffreyhanson** [comment]
Sorry, I completely forgot to respond to your questions @ricschuster. Yeah, large datasets will be  slowed down with the conversion issues unless we implement totally separate functions for handling `sp `and `sf` class objects (but this is not a trivial amount of work). 

Yeah, I think deeper integration of `sf` would lead to efficiency gains, since my impression is that it is faster than `rgeos` (which we use for `sp` data processing) and `rgdal` (for loading in data from shapefiles).

**Comment by jeffreyhanson** [comment]
I've added full compatibility for `sf` in the `v5` branch. This affects pretty much every function that handles spatial data (e.g. penalties, constraints, problem, solve, etc). Since we now use the `exactextractr` and `fastextract` R pckages for comparisons between vector-based and raster-based spatial data, prioritizr will be faster with `sf` than `sp` data (note using raster data will still be the fastest). This is because the `sp` class objects are converted to `sf` class objects for low-level data wrangling. Note that these changes does (or should) not break compatibility with previous versions (e.g. if you use `sp` class planning unit data in the `problem` function, then `solve` will still output `sp` class objects). 

The only version breaking change is now that `connected_matrix` function no longer has a `distance` argument for planning units represented as `SpatialPointsDataFrame` objects. If you try to use `SpatialPointsDataFrame` objects with this function, then you will now get an error. Instead, one should use the new `proximity_matrix` function which is used to identify planning units that are in close proximity to each other using a specified distance threshold. The advantage with this is that users can now create distance-based connectivity matrices for `SpatialLinesDataFrame`, `SpatialPolygonsDataFrame`, and `sf` class objects too - instead of just having this functionality available for `SpatialPointsDataFrame`. Perhaps it might be worth renaming `connected_matrix` to something else?

@ricschuster, when reviewing the changes related to `sf` integration, could you please check the files below? I'm sorry, there's quite a few files associated with this. To make this more manageable, I've grouped them under themes and added a `[  ]` to each group. When going through this, you might find it useful to edit this comment and replace the `[  ]` with a `[:heavy_check_mark:]` after finishing each group to keep track. How does that sound? Or you could copy and paste this text and update your own comment? Or we could break them up into multiple separate issues and link them back here? What do you think?


1. sf dependencies [ ]
    - `DESCRIPTION`
    - `R/sf.R` (define sf as a S4 class so we can dispatch methods)

2. Planning unit data handling functions
  * rij matrix [ ]:
      - `R/rij_matrix.R`
      - `tests/testthat/rij_matrix.R`
  * Intersecting units [ ]:
    - `R/intersecting_units.R`
    - `tests/testthat/test_intersecting_units.R`
  * Category vector [ ] :
    - `R/category_vector.R`
    - `tests/testthat/test_category_vector.R`

3. Spatial association functions
  * Boundary matrix [ ]:
      - `R/boundary_matrix.R`
      - `tests/testthat/test_boundary_matrix.R`
  * Connectivity matrix [ ]:
      - `R/connectivity_matrix.R`
      - `tests/testthat/test_connectivity_matrix.R`
  * Connected matrix [ ]:
      - `R/connected_matrix.R`
      - `tests/testthat/test_connected_matrix.R`
  * Proximity matrix [ ]:
    - `R/proximity_matrix.R`
    - `tests/testthat/test_proximity_matrix.R`

3. Penalty functions
  * Boundary penalties [ ]: 
      - `R/add_boundary_penalties.R`
      - `tests/testthat/test_add_boundary_matrix.R`
  * Connectivity penalties [ ]: 
      - `R/add_connectivity_penalties.R`
      - `tests/testthat/test_add_connectivity_penalties.R`

4. Constraint functions
  * Locked in constraints [ ]: 
      - `R/add_locked_in_constraints.R`
      - `tests/testthat/test_add_locked_in_constraints.R`
  * Locked out constraints [ ]: 
      - `R/add_locked_out_constraints.R`
      - `tests/testthat/test_add_locked_out_constraints.R`
  * Neighbor constraints [ ]: 
      - `R/add_neighbor_constraints.R`
      - `tests/testthat/test_add_neighbor_constraints.R`
  * Contiguity constraints [ ]: 
      - `R/add_contiguity_constraints.R`
      - `tests/testthat/test_add_contiguity_constraints.R`
  * Feature contiguity penalties [ ]: 
      - `R/add_feature_contiguity_constraints.R`
      - `tests/testthat/test_add_feature_contiguity_constraints.R`

5. Building problems [ ]
    - `R/ConservationProblem-proto.R`
    - `R/problem.R`
    - `tests/testthat/test_problem.R`

6. Solving problem [ ]
    - `R/solve.R`
    - `tests/testthat/test_solve.R`

7. Assorted functions for examining the performance of solutions
  *  Feature representation [ ]:
      - `R/feature_representation.R`
      - `tests/testthat/test_feature_representation.R`
  *  Rarity weighted richness [ ]:
      - `R/rarity_weighted_richness.R`
      - `tests/testthat/test_rarity_weighted_richness.R`
  *  Replacement cost [ ]:
      - `R/replacement_cost.R`
      - `tests/testthat/test_replacement_cost.R`

**Comment by mstrimas** [comment]
Wow, Jeff, this is amazing! Seems like it must have been a lot of work, but I think an important transition given that `sf` is now clearly the future of vector data in R. Anything I can do to help with review?

**Comment by jeffreyhanson** [comment]
Thanks! Yeah, I think it's really important too. Yeah, I think the more people looking this the better. Maybe you could coordinate with @ricschuster? Depending on time availability, it might be better to 
divide the files between you? Or each of you could go over all the files? What you ever works best for both of you?

I haven't actually finished the changes yet though, so the GitHub version of the v5 branch doesn't have the changes yet. I'll post here to let you both know it's ready.

**Comment by ricschuster** [comment]
Thanks very much @jeffreyhanson!

@mstrimas, I was planning to have a look at all the files Jeff has listed to get more familiar with the `prioritizr` code, but another set of eyes on anything you want to review, would be awesome.

**Comment by ricschuster** [comment]
Sorry, forgot to respond to this earlier.
re: 
> Perhaps it might be worth renaming connected_matrix to something else?

Might be a good idea and have calling connected_matrix triggering a warning/error that the function is deprecated?

**Comment by jeffreyhanson** [comment]
Yeah, we'll definitely have `connected_matrix` throw a deprecation notice when it's called. What should we call the new function? `intersection_matrix`? Overlaps isn't quite right, since it will pick up polygon units that have touching borders.

**Comment by jeffreyhanson** [comment]
Perhaps `adjacent_matrix`?

**Comment by ricschuster** [comment]
`adjacency_matrix`?

**Comment by jeffreyhanson** [comment]
Perfect!

**Comment by jeffreyhanson** [comment]
I'll just repost the file list with the new adjacency matrix files.


1. sf dependencies [ ]
    - `DESCRIPTION`
    - `R/sf.R` (define sf as a S4 class so we can dispatch methods)

2. Planning unit data handling functions
  * rij matrix [ ]:
      - `R/rij_matrix.R`
      - `tests/testthat/rij_matrix.R`
  * Intersecting units [ ]:
    - `R/intersecting_units.R`
    - `tests/testthat/test_intersecting_units.R`
  * Category vector [ ] :
    - `R/category_vector.R`
    - `tests/testthat/test_category_vector.R`

3. Spatial association functions
  * Boundary matrix [ ]:
      - `R/boundary_matrix.R`
      - `tests/testthat/test_boundary_matrix.R`
  * Connectivity matrix [ ]:
      - `R/connectivity_matrix.R`
      - `tests/testthat/test_connectivity_matrix.R`
  * Adjacency matrix [ ]:
      - `R/adjacency_matrix.R`
      - `tests/testthat/test_adjacency_matrix.R`
  * Proximity matrix [ ]:
    - `R/proximity_matrix.R`
    - `tests/testthat/test_proximity_matrix.R`

3. Penalty functions
  * Boundary penalties [ ]: 
      - `R/add_boundary_penalties.R`
      - `tests/testthat/test_add_boundary_matrix.R`
  * Connectivity penalties [ ]: 
      - `R/add_connectivity_penalties.R`
      - `tests/testthat/test_add_connectivity_penalties.R`

4. Constraint functions
  * Locked in constraints [ ]: 
      - `R/add_locked_in_constraints.R`
      - `tests/testthat/test_add_locked_in_constraints.R`
  * Locked out constraints [ ]: 
      - `R/add_locked_out_constraints.R`
      - `tests/testthat/test_add_locked_out_constraints.R`
  * Neighbor constraints [ ]: 
      - `R/add_neighbor_constraints.R`
      - `tests/testthat/test_add_neighbor_constraints.R`
  * Contiguity constraints [ ]: 
      - `R/add_contiguity_constraints.R`
      - `tests/testthat/test_add_contiguity_constraints.R`
  * Feature contiguity penalties [ ]: 
      - `R/add_feature_contiguity_constraints.R`
      - `tests/testthat/test_add_feature_contiguity_constraints.R`

5. Building problems [ ]
    - `R/ConservationProblem-proto.R`
    - `R/problem.R`
    - `tests/testthat/test_problem.R`

6. Solving problem [ ]
    - `R/solve.R`
    - `tests/testthat/test_solve.R`

7. Assorted functions for examining the performance of solutions
  *  Feature representation [ ]:
      - `R/feature_representation.R`
      - `tests/testthat/test_feature_representation.R`
  *  Rarity weighted richness [ ]:
      - `R/rarity_weighted_richness.R`
      - `tests/testthat/test_rarity_weighted_richness.R`
  *  Replacement cost [ ]:
      - `R/replacement_cost.R`
      - `tests/testthat/test_replacement_cost.R`

**Comment by mstrimas** [comment]
I'll just repost the file list with the new adjacency matrix files.
Will update this as I work through these files. [:heavy_check_mark:] means I've reviewed that section and I'll add comments where suitable for each individual file.

1. sf dependencies [:heavy_check_mark:]
    - `DESCRIPTION`: in a future release it would be good to move `sp` from Depends to Imports or even Suggests
    - `R/sf.R`

2. Planning unit data handling functions
  * rij matrix [:heavy_check_mark:]:
      - `R/rij_matrix.R`: fixed a small typo in docs
      - `tests/testthat/rij_matrix.R`
  * Intersecting units [ ]:
    - `R/intersecting_units.R`
    - `tests/testthat/test_intersecting_units.R`
  * Category vector [ ] :
    - `R/category_vector.R`
    - `tests/testthat/test_category_vector.R`

3. Spatial association functions
  * Boundary matrix [ ]:
      - `R/boundary_matrix.R`
      - `tests/testthat/test_boundary_matrix.R`
  * Connectivity matrix [ ]:
      - `R/connectivity_matrix.R`
      - `tests/testthat/test_connectivity_matrix.R`
  * Adjacency matrix [ ]:
      - `R/adjacency_matrix.R`
      - `tests/testthat/test_adjacency_matrix.R`
  * Proximity matrix [ ]:
    - `R/proximity_matrix.R`
    - `tests/testthat/test_proximity_matrix.R`

3. Penalty functions
  * Boundary penalties [ ]: 
      - `R/add_boundary_penalties.R`
      - `tests/testthat/test_add_boundary_matrix.R`
  * Connectivity penalties [ ]: 
      - `R/add_connectivity_penalties.R`
      - `tests/testthat/test_add_connectivity_penalties.R`

4. Constraint functions
  * Locked in constraints [ ]: 
      - `R/add_locked_in_constraints.R`
      - `tests/testthat/test_add_locked_in_constraints.R`
  * Locked out constraints [ ]: 
      - `R/add_locked_out_constraints.R`
      - `tests/testthat/test_add_locked_out_constraints.R`
  * Neighbor constraints [ ]: 
      - `R/add_neighbor_constraints.R`
      - `tests/testthat/test_add_neighbor_constraints.R`
  * Contiguity constraints [ ]: 
      - `R/add_contiguity_constraints.R`
      - `tests/testthat/test_add_contiguity_constraints.R`
  * Feature contiguity penalties [ ]: 
      - `R/add_feature_contiguity_constraints.R`
      - `tests/testthat/test_add_feature_contiguity_constraints.R`

5. Building problems [ ]
    - `R/ConservationProblem-proto.R`
    - `R/problem.R`
    - `tests/testthat/test_problem.R`

6. Solving problem [ ]
    - `R/solve.R`
    - `tests/testthat/test_solve.R`

7. Assorted functions for examining the performance of solutions
  *  Feature representation [ ]:
      - `R/feature_representation.R`
      - `tests/testthat/test_feature_representation.R`
  *  Rarity weighted richness [ ]:
      - `R/rarity_weighted_richness.R`
      - `tests/testthat/test_rarity_weighted_richness.R`
  *  Replacement cost [ ]:
      - `R/replacement_cost.R`
      - `tests/testthat/test_replacement_cost.R`

**Comment by jeffreyhanson** [comment]
Brilliant! Thank you @mstrimas!

**Comment by mstrimas** [comment]
Sorry for the delay on this, got sidetracked with the transition to working from home. All done now though!

Pushed a handful of small corrections, mostly to documentation. Only remaining thing that I think could be fixed is the following assertion in `R/problem.R`:
```
all(unlist(as.list(features), recursive = TRUE, use.names = FALSE) %in% names(x))
```
gets handled poorly by `assertthat`, giving `Error in stop(assertError(attr(res, "msg"))) : bad error message` if feature character vector includes a column not in `x`. Maybe it would make sense to pull this assertion out of `assertthat` and handle if with an if statement and and custom `stop()` message?

More generally, I think the documentation in some places still treats `sp` as the default. I think in future versions it would make sense to push `sp` to the background and only show `sf` examples, still keeping the ability to handle `sp`  objects, but streamlining the documentation and pushing users towards the best practice of using `sf`. Don't think this needs to happen immediately though, I see this version as a transition from `sp` to `sf`.

Finally, @jeffreyhanson, I haven't really looked at this package in awhile and going through the code and seeing what you're done with it is really amazing. The expanded functionality, amazing documentation, and well written code are all super impressive. There's no reason now why `prioritizr` shouldn't be *the* tool for solving these sorts of problems!

**Comment by mstrimas** [comment]
Oh, also, I did keep an eye out for potential issues arising from the large number of breaking changes in the most recent version of `sf`. I didn't see any obvious problems, but I'm also still getting a handle on exactly what's changed with this new version.

**Comment by jeffreyhanson** [comment]
No worries at all with the delay - thanks for making the time to work on this! I hope you're alright over there?

Thanks for fixing and pushing those documentation fixes. Yeah, I completely agree that the `Error in stop(assertError(attr(res, "msg"))) : bad error message` error messages are really unhelpful. Please let me know if you notice any more of them. With `assertthat`, you can supply a custom error message like this:

```
asserthat::assert_that(
all(unlist(as.list(features), recursive = TRUE, use.names = FALSE) %in% names(x)),
msg = "argument to features contains column names that are not present in the argument to x")
```
I'll push a fix that addresses this in a moment. 

Yeah, I agree it would be good to encourage `sf` as the default in future versions. I thought it might be a good idea to keep plenty of `sp` examples in case there are teething issues with adding `sf` that we didn't catch before the first CRAN release with `sf`.

Yeah, I haven't looked at the new `sf` version yet. I'm not sure how much of an effect this will have. I suspect we might have to update the the C++ code behind the `boundary_matrix` function to account for lon/lat column ordering for `sf` objects. Also, we'll need see if the `raster::compareCRS` function  works with the old and new `sp::CRS` and `sf::crs` classes. Once we're happy with this pull request, I can start checking issues with the new version of sf?

Thanks so much for the kinds words - I really appreciate it! Thanks again for all your contributions and be being so awesome to work with!

**Comment by mstrimas** [comment]
Didn't know that about `assert_that()`, thanks for the tip! I think we're on the same page with `sp`/`sf` transition, treating this version as transitional between the two. Unless @ricschuster wants to review this as well, I think we can close this issue.

**Comment by ricschuster** [comment]
Thanks very much to both of you!
With all my kids at home, I'm getting pretty much no work done right now, so happy to close this issue now.
