### ISSUE TITLE
Slowdown from input data checks

### ISSUE THREAD

**Issue by mstrimas** [prioritizr/prioritizr#65]
Ali Johnson as been working on some large prioritization exercises and finding that formulating the prioritization problem with problem() takes several hours. In an effort to help speed things up for her, I profiled the code and found that a ton of time was spend in the assert_that() checks. As a test, I created a fork of the package without the checks and she found the time to run problem() went from 3 hours to 4 minutes! This seems almost too good to be true, but the results from the 2 prioritizations were identical.

I think in most cases it's worth a little extra time to ensure the inputs are valid; however, for more advanced users working with large data sets, it might be worth giving the option of turning the checks off to speed things up.

How would you feel about an additional argument to the problem() function, e.g. `run_checks`, that when set to FALSE skips over these long running checks? By default, `run_checks` would be TRUE. If everyone's ok with this I can push through a quick change to implement it.

**Comment by ricschuster** [comment]
I should have gone the profiling route as well. Working on datasets of the same extent as Ali I just converted spatial data to `r rij_matrices` and solved the `r assert_that()` issue that way. 

I do very much like your proposal of adding `r run_checks` @mstrimas and would support you pushing that quick change to the master branch.

**Comment by jeffreyhanson** [comment]
Wow, I had no idea that the data input checks in problem were slowing down prioritzr so much. Thank you for diagnosing this! Out of interest, do you know if a particular check is to blame? E.g. checking maximum values in cost and feature raster objects? If so, what happens if you play with `rasterOptions` so that it loads the entire raster object into memory - does that speed up the checks?

Yeah it sounds an additional argument to skip the input checks would be useful. I really like your suggestion of naming the argument `run_checks` and having it default to `TRUE`.

Yeah, running `make docs` updates all the .Rd files, vignettes, the README, and the website pages. Since run times and solutions different depending on the seed, changing the help page for a single function can mean that a lot of .html files get updated too. I agree it's not ideal, do you know any way have _pkgdown_ update only specific files? Yeah, I can rebuild the docs after you commit the changes. 

Thanks!

**Comment by mstrimas** [comment]
Yeah, I figured that change would speed things up a bit, but was shocked by what Ali found! The slowdown seems to come from checking the maximum values. I can't recall, what's the reason for:

isTRUE(all(raster::cellStats(features, "max") > 0))

This allows negative features values, provided at least one is greater than zero. Why?

Also, no, I'm not sure how to just compile sections of the pkgdown site. Ideally it would be nice to run `make docs` on every commit, but it ends up changing so many files it's hard to keep track of what the key change was.

**Comment by jeffreyhanson** [comment]
Ah. Hmm I think that's a typo and should actually be:

```
isTRUE(all(raster::cellStats(features, "min") >= 0))
```

Thanks for catching that!

Yeah, I run `make docs` on every commit to keep the docs up to date but it really does make keeping track of important changes rather difficult. I don't know what the solution is.

**Comment by ricschuster** [comment]
How about we run `make docs` only when we increment at least minor version/release number? This way we don't update the docs all the time and the docs wouldn't be too terribly outdated I think. Alternatively we could also run `make docs` at the patch level and keep doc as is if we only make dev changes (major.minor.patch.dev).

**Comment by jeffreyhanson** [comment]
Yeah, I guess we could do that. Although it seems to me that most changes to the package, apart from zones and the shiny stuff, seem to be related to documentation and it would be a shame for the updated documentation not to be visible on the website. I generally point people to the website and have it open in my browser when walking people through _prioritizr_ stuff, so I would find it very helpful for the website to be up to date.

**Comment by mstrimas** [comment]
Ok, just pushed this change.

I agree that having the docs up to date is nice. Maybe this just means living with slightly cluttered commits. At least for this commit, I haven't run `make docs` and will let you take care of that on your next commit, Jeff. Thanks!
