### ISSUE TITLE
problem too large

### ISSUE THREAD

**Issue by faengl** [prioritizr/prioritizr#97]
Hi,

I just started using prioritizr with quite large raster-based datasets. I would like to ask for some advice concerning problem size and spatial configuration penalties and constrains.
On my system there seems to be some kind of threshold in problem size at which the solver refuses to run (just like in #53). This seems to be related to `add_boundary_penalties` and/or `add_neighbor_constraints` since it only happens when using these options.
The usual error message is `Cholmod-Fehler 'problem too large' [...] ` (in German...). This message seems to pop up if the problem is clearly too large. The optimization process is then aborted in a clean way. If the problem is just slightly too large there is a different error message (can't allocate 14GB memory, something like this). The process is not aborted and can only be stopped by killing the R process.
Also I experienced very high system load with the `add_neighbor_constraints`  and large problems. Actually I was concerned about the health of my computer...

In the following example you can change the value of `res` to produce different dimensions of pu and feature objects. Uncomment the `add_neighbor_constraints` and `add_boundary_penalties` to see influence of these options. I would be glad if someone could tell me if there is a way to solve large problems including the spatial configuration options. Unfortunately I don't have a Gurobi licence. Would that solve the problem?

```
library(prioritizr)
library(Rsymphony)

## Load tutorial data
data(sim_pu_raster)
data(sim_features)

## Set and increase resolution manually
res <- 20

## Resample PUs and features
mod_pu <- raster(nrow=res, ncol=res, xmn=0, xmx=1, ymn=0, ymx=1)
mod_pu <- resample(sim_pu_raster, mod_pu, method='ngb')

mod_feat <- raster(nrow=res, ncol=res, xmn=0, xmx=1, ymn=0, ymx=1)
mod_feat <- resample(sim_features, mod_feat, method='ngb')

## Problem definition
p1 <- problem(mod_pu, mod_feat) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  
  ## uncomment to test neighbor constraints !! watch system load !!
  # add_neighbor_constraints(2) %>%
  
  ## uncomment to test boundary penalties
  # add_boundary_penalties(penalty = 0.01) %>%
  
  add_binary_decisions() %>%
  add_rsymphony_solver(time_limit = 120)

## Show problem
show(p1)

## Solve Problem
p1 <- solve(p1)

## Plot solution
plot(p1)
```

I'm using Ubuntu 16 LTS on a system with 16GB RAM and 4 CPUs. My R version is 3.4.4.

Thanks for any help,
Falko

**Comment by jeffreyhanson** [comment]
Hey,

Thanks for reaching out. Yeah, you won't be able to solve large problems without Gurobi, but I'm surprised that Rsymphony is unable to handle boundary penalties (or neighbor constraints) with ~400 planning units. Which version of prioritizr are you using? You could try using the dev version on GitHub (using `devtools::install_github("prioritizr/prioritizr")`) which has a few tweaks in `add_boundary_penalties` and `add_connectivity_penalties` to reduce memory consumption.

I've tried running your code on my laptop (Ubuntu 16.04; 8GB RAM; 4 CPUs; R 3.4.4), and it seems to work. Could you please verify if the code I've pasted below also works on your system? I've also included the session info further below if that helps.

```
library(prioritizr)
library(Rsymphony)

## Load tutorial data
data(sim_pu_raster)
data(sim_features)

## Set and increase resolution manually
res <- 20

## Resample PUs and features
mod_pu <- raster(nrow=res, ncol=res, xmn=0, xmx=1, ymn=0, ymx=1)
mod_pu <- resample(sim_pu_raster, mod_pu, method='ngb')

mod_feat <- raster(nrow=res, ncol=res, xmn=0, xmx=1, ymn=0, ymx=1)
mod_feat <- resample(sim_features, mod_feat, method='ngb')

## Problem definition
p1 <- problem(mod_pu, mod_feat) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_binary_decisions() %>%
  add_rsymphony_solver(time_limit = 120) %>%
  add_boundary_penalties(penalty = 0.01)

## solve problem
s1 <- solve(p1)
```

----

Session information

```
sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rsymphony_0.1-28   prioritizr_4.0.2.3 proto_1.0.0        raster_2.6-7      
[5] sp_1.3-1           testthat_2.0.0     devtools_1.13.6   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18      lattice_0.20-35   crayon_1.3.4      assertthat_0.2.0 
 [5] digest_0.6.15     withr_2.1.2       grid_3.4.4        R6_2.2.2         
 [9] magrittr_1.5      pillar_1.3.0.9000 rlang_0.2.1       uuid_0.1-2       
[13] Matrix_1.2-14     rgdal_1.3-3       tools_3.4.4       parallel_3.4.4   
[17] compiler_3.4.4    memoise_1.1.0     tibble_1.4.2.9004
```

**Comment by faengl** [comment]
Hi Jeffrey,

the code does run on my system, too. But what happens if you increase the value of  ```res``` so that the spatial resolution of the planing units and features gets finer?  On my system at ```res <- 120``` I get an error "Can't allocate vector of size 14.6 GB" and at ```res <- 130 ``` "Problem too large". Maybe you can check that on your system. Also it would be interesting if there are other, possibly higher, thresholds when using Gurobi.

Here is my session info:
```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8    LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rsymphony_0.1-28 prioritizr_4.0.2 proto_1.0.0      raster_2.6-7     sp_1.2-7        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     lattice_0.20-35  assertthat_0.2.0 grid_3.4.4       magrittr_1.5     pillar_1.2.2     rlang_0.2.0     
 [8] uuid_0.1-2       Matrix_1.2-14    rgdal_1.2-20     tools_3.4.4      yaml_2.1.19      parallel_3.4.4   compiler_3.4.4  
[15] tibble_1.4.2 
```

Thanks for taking the time!

Falko

**Comment by faengl** [comment]
I forgot to mention: When I exclude the ```add_boundary_penalties``` and ```add_connectivity_penalties``` options I can increase the value of ```res``` to much higher numbers without any problems (tested for ```res <- 1500``` for example).

**Comment by jeffreyhanson** [comment]
It also looks like NEOS has a time-limit for 5 minutes and 3 GB RAM (https://neos-server.org/neos/admin.html), so you might be able to solve intermediate sized problems using their Gurobi installation (e.g. 10k planning units with boundary penalties).

**Comment by jeffreyhanson** [comment]
No worries. Thanks for opening this issue and sharing your experiences. I'll close this issue now because I think we've resolved it for the time being at least, but if you'd like to continue discussing this topic please feel free to reopen it. If you aren't able to get a Gurobi license, please open a new issue about NEOS support and I'll see what we can do.

**Comment by ricschuster** [comment]
Hi @faengl,
I would be happy to help you with setting up Gurobi for solving your problem.
I would also be interested to learn more about your project in general, as I'm originally from Austria and always curious to learn how people apply things like Marxan or prioritizr in Europe.
My email is mail <at> richard-schuster <dot> com

**Comment by magalicombes** [comment]
Hi,
I implemented some tests on Gurobi with a 60 562 cells raster, in which 21 538 cells are planning units. I works fine with the neighbor constraint and the boundary penalty. 
But I wanted to run some scenarios with connectivity, either distance-based (PU to PU) or with geographic zones created by a large grid (PU belonging to the same zone have high connectivity; PU belonging to 2 different zones have a connectivity based on the distance/other metric that is measured between the 2 zones of the large grid).
I tried to create a few connectivity matrices of dim = 60 562* 60 562 with the code you provided, and although I can create a boundary_matrix, when I try to rescale it, or try to get any information from it (eg min and max values), I get the `Cholmod 'problem too large` error. When I try to create a distance matrix I get the `cannot allocate vector of size ...` error.
So I think it's more a problem of matrices size than a PrioritizR problem, but do you think that using connectivity penalties for such large problems is feasible? Even if I can create large matrices, I wonder if Gurobi will accept them for solving.

Working with polygons or data frames for my PUlayer and features data would maybe be an option as it will reduce my matrix from 60562 * 60562 to 21538 * 21538 entries. But this may stay way too large...
I have to think about a way to use the large geographic zones (less than 100 zones, so ~ 100 * 100 matrix) connectivity rather than PU to PU connectivity. 
I had a look at MarxanConnect but the matrices problem will stay the same there, and I cannot imagine the time it will take for solving.

If you have any idea about this issue, let me know.
Thanks a lot,

Magali

**Comment by jeffreyhanson** [comment]
Hi,

Yeah, the `Cholmod` error generally means you're trying to create a matrix that is too large to fix in your computers RAM. Could you please post an example so I can see exactly how you're creating this matrix? The reason why it works for the neighbour and the boundary matrices is that we store the matrices in a sparse matrix format (i.e. `dgCMatrix-class` from the `Matrix` R package), so if most of the cells in the matrix are zero (which they tend to be since most planning units tend to have <= 4 neighbors in raster format), then this will substantially reduce the amount of RAM needed to store the matrix. 

One approach would be set a distance threshold, such that pairs of planning units which are really far apart get a value of zero. But the trick would be using a computational method which can return the identifiers (i.e. planning unit indices) and distances for pairs of planning units, without needing to compute the full distance matrix. I have played around with the FNN R package (https://rdrr.io/cran/FNN/), which can find a given number of neighbours for each planning unit, but to use this we need to have a good guess about how many planning units fall within the desired distance for each planning unit (which we might have for raster planning units, but this doesn't generalize to points, polygons, and lines-type planning units).

Cheers,

Jeff

**Comment by jeffreyhanson** [comment]
Just to keep you in the loop, I've posted a question on the rOpenSci slack to see if anyone has any ideas for efficiently creating the thresholded distance matrix, so I'll let you know if anyone has any ideas.

**Comment by magalicombes** [comment]
Hi,

Yes, sure. For the boundary matrix I used the PrioritizR function and it worked fine to create the matrix, but then when I want to rescale:
```
> b_matrix <- boundary_matrix(pulayer[[1]])
> str(b_matrix)
Formal class 'dsCMatrix' [package "Matrix"] with 7 slots
  ..@ i       : int [1:43749] 121 121 122 240 240 241 241 242 121 404 ...
  ..@ p       : int [1:60563] 0 0 0 0 0 0 0 0 0 0 ...
  ..@ Dim     : int [1:2] 60562 60562
  ..@ Dimnames:List of 2
  .. ..$ : NULL
  .. ..$ : NULL
  ..@ x       : num [1:43749] 50000 25000 50000 50000 25000 25000 25000 50000 25000 25000 ...
  ..@ uplo    : chr "U"
  ..@ factors : list()
> # standardize matrix values to lay between zero and one
> b_matrix[] <- rescale(b_matrix[])
Error in asMethod(object) : 
  Erreur Cholmod 'problem too large' dans le fichier ../Core/cholmod_dense.c, ligne 105
```

For the distance matrix I used my PUlayer transformed to points, so I get the coordinates of the raster cells centers:
```
> head(pulayer.p@coords)
            x       y
[1,] -4521201 5547590
[2,] -4496201 5547590
[3,] -4471201 5547590
[4,] -4446201 5547590
[5,] -4421201 5547590
[6,] -4396201 5547590
> d_matrix <- (1 / (as(dist(pulayer.p@coords), "Matrix") + 1))
```
Here I get `cannot allocate vector of size...`.

I saved `dist= dist(pulayer.p@coords)` and it's a `dist` format of 13Gb. I planned to set a distance threshold called `distmax` and change all the values accordingly `dist[dist>distmax] =distmax`, to then create a distance matrix with values rescaled from 1 (distmin) to 0 (distmax). As that my study area is very fragmented, I know that most of the values in the distance matrix will not be useful because related to NA cells of my PUlayer, so I can change set the matrix values to 0 for these cells as well.  I will have a look at the FNN R package, for now I did not find another way than creating the big matrix and replacing values by 0 afterwards. Thanks for asking the question on rOpenSci!

To create my own matrix and fill it as I want I made an empty `dgCMatrix-class`, and started to fill it but this was too long. I will do it on a more powerful computer.
```
i <- 1: NROW(pulayer[]); j <- 1: NROW(pulayer[]); x <- rep(0, NROW(pulayer[]))
ac_matrix <- sparseMatrix(i, j, x = x)
#fill with some R loops....
```

So I will try to create some matrices on a computer with more RAM and see what's the result size in `dgCMatrix-class`. Have you implemented PrioritizR with big connectivity matrices? I will tell you what it does when I get to this point.

Thanks
Magali

**Comment by jeffreyhanson** [comment]
Great - thanks for posting your code.

Yeah, a quick fix for rescaling the boundary penalty matrix is:

```
b@x <- rescale(b_matrix@x, to = c(0.01, 1)) 
# note that we set the lower value to 0.01 so non-zeros don't become zero
```

I haven't heard back about the distance matrix stuff, so I don't have any updates on that yet.

Yeah, I suspect that looping over every single planning unit will take a long time.

Yeah, I've made big connectivity matrices before, but they were all cases where only adjacent planning planning units had non-zero values (i.e. with raster planning units where only planning units that were directly next to each other had non-zero connectivity values). So, I'm afraid that doesn't help you much, I'm afraid.

A mate of mine was using FNN to create the thresholded distance matrix - but their planning units were in raster format so they could assume that for a given distance threshold there were at most a certain number of neighbours. If this would help you, I could email them and ask them for a copy of their code?

**Comment by magalicombes** [comment]
Thanks it worked. I am not used to this matrix format so I will read a bit about it, but changing the values from `matrix@x` seems way more efficient. I guess it only works for replacing or rescaling values and not to fill the matrix, because zeros and non zeros are not stored in the same vector of the `dsCMatrix`

```
> head(b_matrix@x)
[1] 0.34 0.01 0.34 0.34 0.01 0.01
> min(b_matrix@x)
[1] 0.01
> max(b_matrix@x)
[1] 1
```

Yes, is some code from people who already implemented thresholded distance matrices is available, that could help me to write mine. Thank you

Magali

**Comment by jeffreyhanson** [comment]
Brilliant - glad to hear that worked. Yeah, that's exactly right, when `matrix@x` we only update the non-zeros, whereas using `matrix[]` means outputting all values including the zeros.

Ok - just to double check though - this code will assume that your planning units are arranged in a regular grid (e.g. in raster format) - is that ok?

**Comment by magalicombes** [comment]
I guess it's ok, because I created my matrix with all my PUlayer raster cells, the NA cells (that are not planning units) and the "1" or "cost-value" coded cells (planning units). Then I can recode the matrix to 0 for the NA ones, or the matrix values will just be ignored by PrioritizR as these cells are coded NA.

**Comment by jeffreyhanson** [comment]
Ah ok - I've just emailed them so I'll let you know when they get back to me.

**Comment by jeffreyhanson** [comment]
Ok - it turns out my mate was using the neighbor constraints rather than the connectivity constraints with distance. In case it's helpful, I've included his code below but note that the final matrix contains 1s and 0s indicating if each planning unit is within a threshold distance, and does not contain the actual distances between them. Maybe you could modify this to suit your needs? I'll see if I can come up with a solution that outputs actual distances - but it might be a few days before I might have something that works.

```
# load packages
library (Matrix)
library(raster)
library(sp)

# set parameters
k <- 1.5e+2 # this is the maximum amount of planning units that any given
# planning unit is expected to be connected with
max_distance <- 5000 # in this case is the max distance in meters between PU (assuming projected coordinate system)

# load data
p <- "xxx.tif" # file path for cost data delineating planning units
cost_data <- raster(p)
pt <- data.frame(id = Which(!is.na(cost_data), cells = TRUE))
pt$index = seq_len(nrow(pt))
pt$x <- xFromCell(cost_data, pt$index)
pt$y <- yFromCell(cost_data, pt$index)
pt <- SpatialPointsDataFrame(coords = pt[, c("x", "y")], data = pt, 
                             proj4string = cost_data@crs)

# find k neighbors within distance
n <- RANN::nn2(pt@coords, k = k, searchtype = "radius",
               radius = max_distance)

# check if guess was too low
assertthat::assert_that(all(rowSums(n$nn.idx == 0) > 1), msg = "guess was too low")

# convert neighbors to sparse matrix
rows <- matrix(rep(seq_len(nrow(pt)), k), nrow = nrow(pt), ncol = k)
rows <- c(rows * (n[[1]] > 0))
rows <- rows[rows > 0]
rows <- pt$id[rows]
cols <- c(n[[1]])
cols <- cols[cols > 0]
cols <- pt$id[cols]

# object "m_max" should be included in conservation problem
m_max <- sparseMatrix(i = rows, j = cols, x = 1, dims = rep(ncell(cost_data), 2)) 

```

**Comment by magalicombes** [comment]
Thank you Jeffrey,
As you select the non-NA cells in `pt`, I guess that you get a matrix with just these cells. So do the cellID in `pt `and the cellID in `m_max `correspond? Because `m_max `has the raster dimension (as required by PrioritizR) but not pt. I will try and see.

**Comment by magalicombes** [comment]
Hi Jeffrey,
I understood more or less what your code does but I would not be capable to ameliorate it to get distances.

So I used the other (computational intensive) code, to generate a distance matrix, and it worked on a 130G RAM computer. But I have trouble in the last step.

```
# base file : pulayer is a raster with ~130 000 cells and ~31 000 planning units
#Planning units ID and location
pt <- data.frame(id = Which(!is.na(pulayer), cells = TRUE))
pt$index = seq_len(nrow(pt))
pt$x <- xFromCell(pulayer, pt$index)
pt$y <- yFromCell(pulayer, pt$index)

# Distance matrix with the planning units (~31 000 units)
pulayer.p = rasterToPoints(pulayer, spatial = T)
dist= rdist(pulayer.p@coords) #7Gb dist file

#set value to 0 for all dist >distmax
distmax=750000 #750km
dist[dist[]>distmax] =0

dist_mat = as(dist, "Matrix") #281Mb
dist_mat@x <- rescale(dist_mat@x, to = c(0.01, 1)) 
dist_mat@x = round(dist_mat@x, 3) #lighter with less digits?
dist_mat@Dimnames[[1]]= as.character(pt$id)
dist_mat@Dimnames[[2]]= as.character(pt$id)
```

Here I have a distance matrix with all the planning units, thresholded. I want to fill the matrix of dim `ncell(pulayer)*ncell(pulayer)` with these values. In the code below I want to identify all the non-zero pairs of planning units, to fill their connectivity value into a large `DscMatrix`

```
#Want to get the id of pairs with non zero values 
length(dist_mat@i) #These are the row numbers for each non-zero element in the lower triangle of the matrix
dist_mat@i  #0s in it!

#get the i and j vectors with all the names of columns with entries !=0, added row by row
matJ= vector()
matI=vector()
pt$Ncon= rep(NA, nrow(pt)) #store N of connected cells for each planning unit
for(i in 1: nrow(dist_mat)) {
  a= names(which(dist_mat[i,]!=0)) # ID of planning units connected to the i planning unit
  pt$Ncon[i]=length(a)
  matJ= c(matJ, as.integer(a)) #add the IDs row by row for j
 b=rep(i,length(a))
  matI= c(matI,b ) #rep the row IDs for i
  }

#Fill the matrix to be included in the conservation problem
dist_mat_pulayer <- sparseMatrix( i=matI, j=matJ, x = dist_mat@x, dims = c(ncell(pulayer), ncell(pulayer)))
```

This is still running and I think it will work but it will be long to get the loop finished. Do you have a more straightforward way to get the pairs of rows;cols corresponding to `DscMatrix@x` values?
The other steps went quite fast on the high RAM computer.

Thanks ,
Magali

**Comment by jeffreyhanson** [comment]
Hi,

Could you please try something like this and let me know if it works? I've added in a fake planning unit raster dataset to verify that the code works on my computer, so hopefully you can adapt it to your case if creating the distance matrix doesn't take too long.

```
# load packages
library(raster)
library(Matrix)
library(scales)
library(fields)

# set distmax
distmax <- 25 ### to use for debugging, you would set this to, 750000 #750km

# create pulayer
## set number of rows/columns in the grid of planning units
n_pu_rows <- 50
n_pu_cols <- 50

## simulate planning units
pulayer <- raster(matrix(1, ncol = n_pu_rows, nrow = n_pu_cols),
                  xmn = 0, xmx = n_pu_cols, ymn = 0, ymx = n_pu_rows)
pulayer[] <- 1

## set layer name, note this is important so that when we use as.data.frame
## the column "value" contains finite values for planning units and NA 
## values to indicate pixels which are not planning units
names(pulayer) <- "value" 

## randomly set cells as NA values so our simulate planning unit raster 
## in every single pixel
na_cells <- sample.int(ncell(pulayer),  ncell(pulayer) * 0.4)
pulayer[na_cells] <- NA_real_

# Create matrix with thresholded distances for only planning units
## extract data for all pixels in the raster, including pixels that aren't planning units
pt <- as.data.frame(pulayer, na.rm = FALSE, xy = TRUE)

## find out the cell indices for planning units in the raster
pu_rows <- which(!is.na(pt$value))

## distance matrix with the planning units
dist <- rdist(pt[pu_rows, c("x", "y")])  #7Gb dist file

## set value to 0 for all dist >distmax
dist[dist[] > distmax] <- 0

# Create final sparse matrix with thresholded distances 
# between planning units, and where rows/columns correspond 
# to all pixels in the raster
## work out indices for planning units in the raster
dist_indices <- which(dist > 0, arr.ind = TRUE)
sparse_dist_rows <- pu_rows[dist_indices[, 1]]
sparse_dist_cols <- pu_rows[dist_indices[, 2]]

## create the sparse matrix
sm <- sparseMatrix(i = sparse_dist_rows, j = sparse_dist_cols, 
                   x = dist[dist_indices], 
                   dims = rep(ncell(pulayer), 2))

## rescale distance matrix
sm@x <- rescale(sm@x, to = c(0.01, 1)) 

## finally don't forget to rescale matrix so that larger distances
## mean less connectivity
sm@x <- 1 / sm@x

## visualise distance matrix, maybe don't try this for very large matrices
image(sm)
```

**Comment by magalicombes** [comment]
Thanks a lot it worked great!
I may change the distante to connectivity function because the `connectivity = 1/sm@x` function is not linear. I tested `connectivity = 1.01-sm@x` which gives a connectivity value between 0.01 and 1, see graphs below (I don't know how to reduce their size, sorry).
![connectivity_function1](https://user-images.githubusercontent.com/47605044/54439392-fd01b900-4738-11e9-95e1-775a07591c19.png)

![connectivity_function2](https://user-images.githubusercontent.com/47605044/54439405-03903080-4739-11e9-98ed-5112e21d7480.png)

I just wonder if I have to fill the diagonal with the `max(connectivity)` value, but has " Cells that occur along the matrix diagonal are treated as weights which indicate that planning units are more desirable in the solution " I think it will not change anything if the diagonal stays will just zeros.

Thank you for your help,
Magali

**Comment by jeffreyhanson** [comment]
Brilliant! 

Yeah, I agree using `1.01 - rescaled distance` as opposed to `1/rescaled distance` makes more sense.

Yeah, I think you want to keep the cells along the diagonal as zeros. You would only insert non-zero values if you wanted to weight certain planning units as more important. For instance, you could calculate a connectivity value per planning unit using graph theory to upweight important planning units. In other words, given a bunch of reefs and info about how strongly connected they are with each other, you could see how much the overall connectivity among the reef is reduced when each reef is removed, and use this value to weight each reef so that reefs which are more important to overall connectivity get preference. But there are better ways of doing this, at least in my opinion, such as using the contiguity constraints.

Just to double check, have I managed to address all your questions? If so, shall I close the issue? If not, please let me know how I can help.

**Comment by magalicombes** [comment]
Ok, I will keep it as zero for now, and I think it will stay like this keep it simple.
Yes you can close the issue, thanks for the help. Maybe this code to get d_matrix for large problems could be added in the info page examples? https://prioritizr.net/reference/add_connectivity_penalties.html

Magali

**Comment by jeffreyhanson** [comment]
Yeah, that's a great idea! I'll close this issue and make a new one to update the example.
